# Generated by Django 4.1.10 on 2023-08-12 10:41

from django.db import migrations


def forward(apps, schema_editor):
    Item = apps.get_model('armory', 'Item')
    RiotGear = apps.get_model('armory', 'RiotGear')
    Weapon = apps.get_model('armory', 'Weapon')
    BaseSpell = apps.get_model('magic', 'BaseSpell')
    Character = apps.get_model('characters', 'Character')

    for model in [Item, RiotGear, Weapon, BaseSpell]:
        for obj in model.objects.filter(is_homebrew=True):
            if getattr(obj, 'extensions', None) is not None:
                obj.extensions.clear()
            try:
                character = Character.objects.get(
                    created_by=obj.created_by,
                    campaign=obj.homebrew_campaign)
            except (Character.DoesNotExist, Character.MultipleObjectsReturned):
                pass
            else:
                obj.homebrew_character = character
                obj.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(forward)
    ]
