# Generated by Django 5.0.6 on 2024-05-11 19:21

from django.db import migrations


def forwards_func(apps, schema_editor):
    Profile = apps.get_model("portal", "Profile")
    User = apps.get_model("auth", "User")

    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func)]
