from django.contrib.auth.decorators import login_required
from django.urls import path

from campaigns import views

app_name = "campaigns"

urlpatterns = [
    path("new/", login_required(views.CreateCampaignView.as_view()), name="create"),
    path(
        "new/world/",
        login_required(views.CreateCampaignWorldView.as_view()),
        name="create_world",
    ),
    path(
        "toggle_favorite/<int:pk>",
        views.XhrCampaignToggleFavoriteView.as_view(),
        name="xhr_toggle_favorite",
    ),
    path(
        "<slug:slug>/clone",
        login_required(views.CloneCampaignView.as_view()),
        name="clone",
    ),
    path(
        "clone_modal/<slug:slug>",
        views.XhrCloneCampaignModalView.as_view(),
        name="xhr_clone_modal",
    ),
    path(
        "new/<int:world_pk>/",
        views.CreateCampaignEpochView.as_view(),
        name="create_epoch",
    ),
    path(
        "new/<int:world_pk>/<int:epoch_pk>)/",
        views.CreateCampaignExtensionsView.as_view(),
        name="create_extensions",
    ),
    path(
        "new/data/<int:world_pk>/<int:epoch_pk>/",
        views.CreateCampaignDataView.as_view(),
        name="create_data",
    ),
    path("<slug:slug>", views.CampaignDetailView.as_view(), name="detail"),
    path(
        "<slug:slug>/invite/<hash>",
        views.CampaignDetailView.as_view(),
        name="detail",
    ),
    path(
        "detail/settings/<int:pk>/<str:mode>",
        views.XhrCampaignSettingsView.as_view(),
        name="xhr_campaign_settings",
    ),
    path("dice_log/<int:pk>", views.XhrDiceLogView.as_view(), name="xhr_dice_log"),
    path(
        "xhr_campaign_fragment/<int:pk>/<fragment_template>",
        views.XhrCampaignFragmentView.as_view(),
        name="xhr_campaign_fragment",
    ),
    path(
        "plot_preview/<int:pk>/<int:plot_pk>",
        views.XhrCampaignPlotPreviewView.as_view(),
        name="xhr_plot_preview",
    ),
    path(
        "assign_plot/<int:pk>/<int:plot_pk>",
        views.XhrAssignCampaignPlotView.as_view(),
        name="xhr_assign_plot",
    ),
    path(
        "remove_plot/<int:pk>",
        views.XhrRemoveCampaignPlotView.as_view(),
        name="xhr_remove_plot",
    ),
    path(
        "remove_plot_modal/<int:pk>",
        views.XhrRemoveCampaignPlotModalView.as_view(),
        name="xhr_remove_plot_modal",
    ),
    path(
        "remove_character/<int:pk>/<int:character_pk>",
        views.XhrRemoveCharacterView.as_view(),
        name="xhr_remove_character",
    ),
    path(
        "switch_npc/<int:pk>/<int:character_pk>",
        views.XhrSwitchCharacterNPCView.as_view(),
        name="xhr_switch_npc",
    ),
    path(
        "add_foe/<int:pk>/<int:foe_pk>",
        views.XhrAddFoeToCampaignView.as_view(),
        name="xhr_add_foe",
    ),
    path(
        "remove_foe/<int:pk>/<int:foe_pk>",
        views.XhrRemoveFoeView.as_view(),
        name="xhr_remove_foe",
    ),
    path(
        "search_foe/<int:pk>",
        views.XhrSearchFoeSidebarView.as_view(),
        name="xhr_search_foe",
    ),
    path(
        "select_npc/<int:pk>",
        views.XhrSelectNPCView.as_view(),
        name="xhr_select_npc",
    ),
    path(
        "clone_npc/<int:pk>/<int:character_pk>",
        views.CloneNPCView.as_view(),
        name="clone_npc",
    ),
    path(
        "assign_npc/<int:pk>/<int:character_pk>",
        views.AssignNPCView.as_view(),
        name="assign_npc",
    ),
    path(
        "sidebar/<int:pk>/<sidebar_template>",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar",
    ),
    path(
        "sidebar/character/<int:pk>/<sidebar_template>",
        views.XhrCharacterSidebarView.as_view(),
        name="xhr_character_sidebar",
    ),
    path(
        "sidebar/foe/<int:pk>/<sidebar_template>",
        views.XhrFoeSidebarView.as_view(),
        name="xhr_foe_sidebar",
    ),
    path(
        "sidebar/plot/handout/<int:campaign_pk>/<int:pk>",
        views.XhrPlotHandoutSidebarView.as_view(),
        name="xhr_handout_sidebar",
    ),
    path(
        "sidebar/plot/location/<int:campaign_pk>/<int:pk>",
        views.XhrPlotLocationSidebarView.as_view(),
        name="xhr_location_sidebar",
    ),
    path(
        "sidebar/plot/foe/<int:campaign_pk>/<int:pk>",
        views.XhrPlotFoeSidebarView.as_view(),
        name="xhr_plot_foe_sidebar",
    ),
    path(
        "game_log/<int:campaign_pk>",
        views.XhrCampaignGameLogView.as_view(),
        name="xhr_game_log",
    ),
]
