# Generated by Django 5.2.3 on 2025-06-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("armory", "0031_alter_riotgearmodifier_aspect"),
        ("campaigns", "0014_remove_campaign_act_date_campaign_ingame_act_date"),
        ("characters", "0021_contact"),
        ("rules", "0015_lineage_base_contacts_lineage_base_languages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleStatusEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "speed_modifier",
                    models.IntegerField(default=0, verbose_name="speed modifier"),
                ),
                (
                    "handling_modifier",
                    models.IntegerField(default=0, verbose_name="handling modifier"),
                ),
                (
                    "armor_modifier",
                    models.IntegerField(default=0, verbose_name="armor modifier"),
                ),
                (
                    "power_modifier",
                    models.IntegerField(default=0, verbose_name="power modifier"),
                ),
                (
                    "evasion_modifier",
                    models.IntegerField(default=0, verbose_name="evasion modifier"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=1,
                        help_text="Duration in rounds, -1 for permanent",
                        verbose_name="duration",
                    ),
                ),
                (
                    "is_positive",
                    models.BooleanField(default=False, verbose_name="is positive"),
                ),
            ],
            options={
                "verbose_name": "vehicle status effect",
                "verbose_name_plural": "vehicle status effects",
            },
        ),
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_renewable",
                    models.BooleanField(default=False, verbose_name="is renewable"),
                ),
                (
                    "energy_density",
                    models.IntegerField(default=100, verbose_name="energy density"),
                ),
                (
                    "cost_per_unit",
                    models.IntegerField(default=1, verbose_name="cost per unit"),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fuel_types",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuel type",
                "verbose_name_plural": "fuel types",
            },
        ),
        migrations.CreateModel(
            name="MountPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "mount_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon Mount"),
                            ("equipment", "Equipment Mount"),
                            ("armor", "Armor Mount"),
                            ("engine", "Engine Mount"),
                            ("special", "Special Mount"),
                        ],
                        default="weapon",
                        max_length=20,
                        verbose_name="mount type",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("huge", "Huge"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="size",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("rear", "Rear"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("turret", "Turret (360°)"),
                        ],
                        default="front",
                        max_length=10,
                        verbose_name="direction",
                    ),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mount_points",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
            ],
            options={
                "verbose_name": "mount point",
                "verbose_name_plural": "mount points",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "crew_required",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum number of crew needed to operate",
                        verbose_name="crew required",
                    ),
                ),
                (
                    "passenger_capacity",
                    models.IntegerField(default=0, verbose_name="passenger capacity"),
                ),
                (
                    "cargo_capacity",
                    models.FloatField(
                        default=0,
                        help_text="Cargo capacity in kg",
                        verbose_name="cargo capacity",
                    ),
                ),
                (
                    "max_speed",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum speed in km/h",
                        verbose_name="maximum speed",
                    ),
                ),
                (
                    "acceleration",
                    models.FloatField(
                        default=0,
                        help_text="Acceleration rate",
                        verbose_name="acceleration",
                    ),
                ),
                (
                    "handling",
                    models.IntegerField(
                        default=0, help_text="Handling rating", verbose_name="handling"
                    ),
                ),
                (
                    "durability",
                    models.IntegerField(
                        default=10,
                        help_text="Vehicle health points",
                        verbose_name="durability",
                    ),
                ),
                (
                    "armor",
                    models.IntegerField(
                        default=0, help_text="Damage reduction", verbose_name="armor"
                    ),
                ),
                (
                    "fuel_capacity",
                    models.FloatField(default=0, verbose_name="fuel capacity"),
                ),
                (
                    "fuel_efficiency",
                    models.FloatField(
                        default=0,
                        help_text="Distance per unit of fuel",
                        verbose_name="fuel efficiency",
                    ),
                ),
                (
                    "range",
                    models.IntegerField(
                        default=0, help_text="Maximum range in km", verbose_name="range"
                    ),
                ),
                (
                    "energy_capacity",
                    models.IntegerField(
                        default=0,
                        help_text="Energy storage capacity",
                        verbose_name="energy capacity",
                    ),
                ),
                (
                    "power_output",
                    models.IntegerField(
                        default=0,
                        help_text="Power generated",
                        verbose_name="power output",
                    ),
                ),
                (
                    "length",
                    models.FloatField(
                        default=0, help_text="Length in meters", verbose_name="length"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        default=0, help_text="Width in meters", verbose_name="width"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=0, help_text="Height in meters", verbose_name="height"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0, help_text="Weight in kg", verbose_name="weight"
                    ),
                ),
                (
                    "evasion",
                    models.IntegerField(
                        default=0,
                        help_text="Ability to avoid attacks",
                        verbose_name="evasion",
                    ),
                ),
                (
                    "stealth",
                    models.IntegerField(
                        default=0, help_text="Stealth rating", verbose_name="stealth"
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=10,
                        verbose_name="rarity",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="price")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="vehicle_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "tech_level",
                    models.IntegerField(
                        choices=[
                            (1, "Primitive"),
                            (2, "Basic"),
                            (3, "Advanced"),
                            (4, "Futuristic"),
                            (5, "Cutting-Edge"),
                            (6, "Alien/Otherworldly"),
                        ],
                        default=2,
                        verbose_name="tech level",
                    ),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vehicles",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.fueltype",
                        verbose_name="fuel type",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleMachinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("weight", models.FloatField(default=0, verbose_name="weight")),
                ("price", models.IntegerField(default=0, verbose_name="price")),
                (
                    "required_mount_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon Mount"),
                            ("equipment", "Equipment Mount"),
                            ("armor", "Armor Mount"),
                            ("engine", "Engine Mount"),
                            ("special", "Special Mount"),
                        ],
                        max_length=20,
                        verbose_name="required mount type",
                    ),
                ),
                (
                    "required_mount_size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("huge", "Huge"),
                        ],
                        max_length=10,
                        verbose_name="required mount size",
                    ),
                ),
                (
                    "power_consumption",
                    models.IntegerField(
                        default=0,
                        help_text="Energy units required",
                        verbose_name="power consumption",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="vehicle_machinery_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vehicle_machinery",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_machinery",
                        to="armory.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_machinery",
                        to="armory.weapon",
                        verbose_name="weapon",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle machinery",
                "verbose_name_plural": "vehicle machinery",
            },
        ),
        migrations.CreateModel(
            name="VehicleMountPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="custom name",
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="is operational"),
                ),
                (
                    "damage_level",
                    models.IntegerField(default=0, verbose_name="damage level"),
                ),
                (
                    "mount_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.mountpoint",
                    ),
                ),
                (
                    "mounted_machinery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.vehiclemachinery",
                        verbose_name="mounted machinery",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle mount point",
                "verbose_name_plural": "vehicle mount points",
                "unique_together": {("vehicle", "mount_point")},
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="mount_points",
            field=models.ManyToManyField(
                related_name="vehicles",
                through="vehicles.VehicleMountPoint",
                to="vehicles.mountpoint",
                verbose_name="mount points",
            ),
        ),
        migrations.CreateModel(
            name="ActiveVehicleStatusEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remaining_duration",
                    models.IntegerField(default=1, verbose_name="remaining duration"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="applied at"),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_effects_applied",
                        to="characters.character",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_status_effects",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "status_effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehiclestatuseffect",
                    ),
                ),
            ],
            options={
                "verbose_name": "active vehicle status effect",
                "verbose_name_plural": "active vehicle status effects",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_flying",
                    models.BooleanField(default=False, verbose_name="is flying"),
                ),
                (
                    "is_water",
                    models.BooleanField(default=False, verbose_name="is water"),
                ),
                (
                    "is_space",
                    models.BooleanField(default=False, verbose_name="is space"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vehicle_types",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle type",
                "verbose_name_plural": "vehicle types",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicletype",
                verbose_name="vehicle type",
            ),
        ),
    ]
