# Generated by Django 5.2.9 on 2025-12-23 14:32

import phasesix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemachinery",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
    ]
