# Generated by Django 6.0.6 on 2026-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_image_alter_vehiclemachinery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
        migrations.AddField(
            model_name='vehiclemachinery',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='vehiclemachinery',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
    ]
