from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from .views import (
    PlotEditorView,
    PlotListView,
    XhrCreatePlotView,
    XhrCreatePlotFromDescriptionView,
    XhrUpdatePlotView,
    XhrCreatePlotElementView,
    XhrUpdatePlotElementView,
    DeletePlotElementView,
    XhrCreateHandoutView,
    XhrUpdateHandoutView,
    DeleteHandoutView,
    AssignHandoutView,
    XhrCreateLocationView,
    XhrUpdateLocationView,
    DeleteLocationView,
    AssignLocationView,
    XhrSelectPlotNpcView,
    XhrSelectPlotFoeView,
    AddPlotNpcView,
    AssignPlotNpcView,
    DeletePlotNpcView,
    AssignPlotFoeView,
    DeletePlotFoeView,
    XhrUpdatePlotNpcView,
    XhrUpdatePlotFoeView,
    XhrPlotFragmentView,
    XhrCampaignPlotViewFragment,
    XhrReorderPlotElementView,
)

app_name = "plots"

urlpatterns = [
    path("", staff_member_required(PlotListView.as_view()), name="list_plots"),
    path(
        "create", staff_member_required(XhrCreatePlotView.as_view()), name="create_plot"
    ),
    path(
        "<int:pk>/edit",
        staff_member_required(XhrUpdatePlotView.as_view()),
        name="update_plot",
    ),
    path(
        "<int:pk>/from-description",
        staff_member_required(XhrCreatePlotFromDescriptionView.as_view()),
        name="create_plot_from_description",
    ),
    path(
        "<int:pk>/editor",
        staff_member_required(PlotEditorView.as_view()),
        name="plot_editor",
    ),
    path(
        "xhr_plot_fragment/<int:pk>/<fragment_template>",
        staff_member_required(XhrPlotFragmentView.as_view()),
        name="xhr_plot_fragment",
    ),
    path(
        "xhr_campaign_plot_view/<int:campaign_pk>/<int:plot_pk>",
        staff_member_required(XhrCampaignPlotViewFragment.as_view()),
        name="xhr_campaign_plot_view",
    ),
    path(
        "xhr_reorder_plot_element",
        staff_member_required(XhrReorderPlotElementView.as_view()),
        name="xhr_reorder_plot_element",
    ),
    # PlotElement
    path(
        "<int:plot_pk>/plot_element/create",
        staff_member_required(XhrCreatePlotElementView.as_view()),
        name="create_plot_element",
    ),
    path(
        "plot_element/<int:pk>/update",
        staff_member_required(XhrUpdatePlotElementView.as_view()),
        name="update_plot_element",
    ),
    path(
        "plot_element/<int:pk>/delete",
        staff_member_required(DeletePlotElementView.as_view()),
        name="delete_plot_element",
    ),
    # Handouts and Locations
    path(
        "<int:plot_element_pk>/handout/create",
        staff_member_required(XhrCreateHandoutView.as_view()),
        name="create_handout",
    ),
    path(
        "<int:plot_element_pk>/handout/<int:pk>/update",
        staff_member_required(XhrUpdateHandoutView.as_view()),
        name="update_handout",
    ),
    path(
        "<int:plot_element_pk>/handout/<int:pk>/delete",
        staff_member_required(DeleteHandoutView.as_view()),
        name="delete_handout",
    ),
    path(
        "<int:plot_element_pk>/handout/<int:handout_pk>/assign",
        staff_member_required(AssignHandoutView.as_view()),
        name="assign_handout",
    ),
    path(
        "<int:plot_element_pk>/location/create",
        staff_member_required(XhrCreateLocationView.as_view()),
        name="create_location",
    ),
    path(
        "<int:plot_element_pk>/location/<int:pk>/update",
        staff_member_required(XhrUpdateLocationView.as_view()),
        name="update_location",
    ),
    path(
        "<int:plot_element_pk>/location/<int:pk>/delete",
        staff_member_required(DeleteLocationView.as_view()),
        name="delete_location",
    ),
    path(
        "<int:plot_element_pk>/location/<int:location_pk>/assign",
        staff_member_required(AssignLocationView.as_view()),
        name="assign_location",
    ),
    path(
        "plot_element/<int:pk>/npc/select",
        staff_member_required(XhrSelectPlotNpcView.as_view()),
        name="select_plot_npc",
    ),
    path(
        "plot_element/<int:pk>/foe/select",
        staff_member_required(XhrSelectPlotFoeView.as_view()),
        name="select_plot_foe",
    ),
    path(
        "plot_element/<int:pk>/npc/<int:character_pk>/add",
        staff_member_required(AddPlotNpcView.as_view()),
        name="add_plot_npc",
    ),
    path(
        "plot_element/<int:pk>/npc/<int:character_pk>/assign",
        staff_member_required(AssignPlotNpcView.as_view()),
        name="assign_plot_npc",
    ),
    path(
        "plot_element/<int:plot_element_pk>/npc/<int:pk>/delete",
        staff_member_required(DeletePlotNpcView.as_view()),
        name="delete_plot_npc",
    ),
    path(
        "plot_element/<int:pk>/foe/<int:foe_pk>/assign",
        staff_member_required(AssignPlotFoeView.as_view()),
        name="assign_plot_foe",
    ),
    path(
        "plot_element/<int:plot_element_pk>/foe/<int:pk>/delete",
        staff_member_required(DeletePlotFoeView.as_view()),
        name="delete_plot_foe",
    ),
    path(
        "plot_element/<int:plot_element_pk>/npc/<int:pk>/update",
        staff_member_required(XhrUpdatePlotNpcView.as_view()),
        name="update_plot_npc",
    ),
    path(
        "plot_element/<int:plot_element_pk>/foe/<int:pk>/update",
        staff_member_required(XhrUpdatePlotFoeView.as_view()),
        name="update_plot_foe",
    ),
]
