# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseSpell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                (
                    "is_tirakan_spell",
                    models.BooleanField(default=False, verbose_name="is tirakan spell"),
                ),
                (
                    "spell_point_cost",
                    models.IntegerField(verbose_name="spell point cost"),
                ),
                (
                    "arcana_cost",
                    models.IntegerField(default=1, verbose_name="arcana cost"),
                ),
                ("power", models.IntegerField(default=1, verbose_name="power")),
                ("range", models.IntegerField(default=0, verbose_name="range")),
                ("actions", models.IntegerField(default=1, verbose_name="actions")),
                (
                    "is_ritual",
                    models.BooleanField(default=False, verbose_name="is ritual"),
                ),
                ("name_de", models.CharField(max_length=80, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="name"
                    ),
                ),
                ("rules_de", models.TextField(verbose_name="rules")),
                (
                    "rules_en",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "quote",
                    models.TextField(blank=True, null=True, verbose_name="quote"),
                ),
                (
                    "quote_author",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="quote author",
                    ),
                ),
            ],
            options={
                "verbose_name": "base spell",
                "verbose_name_plural": "base spells",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SpellOrigin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
                (
                    "fa_icon_class",
                    models.CharField(
                        default="fas fa-book",
                        max_length=30,
                        verbose_name="FA Icon Class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="spellorigin_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
            ],
            options={
                "verbose_name": "spell origin",
                "verbose_name_plural": "spell origins",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SpellShape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "spell shape",
                "verbose_name_plural": "spell shapes",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SpellTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=120, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="name"
                    ),
                ),
                (
                    "spell_point_cost",
                    models.IntegerField(default=1, verbose_name="spell point cost"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "rules_de",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "rules_en",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "quote",
                    models.TextField(blank=True, null=True, verbose_name="quote"),
                ),
                (
                    "quote_author",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="quote author",
                    ),
                ),
            ],
            options={
                "verbose_name": "spell template",
                "verbose_name_plural": "spell templates",
            },
        ),
        migrations.CreateModel(
            name="SpellTemplateCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=120, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "spell template category",
                "verbose_name_plural": "spell template categories",
            },
        ),
        migrations.CreateModel(
            name="SpellTemplateModifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("power", "power"),
                            ("range", "range"),
                            ("actions", "actions"),
                            ("arcana_cost", "arcana"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="attribute",
                    ),
                ),
                (
                    "attribute_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="attribute modifier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
                (
                    "fa_icon_class",
                    models.CharField(
                        default="fas fa-book",
                        max_length=30,
                        verbose_name="FA Icon Class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="spelltype_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
            ],
            options={
                "verbose_name": "spell type",
                "verbose_name_plural": "spell types",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SpellVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "spell variant",
                "verbose_name_plural": "spell variants",
                "ordering": ("id",),
            },
        ),
    ]
