# Generated by Django 5.1 on 2024-08-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0004_basespell_homebrew_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="basespell",
            name="duration",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="duration"
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="needs_concentration",
            field=models.BooleanField(
                default=False, verbose_name="needs concentration"
            ),
        ),
    ]
