# Generated by Django 5.1 on 2024-08-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0006_rename_duration_basespell_duration_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basespell",
            name="is_tirakan_spell",
        ),
    ]
