# Generated by Django 5.1 on 2024-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0008_remove_basespell_power_basespell_duration_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basespell",
            name="duration_de",
            field=models.CharField(
                blank=True,
                help_text="Leave empty for instantaneous spells",
                max_length=40,
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AlterField(
            model_name="basespell",
            name="duration_en",
            field=models.CharField(
                blank=True,
                help_text="Leave empty for instantaneous spells",
                max_length=40,
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AlterField(
            model_name="basespell",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rounds", "rounds"),
                    ("seconds", "seconds"),
                    ("minutes", "minutes"),
                    ("hours", "hours"),
                    ("days", "days"),
                    ("nights", "nights"),
                    ("weeks", "weeks"),
                    ("months", "months"),
                    ("years", "years"),
                ],
                max_length=10,
                null=True,
                verbose_name="duration unit",
            ),
        ),
    ]
