# Generated by Django 3.2.7 on 2021-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0021_spelltype_supplemental_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellTemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'spell template category',
                'verbose_name_plural': 'spell template categories',
            },
        ),
    ]
