# Generated by Django 3.2.7 on 2021-10-31 17:12

from django.db import migrations


def add_basic_category(apps, schema_editor):
    SpellTemplateCategory = apps.get_model('magic', 'SpellTemplateCategory')
    SpellTemplateCategory.objects.create(
        name_en='Basic',
        name_de='Grundlegend')


class Migration(migrations.Migration):
    dependencies = [
        ('magic', '0022_spelltemplatecategory'),
    ]

    operations = [
        migrations.RunPython(add_basic_category)
    ]
