# Generated by Django 3.2.7 on 2021-10-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0023_auto_20211031_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelltemplate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magic.spelltemplatecategory'),
            preserve_default=False,
        ),
    ]
