# Generated by Django 3.2.9 on 2022-01-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0068_alter_attribute_options'),
        ('magic', '0024_spelltemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelltype',
            name='reference_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.attribute', verbose_name='reference attribute'),
            preserve_default=False,
        ),
    ]
