# Generated by Django 3.2.9 on 2022-01-03 16:10

from django.db import migrations


def assign_attribute(apps, schema_editor):
    SpellType = apps.get_model('magic', 'SpellType')
    Attribute = apps.get_model('rules', 'Attribute')

    for st in SpellType.objects.all():
        st.reference_attribute = Attribute.objects.get(name_en__iexact=st.dominant_attribute.strip())
        st.save()


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0025_spelltype_reference_attribute'),
    ]

    operations = [
        migrations.RunPython(assign_attribute)
    ]
