# Generated by Django 3.2.9 on 2022-01-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0026_auto_20220103_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spelltype',
            name='dominant_attribute',
        ),
        migrations.RemoveField(
            model_name='spelltype',
            name='supplemental_attribute',
        ),
    ]
