# Generated by Django 3.2.12 on 2022-02-12 21:11

from django.db import migrations


def set_arcana(apps, schema_editor):
    BaseSpell = apps.get_model('magic', 'BaseSpell')
    for b in BaseSpell.objects.all():
        b.arcana_cost = 0
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0027_auto_20220103_1623'),
    ]

    operations = [
        migrations.RunPython(set_arcana)
    ]
