# Generated by Django 3.2.12 on 2022-05-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_epoch'),
        ('magic', '0029_auto_20220402_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='basespell',
            name='homebrew_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='basespell',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='is homebrew'),
        ),
    ]
