# Generated by Django 3.2.12 on 2022-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0030_auto_20220502_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='basespell',
            name='keep_as_homebrew',
            field=models.BooleanField(default=False, help_text='This was not accepted as general spell and is kept as homebrew.', verbose_name='keep as homebrew'),
        ),
    ]
