# Generated by Django 3.2.12 on 2022-06-17 16:59

from django.db import migrations


def spell_description_stars(apps, schema_editor):
    BaseSpell = apps.get_model('magic', 'BaseSpell')
    for b in BaseSpell.objects.all():
        if b.rules_en:
            b.rules_en = b.rules_en.replace('*', r'\*').replace('<', '__').replace('>', '__').replace('power', 'Power')
        if b.rules_de:
            b.rules_de = b.rules_de.replace('*', r'\*').replace('<', '__').replace('>', '__')
        if b.rules_en or b.rules_de:
            b.save()


class Migration(migrations.Migration):
    dependencies = [
        ('magic', '0031_basespell_keep_as_homebrew'),
    ]

    operations = [
        migrations.RunPython(spell_description_stars)
    ]
