# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0032_auto_20220617_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelltype',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='spelltype_images', verbose_name='image'),
        ),
    ]
