# Generated by Django 4.1.3 on 2022-12-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0033_alter_spelltype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('fa_icon_class', models.CharField(default='fas fa-book', max_length=30, verbose_name='FA Icon Class')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='spelltype_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
            ],
            options={
                'verbose_name': 'spell origin',
                'verbose_name_plural': 'spell origins',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='basespell',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magic.spellorigin', verbose_name='origin'),
        ),
    ]
