# Generated by Django 4.1.3 on 2022-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0034_spellorigin_basespell_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellorigin',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='spellorigin_images', verbose_name='image'),
        ),
    ]
