# Generated by Django 5.1.2 on 2024-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_alter_templatemodifier_aspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuseffect",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("text-white", "White"),
                    ("text-success", "Success"),
                    ("text-primary", "Primary"),
                    ("text-secondary", "Secondary"),
                    ("text-warning", "Warning"),
                    ("text-danger", "Danger"),
                ],
                default="text-white",
                max_length=20,
                verbose_name="color class",
            ),
        ),
    ]
