# Generated by Django 5.1.2 on 2024-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0005_alter_statuseffect_color_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_mastery",
            field=models.BooleanField(default=False, verbose_name="is mastery"),
        ),
    ]
