# Generated by Django 5.1.2 on 2024-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0007_template_homebrew_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_magical",
            field=models.BooleanField(default=False, verbose_name="is magical"),
        ),
    ]
