# Generated by Django 5.1.5 on 2025-01-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0008_skill_is_magical"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="exclusive_languages",
            field=models.BooleanField(
                default=False, help_text="Don't allow epoch languages if this is set."
            ),
        ),
    ]
