# Generated by Django 5.1.7 on 2025-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0009_extension_exclusive_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="base_biostrain",
            field=models.IntegerField(default=0, verbose_name="biostrain"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_energy",
            field=models.IntegerField(default=0, verbose_name="energy"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_body",
            field=models.IntegerField(default=4, verbose_name="sockets body"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_head",
            field=models.IntegerField(default=2, verbose_name="sockets head"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_left_arm",
            field=models.IntegerField(default=2, verbose_name="sockets left arm"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_left_leg",
            field=models.IntegerField(default=2, verbose_name="sockets left leg"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_right_arm",
            field=models.IntegerField(default=2, verbose_name="sockets right arm"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_right_leg",
            field=models.IntegerField(default=2, verbose_name="sockets right leg"),
        ),
    ]
