# Generated by Django 5.1.7 on 2025-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0010_lineage_base_biostrain_lineage_base_energy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineage",
            name="base_sockets_head",
            field=models.IntegerField(default=1, verbose_name="sockets head"),
        ),
    ]
