# Generated by Django 5.1.7 on 2025-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0011_alter_lineage_base_sockets_head"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineage",
            name="base_biostrain",
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_bio_strain",
            field=models.IntegerField(default=0, verbose_name="bio strain"),
        ),
    ]
