# Generated by Django 5.1.7 on 2025-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0012_remove_lineage_base_biostrain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineage",
            name="base_sockets_body",
        ),
        migrations.AddField(
            model_name="lineage",
            name="base_sockets_torso",
            field=models.IntegerField(default=4, verbose_name="sockets torso"),
        ),
    ]
