# Generated by Django 5.2.4 on 2025-07-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_alter_foe_wiki_page"),
        ("characters", "0022_character_base_stress"),
        ("rules", "0016_lineage_base_base_stress_and_more"),
        ("worlds", "0032_auto_20250522_1046"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoeResistanceOrWeakness",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "foe resistance or weakness",
                "verbose_name_plural": "foe resistances or weaknesses",
            },
        ),
        migrations.CreateModel(
            name="FoeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "foe type",
                "verbose_name_plural": "foe types",
            },
        ),
        migrations.CreateModel(
            name="Foe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=120, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="name"
                    ),
                ),
                (
                    "short_description_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                ("health", models.IntegerField(default=6, verbose_name="health")),
                ("movement", models.IntegerField(default=4, verbose_name="movement")),
                ("strength", models.IntegerField(default=2, verbose_name="strength")),
                ("dexterity", models.IntegerField(default=2, verbose_name="dexterity")),
                ("mind", models.IntegerField(default=2, verbose_name="mind")),
                ("actions", models.IntegerField(default=2, verbose_name="actions")),
                (
                    "stress_test_succeeded_stress",
                    models.IntegerField(
                        default=0, verbose_name="stress test succeeded stress"
                    ),
                ),
                (
                    "stress_test_failed_stress",
                    models.IntegerField(
                        default=0, verbose_name="stress test failed stress"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="foe_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                ("extensions", models.ManyToManyField(to="rules.extension")),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
                (
                    "wiki_page",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worlds.wikipage",
                    ),
                ),
                (
                    "resistances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wiki_page_game_values_resistance_set",
                        to="rules.foeresistanceorweakness",
                        verbose_name="resistances",
                    ),
                ),
                (
                    "weaknesses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wiki_page_game_values_weakness_set",
                        to="rules.foeresistanceorweakness",
                        verbose_name="weaknesses",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.foetype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "foe",
                "verbose_name_plural": "foes",
            },
        ),
        migrations.CreateModel(
            name="FoeAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                ("skill", models.IntegerField(default=6, verbose_name="skill")),
                ("effect_de", models.TextField(verbose_name="effect")),
                (
                    "effect_en",
                    models.TextField(blank=True, null=True, verbose_name="effect"),
                ),
                (
                    "foe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.foe",
                        verbose_name="foe",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
            ],
            options={
                "verbose_name": "foe action",
                "verbose_name_plural": "foe actions",
            },
        ),
    ]
