# Generated by Django 5.2.4 on 2025-07-11 17:51

from django.db import migrations


def forwards_func(apps, schema_editor):
    WikiPage = apps.get_model("worlds", "WikiPage")
    WikiPageFoeType = apps.get_model("worlds", "WikiPageFoeType")
    Foe = apps.get_model("rules", "Foe")
    FoeType = apps.get_model("rules", "FoeType")

    for wiki_page_foe_type in WikiPageFoeType.objects.all():
        FoeType.objects.create(
            name_de=wiki_page_foe_type.name_de, name_en=wiki_page_foe_type.name_en
        )

    for wiki_page in WikiPage.objects.all():
        if wiki_page.wikipagegamevalues_set.exists():
            gv = wiki_page.wikipagegamevalues_set.first()
            foe = Foe.objects.create(
                name_de=wiki_page.name_de,
                name_en=wiki_page.name_en,
                slug=wiki_page.slug,
                type=FoeType.objects.get(name_de=gv.type.name_de),
                wiki_page=wiki_page,
            )
            print(wiki_page.name_de)


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0017_foeresistanceorweakness_foetype_foe_foeaction"),
    ]

    operations = [migrations.RunPython(forwards_func)]
