# Generated by Django 5.2.4 on 2025-07-11 18:28

from django.db import migrations

from rules.models import FoeAction


def to_first_linebreak(value):
    try:
        return value.splitlines()[0]
    except IndexError:
        return ""


def forwards_func(apps, schema_editor):
    WikiPage = apps.get_model("worlds", "WikiPage")
    WikiPageFoeType = apps.get_model("worlds", "WikiPageFoeType")
    Foe = apps.get_model("rules", "Foe")
    FoeType = apps.get_model("rules", "FoeType")
    FoeResistanceOrWeakness = apps.get_model("rules", "FoeResistanceOrWeakness")

    for wiki_page_foe_type in WikiPageFoeType.objects.all():
        FoeType.objects.create(
            name_de=wiki_page_foe_type.name_de, name_en=wiki_page_foe_type.name_en
        )

    for wiki_page in WikiPage.objects.all():
        if wiki_page.wikipagegamevalues_set.exists():
            gv = wiki_page.wikipagegamevalues_set.first()
            foe = Foe.objects.create(
                name_de=wiki_page.name_de,
                name_en=wiki_page.name_en,
                short_description_de=to_first_linebreak(wiki_page.text_de),
                short_description_en=to_first_linebreak(wiki_page.text_en),
                slug=wiki_page.slug,
                type=FoeType.objects.get(name_de=gv.type.name_de),
                wiki_page=wiki_page,
                health=gv.health,
                movement=gv.walking_range,
                strength=6 - gv.quickness,
                dexterity=gv.quickness,
                mind=gv.perception,
                actions=gv.actions,
                stress_test_succeeded_stress=gv.stress_test_succeeded_stress,
                stress_test_failed_stress=gv.stress_test_failed_stress,
            )
            foe.extensions.add(wiki_page.world.extension)
            foe.image.save(wiki_page.image.name, wiki_page.image)
            foe.image_copyright = wiki_page.image_copyright
            foe.image_copyright_url = wiki_page.image_copyright_url
            foe.save()

            for resistance in gv.resistances.all():
                r = FoeResistanceOrWeakness.objects.get_or_create(
                    name_de=resistance.name_de, name_en=resistance.name_en
                )
                foe.resistances.add(r[0])
            for weakness in gv.weaknesses.all():
                r = FoeResistanceOrWeakness.objects.get_or_create(
                    name_de=weakness.name_de, name_en=weakness.name_en
                )
                foe.resistances.add(r[0])
            for action in wiki_page.wikipagegameaction_set.all():
                foe.foeaction_set.create(
                    name_de=action.name_de,
                    name_en=action.name_en,
                    skill=action.skill,
                    effect_de=action.effect_de,
                    effect_en=action.effect_en,
                )
            print(wiki_page.name_de)


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0017_foeresistanceorweakness_foetype_foe_foeaction"),
    ]

    operations = [migrations.RunPython(forwards_func)]
