# Generated by Django 5.2.4 on 2025-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0019_foe_created_at_foe_created_by_foe_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foe",
            name="resistances",
            field=models.ManyToManyField(
                blank=True,
                related_name="foe_resistance_set",
                to="rules.foeresistanceorweakness",
                verbose_name="resistances",
            ),
        ),
        migrations.AlterField(
            model_name="foe",
            name="weaknesses",
            field=models.ManyToManyField(
                blank=True,
                related_name="foe_weakness_set",
                to="rules.foeresistanceorweakness",
                verbose_name="weaknesses",
            ),
        ),
    ]
