# Generated by Django 5.2.4 on 2025-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0020_alter_foe_resistances_alter_foe_weaknesses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="fixed_extensions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mandatory extensions for a world. Only applies if this object is a world",
                limit_choices_to={"type": "x"},
                to="rules.extension",
            ),
        ),
    ]
