# Generated by Django 5.2.7 on 2025-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0021_alter_extension_fixed_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="fa_icon_latex",
            field=models.CharField(
                default="", max_length=30, verbose_name="FA Icon LaTeX"
            ),
        ),
    ]
