# Generated by Django 6.0.6 on 2026-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0024_extension_image_prompt_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="essential_benefit_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential benefit"
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_benefit_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential benefit"
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_description_de",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential description",
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_description_en",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential description",
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_skills_de",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="essential skills"
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_skills_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="essential skills"
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_vulnerability_de",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="essential vulnerability",
            ),
        ),
        migrations.AddField(
            model_name="lineage",
            name="essential_vulnerability_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="essential vulnerability",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_benefit_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential benefit"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_benefit_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential benefit"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_description_de",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential description",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_description_en",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential description",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_facet_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential facet"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_facet_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="essential facet"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_skills_de",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="essential skills"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_skills_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="essential skills"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_vulnerability_de",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="essential vulnerability",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="essential_vulnerability_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="essential vulnerability",
            ),
        ),
    ]
