# Generated by Django 6.0.6 on 2026-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0025_lineage_essential_benefit_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='extension',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
        migrations.AddField(
            model_name='foe',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='foe',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
    ]
