name: Build-Main
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  Build-Main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: sbroeckling/phasesix:latest
