# Generated by Django 5.2.1 on 2025-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20240511_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default="", max_length=220, verbose_name="slug"),
            preserve_default=False,
        ),
    ]
