# Generated by Django 5.2.1 on 2025-05-15 11:18

from django.db import migrations

from worlds.unique_slugify import unique_slugify


def forwards_func(apps, schema_editor):
    Profile = apps.get_model("portal", "Profile")
    for p in Profile.objects.all():
        unique_slugify(p, p.user.username)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_profile_slug"),
    ]

    operations = [migrations.RunPython(forwards_func)]
