# Generated by Django 5.2.1 on 2025-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_auto_20250515_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_wiki_image_copyright",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="last wiki image copyright",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_wiki_image_copyright_url",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="last wiki image copyright url",
            ),
        ),
    ]
