# Generated by Django 5.2.4 on 2025-07-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_profile_last_wiki_image_copyright_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="settings_language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="EN",
                max_length=2,
                verbose_name="language preference",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="settings_protection_display",
            field=models.CharField(
                choices=[("I", "Shield icons"), ("G", "Letters")],
                default="I",
                max_length=1,
                verbose_name="protection display",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="settings_reduce_images",
            field=models.BooleanField(
                default=False,
                help_text="Reduce the amount of images displayed on the site.",
                verbose_name="reduce images",
            ),
        ),
    ]
