# Generated by Django 5.2.6 on 2025-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_profile_settings_language_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="api_key",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="api key"
            ),
        ),
    ]
