# Generated by Django 5.2.9 on 2025-12-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_profile_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="settings_protection_display",
            field=models.CharField(
                choices=[("I", "Letters"), ("G", "Shield Icons")],
                default="I",
                max_length=1,
                verbose_name="protection display",
            ),
        ),
    ]
