# Generated by Django 5.2.9 on 2025-12-23 14:32

import phasesix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_alter_profile_settings_protection_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
    ]
