# Generated by Django 5.2.9 on 2025-12-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="may_use_ai",
            field=models.BooleanField(default=False, verbose_name="may use AI"),
        ),
    ]
