# Generated by Django 2.0.2 on 2018-02-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0003_auto_20180218_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('intelligence', models.IntegerField(default=0, verbose_name='Intelligenz')),
                ('valour', models.IntegerField(default=0, verbose_name='Tapferkeit')),
                ('willpower', models.IntegerField(default=0, verbose_name='Willenskraft')),
                ('deftness', models.IntegerField(default=1, verbose_name='Geschick')),
                ('strength', models.IntegerField(default=1, verbose_name='Kraft')),
                ('attractiveness', models.IntegerField(default=1, verbose_name='Attraktivität')),
                ('endurance', models.IntegerField(default=1, verbose_name='Ausdauer')),
                ('resistance', models.IntegerField(default=1, verbose_name='Resistenz')),
                ('quickness', models.IntegerField(default=1, verbose_name='Schnelligkeit')),
                ('openness', models.IntegerField(default=1, verbose_name='Offenheit')),
                ('conscientiousness', models.IntegerField(default=1, verbose_name='Gewissenhaftigkeit')),
                ('extraversion', models.IntegerField(default=1, verbose_name='Extraversion')),
                ('agreeableness', models.IntegerField(default=1, verbose_name='Verträglichkeit')),
                ('neuroticism', models.IntegerField(default=1, verbose_name='Neurotizismus')),
                ('gifts', models.ManyToManyField(to='rules.Gift', verbose_name='Gaben')),
                ('quirks', models.ManyToManyField(to='rules.Quirk', verbose_name='Eigenarten')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Basiswert')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge')),
            ],
            options={
                'ordering': ('knowledge__name_en',),
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Basiswert')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Skill')),
            ],
            options={
                'ordering': ('skill__name_en',),
            },
        ),
    ]
