# Generated by Django 2.0.5 on 2018-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='shadows',
            field=models.ManyToManyField(to='rules.Shadow', verbose_name='Schatten'),
        ),
    ]
