# Generated by Django 4.1.10 on 2023-08-26 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ("-modified_at",)},
        ),
    ]
