# Generated by Django 5.1.2 on 2024-11-02 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0024_alter_protectiontype_icon_class"),
        ("characters", "0003_alter_character_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterRiotGearProtectionUsed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0, verbose_name="value")),
                (
                    "character_riot_gear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.characterriotgear",
                    ),
                ),
                (
                    "protection_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.protectiontype",
                    ),
                ),
            ],
            options={
                "ordering": ("character_riot_gear__id",),
            },
        ),
    ]
