# Generated by Django 5.1.7 on 2025-03-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_characterlanguage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ("-created_at",)},
        ),
    ]
