# Generated by Django 5.1.7 on 2025-03-18 20:50

from django.db import migrations


def forwards_func(apps, schema_editor):
    Pronoun = apps.get_model("characters", "Pronoun")
    Pronoun.objects.create(
        nominative_de="sie",
        nominative_en="she",
        dative_de="ihr",
        dative_en="her",
        possessive_de="ihr",
        possessive_en="hers",
        copula_verb_de="ist",
        copula_verb_en="is",
    )
    Pronoun.objects.create(
        nominative_de="er",
        nominative_en="he",
        dative_de="ihm",
        dative_en="him",
        possessive_de="sein",
        possessive_en="his",
        copula_verb_de="ist",
        copula_verb_en="is",
    )
    Pronoun.objects.create(
        nominative_de="dey",
        nominative_en="they",
        dative_de="denen",
        dative_en="them",
        possessive_de="deren",
        possessive_en="theirs",
        copula_verb_de="ist",
        copula_verb_en="are",
    )
    Pronoun.objects.create(
        nominative_de="em",
        nominative_en="em",
        dative_de="em",
        dative_en="em",
        possessive_de="em",
        possessive_en="em",
        copula_verb_de="ist",
        copula_verb_en="are",
    )
    Pronoun.objects.create(
        nominative_de="hen",
        nominative_en="hen",
        dative_de="hen",
        dative_en="hen",
        possessive_de="hens",
        possessive_en="hens",
        copula_verb_de="ist",
        copula_verb_en="are",
    )
    Pronoun.objects.create(
        nominative_de="nin",
        nominative_en="nin",
        dative_de="nim",
        dative_en="nim",
        possessive_de="nims",
        possessive_en="nims",
        copula_verb_de="ist",
        copula_verb_en="are",
    )
    Pronoun.objects.create(
        nominative_de="per",
        nominative_en="per",
        dative_de="per",
        dative_en="per",
        possessive_de="pers",
        possessive_en="pers",
        copula_verb_de="ist",
        copula_verb_en="are",
    )
    Pronoun.objects.create(
        nominative_de="xier",
        nominative_en="xier",
        dative_de="xiem",
        dative_en="xiem",
        possessive_de="xies",
        possessive_en="xies",
        copula_verb_de="ist",
        copula_verb_en="are",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0008_pronoun_character_pronoun"),
    ]

    operations = [migrations.RunPython(forwards_func)]
