# Generated by Django 5.1.7 on 2025-03-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0009_auto_20250318_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pronoun",
            name="copula_verb_de",
            field=models.CharField(max_length=12, verbose_name="copula verb"),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="copula_verb_en",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="copula verb"
            ),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="dative_de",
            field=models.CharField(max_length=12, verbose_name="dative"),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="dative_en",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="dative"
            ),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="nominative_de",
            field=models.CharField(max_length=12, verbose_name="nominative"),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="nominative_en",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="nominative"
            ),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="possessive_de",
            field=models.CharField(max_length=12, verbose_name="possessive"),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="possessive_en",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="possessive"
            ),
        ),
    ]
