# Generated by Django 5.1.7 on 2025-03-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0010_alter_pronoun_copula_verb_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="pronoun",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.pronoun",
                verbose_name="pronoun",
            ),
            preserve_default=False,
        ),
    ]
