# Generated by Django 5.1.7 on 2025-03-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0012_character_is_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ("-is_favorite", "-created_at")},
        ),
    ]
