# Generated by Django 3.2.7 on 2021-10-31 08:56

from django.db import migrations


def create_and_assign_magical_skills(apps, schema_editor):
    Skill = apps.get_model('rules', 'Skill')
    Character = apps.get_model('characters', 'Character')
    Extension = apps.get_model('rules', 'Extension')

    magic_extension = Extension.objects.get(identifier='magic')

    spell_casting = Skill.objects.create(
        name_de="Zaubern",
        name_en="Spell casting",
        kind="p",
        dominant_attribute="willpower",
        supplemental_attribute="charm"
    )
    spell_casting.extensions.add(magic_extension)

    magic_knowledge = Skill.objects.create(
        name_de="Magiekunde",
        name_en="Magic Knowledge",
        kind="m",
        dominant_attribute="education",
        supplemental_attribute="conscientiousness"
    )
    magic_knowledge.extensions.add(magic_extension)

    for c in Character.objects.all():
        c.characterskill_set.create(skill=spell_casting)
        c.characterskill_set.create(skill=magic_knowledge)


class Migration(migrations.Migration):
    dependencies = [
        ('characters', '0045_remove_characterskill_base_value'),
    ]

    operations = [
        migrations.RunPython(create_and_assign_magical_skills)
    ]
