# Generated by Django 3.2.7 on 2021-10-31 09:08

from django.db import migrations


def rewrite_template_modifiers_for_spell_casting(apps, schema_editor):
    TemplateModifier = apps.get_model('rules', 'TemplateModifier')
    Skill = apps.get_model('rules', 'Skill')

    for tm in TemplateModifier.objects.all():
        if tm.knowledge is not None and tm.knowledge.name_en == 'Magic Knowledge':
            if tm.skill is None:
                tm.skill = Skill.objects.get(name_en='Magic Knowledge')
                tm.skill_modifier = tm.knowledge_modifier
            else:
                TemplateModifier.objects.create(
                    template=tm.template,
                    skill=Skill.objects.get(name_en='Magic Knowledge'),
                    skill_modifier=tm.knowledge_modifier)
            tm.knowledge = None
            tm.knowledge_modifier = None
            tm.save()


class Migration(migrations.Migration):
    dependencies = [
        ('characters', '0046_auto_20211031_0856'),
    ]

    operations = [
        migrations.RunPython(rewrite_template_modifiers_for_spell_casting)
    ]
