# Generated by Django 3.2.7 on 2021-11-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0036_currencymap_currencymapunit'),
        ('characters', '0047_auto_20211031_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('currency_map_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.currencymapunit')),
            ],
        ),
    ]
