# Generated by Django 3.2.9 on 2022-01-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0068_alter_attribute_options'),
        ('characters', '0048_charactercurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.attribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'ordering': ('attribute__name_de',),
            },
        ),
    ]
