# Generated by Django 3.2.9 on 2022-01-03 12:17

from django.db import migrations


def assign_attributes(apps, schema_editor):
    Character = apps.get_model('characters', 'Character')
    Attribute = apps.get_model('rules', 'Attribute')
    for c in Character.objects.all():
        for a in Attribute.objects.all():
            c.characterattribute_set.create(attribute=a)


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0049_characterattribute'),
    ]

    operations = [
        migrations.RunPython(assign_attributes)
    ]
