# Generated by Django 3.2.12 on 2022-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0050_auto_20220103_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteritem',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='characteritem',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering'),
        ),
    ]
