# Generated by Django 3.2.12 on 2022-04-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0051_auto_20220420_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('subject', models.CharField(blank=True, max_length=80, null=True, verbose_name='subject')),
                ('text', models.TextField(verbose_name='text')),
                ('ordering', models.IntegerField(default=1, verbose_name='ordering')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'ordering': ('ordering', 'created_at'),
            },
        ),
    ]
