# Generated by Django 3.2.12 on 2022-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0052_characternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='characternote',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is private'),
        ),
    ]
