# Generated by Django 3.2.12 on 2022-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0053_characternote_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='latest_initiative',
            field=models.IntegerField(default=0, verbose_name='latest initiative'),
        ),
    ]
