# Generated by Django 3.2.12 on 2022-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0054_character_latest_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quirks_gained',
            field=models.IntegerField(default=0, verbose_name='quirks gained'),
        ),
    ]
