# Generated by Django 3.2.12 on 2022-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0055_character_quirks_gained'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quirks_healed',
            field=models.IntegerField(default=0, help_text='The amount of quirks healed by treatment.', verbose_name='quirks healed'),
        ),
        migrations.AlterField(
            model_name='character',
            name='quirks_gained',
            field=models.IntegerField(default=0, help_text='The amount of quirks gained by excess stress', verbose_name='quirks gained'),
        ),
    ]
