# Generated by Django 3.2.12 on 2022-08-02 15:06

from django.db import migrations


def assign_quirks_needed(apps, schema_editor):
    Character = apps.get_model('characters', 'Character')
    for c in Character.objects.all():
        c.quirks_gained = c.quirks.count()
        c.save()
    for c in Character.objects.all():
        c.quirks.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('characters', '0056_auto_20220731_1751'),
    ]

    operations = [
        migrations.RunPython(assign_quirks_needed)
    ]
