# Generated by Django 3.2.15 on 2022-10-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_roll_description'),
        ('characters', '0057_auto_20220802_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='npc_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_cmpaign_set', to='campaigns.campaign', verbose_name='Campaign'),
        ),
    ]
