# Generated by Django 3.2.15 on 2022-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0059_alter_character_npc_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='charges_used',
            field=models.IntegerField(default=0, verbose_name='Charges used'),
        ),
    ]
