# Generated by Django 3.2.15 on 2022-10-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0060_characteritem_charges_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='in_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characteritem'),
        ),
    ]
