# Generated by Django 3.2.15 on 2022-10-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaign_world'),
        ('characters', '0061_characteritem_in_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='npc_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_set', to='campaigns.campaign', verbose_name='NPC Campaign'),
        ),
    ]
