# Generated by Django 3.2.15 on 2022-10-16 18:25

from django.db import migrations


def add_lineage_template(apps, schema_editor):
    Character = apps.get_model('characters', 'Character')
    for c in Character.objects.all():
        if c.lineage.template is not None:
            if not c.charactertemplate_set.filter(template=c.lineage.template).exists():
                c.charactertemplate_set.create(template=c.lineage.template)


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0062_alter_character_npc_campaign'),
    ]

    operations = [
        migrations.RunPython(add_lineage_template),
    ]
