# Generated by Django 4.1.3 on 2022-12-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0054_item_is_container'),
        ('characters', '0063_auto_20221016_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='currency_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armory.currencymap', verbose_name='currency map'),
            preserve_default=False,
        ),
    ]
