# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0064_character_currency_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backdrop_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='character_backdrop_images', verbose_name='backdrop image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='character_images', verbose_name='image'),
        ),
    ]
