# Generated by Django 4.1.6 on 2023-02-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantheon', '0002_auto_20230213_1915'),
        ('characters', '0065_alter_character_backdrop_image_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='attitude'),
        ),
        migrations.AddField(
            model_name='character',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='character',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantheon.entity', verbose_name='entity'),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='weight'),
        ),
    ]
