# Generated by Django 4.1.7 on 2023-03-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0066_character_attitude_character_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='may_appear_on_start_page',
            field=models.BooleanField(default=False, help_text='This character may appear on the anonymous start page (i.E. if it has only free images', verbose_name='may appear on start page'),
        ),
    ]
