# Generated by Django 4.1.7 on 2023-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0068_character_created_at_character_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="favor",
            field=models.IntegerField(default=0, verbose_name="favor"),
        ),
    ]
