# Generated by Django 4.1.7 on 2023-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0069_character_favor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="attitude",
            field=models.IntegerField(default=50, verbose_name="attitude"),
        ),
    ]
