# Generated by Django 4.1.7 on 2023-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0070_alter_character_attitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="favor",
        ),
        migrations.AddField(
            model_name="character",
            name="grace",
            field=models.IntegerField(default=0, verbose_name="grace"),
        ),
    ]
