# Generated by Django 5.1.7 on 2025-04-01 04:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymodification",
            name="rules_de",
            field=models.TextField(blank=True, null=True, verbose_name="rules"),
        ),
        migrations.AddField(
            model_name="bodymodification",
            name="rules_en",
            field=models.TextField(blank=True, null=True, verbose_name="rules"),
        ),
    ]
