# Generated by Django 5.1.7 on 2025-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "body_modifications",
            "0002_bodymodification_rules_de_bodymodification_rules_en",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymodification",
            name="name_de",
            field=models.CharField(max_length=80, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="bodymodification",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="name"
            ),
        ),
    ]
