# Generated by Django 5.1.7 on 2025-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0004_auto_20250401_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymodification",
            name="activation",
            field=models.CharField(
                choices=[("a", "active"), ("p", "passive")],
                default="p",
                max_length=1,
                verbose_name="activation",
            ),
        ),
    ]
