# Generated by Django 5.1.7 on 2025-04-14 10:27

from django.db import migrations


def forward(apps, schema_editor):
    Extension = apps.get_model("rules", "Extension")
    BodyModification = apps.get_model("body_modifications", "BodyModification")

    for bm in BodyModification.objects.all():
        for e in Extension.objects.filter(type="e"):
            bm.extensions.add(e)


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0005_bodymodification_activation"),
    ]

    operations = [migrations.RunPython(forward)]
