# Generated by Django 5.1.7 on 2025-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0006_auto_20250414_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="socketlocation",
            name="gi_icon_class",
            field=models.CharField(blank=True, null=True, verbose_name="gi icon class"),
        ),
    ]
