# Generated by Django 5.1.7 on 2025-04-14 11:01

from django.db import migrations


def forwards_func(apps, schema_editor):
    SocketLocation = apps.get_model("body_modifications", "SocketLocation")
    SocketLocation.objects.filter(name_en="Head").update(
        gi_icon_class="gi gi-delapouite-vr-headset"
    )
    SocketLocation.objects.filter(name_en="Torso").update(
        gi_icon_class="gi gi-delapouite-muscular-torso"
    )
    SocketLocation.objects.filter(name_en="Left Arm").update(
        gi_icon_class="gi gi-delapouite-forearm"
    )
    SocketLocation.objects.filter(name_en="Right Arm").update(
        gi_icon_class="gi gi-delapouite-forearm mirrored"
    )
    SocketLocation.objects.filter(name_en="Left Leg").update(
        gi_icon_class="gi gi-delapouite-leg mirrored"
    )
    SocketLocation.objects.filter(name_en="Right Leg").update(
        gi_icon_class="gi gi-delapouite-leg"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0007_socketlocation_gi_icon_class"),
    ]

    operations = [migrations.RunPython(forwards_func)]
