# Generated by Django 5.1.7 on 2025-04-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0010_auto_20250414_1154"),
        ("magic", "0010_alter_basespell_duration_unit"),
        ("rules", "0014_template_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyModificationModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base_max_health", "max health"),
                            ("base_max_arcana", "max arcana"),
                            ("base_spell_points", "spell points"),
                            ("base_actions", "actions"),
                            ("base_minimum_roll", "minimum roll"),
                            ("base_rest_minimum_roll", "rest minimum roll"),
                            ("base_protection", "protection"),
                            ("base_evasion", "evasion"),
                            ("base_bonus_dice", "bonus dice"),
                            ("base_destiny_dice", "destiny dice"),
                            ("base_rerolls", "rerolls"),
                            ("base_max_stress", "max stress"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="aspect",
                    ),
                ),
                (
                    "aspect_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="aspect modifier"
                    ),
                ),
                (
                    "attribute_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="attribute modifier"
                    ),
                ),
                (
                    "skill_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="skill modifier"
                    ),
                ),
                (
                    "knowledge_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="knowledge modifier"
                    ),
                ),
                (
                    "allows_priest_actions",
                    models.BooleanField(
                        default=False, verbose_name="allows priest actions"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.attribute",
                        verbose_name="attribute",
                    ),
                ),
                (
                    "body_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_modifications.bodymodification",
                        verbose_name="body modification",
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.knowledge",
                        verbose_name="knowledge",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.skill",
                        verbose_name="skill",
                    ),
                ),
                (
                    "unlocks_spell_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="magic.spellorigin",
                        verbose_name="unlocks spell origin",
                    ),
                ),
            ],
            options={
                "verbose_name": "body modification modifier",
                "verbose_name_plural": "body modification modifiers",
                "ordering": ("id",),
            },
        ),
    ]
