# Generated by Django 5.2.4 on 2025-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0012_alter_bodymodificationmodifier_aspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymodificationmodifier",
            name="aspect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base_languages", "languages"),
                    ("base_contacts", "contacts"),
                    ("base_max_health", "max health"),
                    ("base_max_arcana", "max arcana"),
                    ("base_spell_points", "spell points"),
                    ("base_actions", "actions"),
                    ("base_minimum_roll", "minimum roll"),
                    ("base_rest_minimum_roll", "rest minimum roll"),
                    ("base_protection", "protection"),
                    ("base_evasion", "evasion"),
                    ("base_bonus_dice", "bonus dice"),
                    ("base_destiny_dice", "destiny dice"),
                    ("base_rerolls", "rerolls"),
                    ("base_base_stress", "base stress"),
                    ("base_max_stress", "max stress"),
                ],
                max_length=40,
                null=True,
                verbose_name="aspect",
            ),
        ),
    ]
