# Generated by Django 5.2.7 on 2025-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0013_alter_bodymodificationmodifier_aspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymodification",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
    ]
