# Generated by Django 5.2.9 on 2025-12-21 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0021_campaign_plot"),
        ("partypad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="padobject",
            old_name="src",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="padobject",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="partypad/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="party_pads",
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="pad",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="party_pads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pad_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="height",
            field=models.IntegerField(verbose_name="Height"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="loop",
            field=models.BooleanField(default=False, verbose_name="Loop"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("token", "Token"),
                ],
                max_length=16,
                verbose_name="Object type",
            ),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="pad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pad_objects",
                to="partypad.pad",
                verbose_name="Pad",
            ),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="playing",
            field=models.BooleanField(default=False, verbose_name="Playing"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="rotation",
            field=models.IntegerField(default=0, verbose_name="Rotation"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="width",
            field=models.IntegerField(verbose_name="Width"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="x",
            field=models.IntegerField(verbose_name="X position"),
        ),
        migrations.AlterField(
            model_name="padobject",
            name="y",
            field=models.IntegerField(verbose_name="Y position"),
        ),
    ]
