# Generated by Django 3.2.9 on 2022-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20210726_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='foe',
            name='protection',
            field=models.IntegerField(default=0, verbose_name='protection'),
        ),
    ]
