# Generated by Django 3.2.9 on 2022-01-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0008_foe_protection'),
    ]

    operations = [
        migrations.RenameField('foe', 'movement', 'quickness')
    ]
