# Generated by Django 3.2.9 on 2022-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0009_auto_20220120_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='foe',
            name='arcana',
            field=models.IntegerField(default=0, verbose_name='arcana'),
        ),
        migrations.AlterField(
            model_name='foe',
            name='quickness',
            field=models.IntegerField(default=1, verbose_name='quickness'),
        ),
    ]
