# Generated by Django 4.1.3 on 2022-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0010_auto_20220120_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foe',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='foe_images', verbose_name='image'),
        ),
    ]
