# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0011_alter_foe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foe',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='foe_images', verbose_name='image'),
        ),
    ]
