# Generated by Django 4.1.7 on 2023-05-01 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bestiary", "0012_alter_foe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foeaction",
            name="foe",
        ),
        migrations.DeleteModel(
            name="Foe",
        ),
        migrations.DeleteModel(
            name="FoeAction",
        ),
        migrations.DeleteModel(
            name="FoeResistanceOrWeakness",
        ),
        migrations.DeleteModel(
            name="FoeType",
        ),
    ]
