# Generated by Django 4.1.3 on 2022-11-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0087_lineage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'wiki category',
                'verbose_name_plural': 'wiki categories',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='extension_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('extension', models.ForeignKey(blank=True, help_text='The corresponding world extension, which is added to the characters.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.extension', verbose_name='extension')),
            ],
            options={
                'verbose_name': 'world',
                'verbose_name_plural': 'worlds',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('category', models.ForeignKey(help_text='The category of the wiki page.', on_delete=django.db.models.deletion.CASCADE, to='worlds.wikicategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'wiki page',
                'verbose_name_plural': 'wiki pages',
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='world',
            field=models.ForeignKey(help_text='The world this category belongs to.', on_delete=django.db.models.deletion.CASCADE, to='worlds.world', verbose_name='world'),
        ),
    ]
