# Generated by Django 4.1.3 on 2022-11-26 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0087_lineage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='extension_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('extension', models.ForeignKey(blank=True, help_text='The corresponding world extension, which is added to the characters.', limit_choices_to={'type': 'w'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.extension', verbose_name='extension')),
            ],
            options={
                'verbose_name': 'world',
                'verbose_name_plural': 'worlds',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('abstract_de', models.TextField(blank=True, null=True, verbose_name='abstract')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='abstract')),
                ('text_de', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foe_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent wiki page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.wikipage', verbose_name='parent')),
                ('world', models.ForeignKey(help_text='The world this category belongs to.', on_delete=django.db.models.deletion.CASCADE, to='worlds.world', verbose_name='world')),
            ],
            options={
                'verbose_name': 'wiki category',
                'verbose_name_plural': 'wiki categories',
                'ordering': ('ordering',),
            },
        ),
    ]
