# Generated by Django 4.1.3 on 2022-11-26 18:22

from django.db import migrations


def add_worlds(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    World.objects.bulk_create([
        World(name_de='Terra', name_en="Terra", is_active=True, ordering=1),
        World(name_de='Froeleikrfold', name_en="Froeleikrfold", is_active=True, ordering=1),
        World(name_de='Tirakans Reiche', name_en="Realms of Tirakan", is_active=True, ordering=1),
        World(name_de='NEXUS', name_en="NEXUS", is_active=True, ordering=1),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_worlds),
    ]
