# Generated by Django 4.1.3 on 2022-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_auto_20221126_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='abstract_de',
            field=models.TextField(blank=True, help_text='A short summary of the wiki page. This may also contain Wiki links.', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='A short summary of the wiki page. This may also contain Wiki links.', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='text_de',
            field=models.TextField(blank=True, help_text='The wiki page text. This may contain Wiki links.', null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='text_en',
            field=models.TextField(blank=True, help_text='The wiki page text. This may contain Wiki links.', null=True, verbose_name='text'),
        ),
    ]
