# Generated by Django 4.1.3 on 2022-11-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_alter_wikipage_abstract_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(default='', max_length=220, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='abstract_de',
            field=models.TextField(blank=True, help_text='A short summary of the wiki page. This may contain Wiki links.', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='A short summary of the wiki page. This may contain Wiki links.', null=True, verbose_name='abstract'),
        ),
    ]
