# Generated by Django 4.1.3 on 2022-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_wikipage_slug_alter_wikipage_abstract_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ('ordering',), 'verbose_name': 'wiki page', 'verbose_name_plural': 'wiki pages'},
        ),
    ]
