# Generated by Django 4.1.10 on 2023-08-27 16:56

from django.db import migrations


def forward(apps, schema_editor):
    WorldSiteConfiguration = apps.get_model("worlds", "WorldSiteConfiguration")
    for wsc in WorldSiteConfiguration.objects.all():
        wsc.world.brand_name_de = wsc.brand_name_de
        wsc.world.brand_name_en = wsc.brand_name_en
        wsc.world.brand_logo = wsc.brand_logo
        wsc.world.template_addon = wsc.template_addon
        wsc.world.save()


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0004_rename_brand_name_world_brand_name_de_and_more"),
    ]

    operations = [migrations.RunPython(forward)]
