# Generated by Django 4.1.3 on 2022-11-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0005_alter_wikipage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki_page_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='world',
            field=models.ForeignKey(help_text='The world this page belongs to.', on_delete=django.db.models.deletion.CASCADE, to='worlds.world', verbose_name='world'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='world_images', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='WikiPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wiki_page_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('caption', models.CharField(blank=True, max_length=120, null=True, verbose_name='caption')),
                ('wiki_page', models.ForeignKey(help_text='The wiki page the image belongs to.', on_delete=django.db.models.deletion.CASCADE, to='worlds.wikipage', verbose_name='wiki page')),
            ],
            options={
                'verbose_name': 'wiki page image',
                'verbose_name_plural': 'wiki page images',
            },
        ),
    ]
