# Generated by Django 4.1.3 on 2022-11-28 12:54

from django.db import migrations, models

from worlds.unique_slugify import unique_slugify


def forwards_func(apps, schema_editor):
    World = apps.get_model('worlds', 'World')
    for world in World.objects.all():
        if not world.slug:
            unique_slugify(world, str(world.name_de))
            world.save()


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_alter_wikipage_image_alter_wikipage_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='slug',
            field=models.SlugField(max_length=220, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.RunPython(forwards_func),
    ]
