# Generated by Django 4.1.3 on 2022-11-29 13:26

from django.db import migrations, models

from worlds.unique_slugify import unique_slugify


def forwards_func(apps, schema_editor):
    WikiPageImage = apps.get_model('worlds', 'WikiPageImage')
    for world in WikiPageImage.objects.all():
        if not world.slug:
            unique_slugify(world, str(world.name_de))
            world.save()


class Migration(migrations.Migration):
    dependencies = [
        ('worlds', '0007_alter_wikipage_managers_world_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipageimage',
            name='slug',
            field=models.SlugField(max_length=220, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='wikipageimage',
            name='caption',
            field=models.CharField(default='', max_length=120, verbose_name='caption'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func),
    ]
