# Generated by Django 4.1.10 on 2023-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0008_auto_20230827_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="template_addon",
            field=models.CharField(max_length=40, verbose_name="Template Addon"),
        ),
    ]
