# Generated by Django 4.1.11 on 2023-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0009_alter_world_template_addon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="world",
            name="template_addon",
        ),
        migrations.AddField(
            model_name="world",
            name="index_template",
            field=models.CharField(
                choices=[
                    ("index.html", "index.html"),
                    ("worlds/world_detail.html", "worlds/world_detail.html"),
                ],
                default="index.html",
                max_length=40,
                verbose_name="Index Template",
            ),
        ),
    ]
