# Generated by Django 4.1.3 on 2022-12-01 17:46

from django.db import migrations


def forwards_func(apps, schema_editor):
    WikiPage = apps.get_model("worlds", "WikiPage")
    for wikipage in WikiPage.objects.all():
        if not wikipage.text_de:
            wikipage.text_de = wikipage.abstract_de
        if not wikipage.text_en:
            wikipage.text_en = wikipage.abstract_en
        wikipage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0009_wikipageimage_created_at_wikipageimage_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
