# Generated by Django 4.1.3 on 2022-12-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0010_auto_20221201_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='abstract_de',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='abstract_en',
        ),
    ]
