# Generated by Django 4.1.3 on 2022-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0011_remove_wikipage_abstract_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='wiki_page_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='wikipageimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='wiki_page_images', verbose_name='image'),
        ),
    ]
