# Generated by Django 4.1.11 on 2023-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0011_world_scss_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="brand_claim",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Brand claim"
            ),
        ),
    ]
