# Generated by Django 4.1.11 on 2023-09-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0012_world_brand_claim"),
    ]

    operations = [
        migrations.RenameField(
            model_name="world",
            old_name="brand_claim",
            new_name="brand_claim_de",
        ),
        migrations.AddField(
            model_name="world",
            name="brand_claim_en",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Brand claim"
            ),
        ),
    ]
