# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_alter_wikipage_image_alter_wikipageimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='wiki_page_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='wikipageimage',
            name='image',
            field=models.ImageField(max_length=256, upload_to='wiki_page_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='world_images', verbose_name='image'),
        ),
    ]
