# Generated by Django 4.1.3 on 2022-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_alter_wikipage_image_alter_wikipageimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='short_name_de',
            field=models.CharField(blank=True, help_text='An optional short name for the default link text.', max_length=90, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='short_name_en',
            field=models.CharField(blank=True, help_text='An optional short name for the default link text.', max_length=90, null=True, verbose_name='short name'),
        ),
    ]
