# Generated by Django 4.1.3 on 2022-12-24 11:59

from django.db import migrations


def forwards(apps, schema_editor):
    WikiPage = apps.get_model('worlds', 'WikiPage')
    for page in WikiPage.objects.all():
        page.short_name_de = page.name_de
        page.short_name_en = page.name_en
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ('worlds', '0014_wikipage_short_name_de_wikipage_short_name_en'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
