# Generated by Django 4.1.6 on 2023-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_auto_20221224_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='info_name_cm_de',
            field=models.CharField(default='cm', max_length=20, verbose_name='Name for centimeter'),
        ),
        migrations.AddField(
            model_name='world',
            name='info_name_cm_en',
            field=models.CharField(blank=True, default='cm', max_length=20, verbose_name='Name for centimeter'),
        ),
        migrations.AddField(
            model_name='world',
            name='info_name_kg_de',
            field=models.CharField(default='kg', max_length=20, verbose_name='Name for kilogram'),
        ),
        migrations.AddField(
            model_name='world',
            name='info_name_kg_en',
            field=models.CharField(blank=True, default='kg', max_length=20, verbose_name='Name for kilogram'),
        ),
    ]
