# Generated by Django 4.1.7 on 2023-04-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0016_world_info_name_cm_de_world_info_name_cm_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldSiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_domain_name', models.CharField(blank=True, help_text='This world is set as default if the given dns domain name is requested', max_length=120, null=True, verbose_name='dns domain name')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
    ]
