# Generated by Django 4.1.7 on 2023-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0017_worldsiteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='brand_name',
            field=models.CharField(default='PhaseSix', max_length=80, verbose_name='Brand name'),
            preserve_default=False,
        ),
    ]
