# Generated by Django 4.1.7 on 2023-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0018_worldsiteconfiguration_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='template_suffix',
            field=models.CharField(default='', max_length=40, verbose_name='Template Suffix'),
        ),
    ]
