# Generated by Django 4.1.7 on 2023-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0019_worldsiteconfiguration_template_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldsiteconfiguration',
            name='template_suffix',
            field=models.CharField(max_length=40, verbose_name='Template Suffix'),
        ),
    ]
