# Generated by Django 4.1.7 on 2023-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0020_alter_worldsiteconfiguration_template_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldsiteconfiguration',
            old_name='template_suffix',
            new_name='template_addon',
        ),
    ]
