# Generated by Django 4.1.7 on 2023-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0021_rename_template_suffix_worldsiteconfiguration_template_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='session_cookie_domain',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='session cookie domain'),
        ),
    ]
