# Generated by Django 5.1.5 on 2025-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0008_skill_is_magical"),
        ("worlds", "0022_alter_wikipagegameaction_wiki_page_wikipageembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "country_name_de",
                    models.CharField(max_length=100, verbose_name="country name"),
                ),
                (
                    "country_name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="country name",
                    ),
                ),
                (
                    "amount_of_people_speaking",
                    models.IntegerField(verbose_name="amount of people speaking"),
                ),
                (
                    "extensions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="languages",
                        to="rules.extension",
                        verbose_name="extensions",
                    ),
                ),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ("amount_of_people_speaking",),
            },
        ),
    ]
