# Generated by Django 4.1.7 on 2023-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0022_worldsiteconfiguration_session_cookie_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='world',
            name='description_en',
        ),
        migrations.AddField(
            model_name='world',
            name='description_1_de',
            field=models.TextField(blank=True, null=True, verbose_name='description 1'),
        ),
        migrations.AddField(
            model_name='world',
            name='description_1_en',
            field=models.TextField(blank=True, null=True, verbose_name='description 1'),
        ),
        migrations.AddField(
            model_name='world',
            name='description_2_de',
            field=models.TextField(blank=True, null=True, verbose_name='description 2'),
        ),
        migrations.AddField(
            model_name='world',
            name='description_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='description 2'),
        ),
        migrations.AddField(
            model_name='world',
            name='description_3_de',
            field=models.TextField(blank=True, null=True, verbose_name='description 3'),
        ),
        migrations.AddField(
            model_name='world',
            name='description_3_en',
            field=models.TextField(blank=True, null=True, verbose_name='description 3'),
        ),
    ]
