# Generated by Django 4.1.7 on 2023-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0023_remove_world_description_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldsiteconfiguration',
            options={'verbose_name': 'world site configuration', 'verbose_name_plural': 'world site configurations'},
        ),
        migrations.RenameField(
            model_name='worldsiteconfiguration',
            old_name='brand_name',
            new_name='brand_name_de',
        ),
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='brand_name_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Brand name'),
        ),
    ]
