# Generated by Django 4.1.7 on 2023-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_alter_worldsiteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='worldsiteconfiguration',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
