# Generated by Django 4.1.7 on 2023-04-27 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worlds", "0025_worldsiteconfiguration_description_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPageFoeResistanceOrWeakness",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "wiki page foe resistance or weakness",
                "verbose_name_plural": "wiki page foe resistances or weaknesses",
            },
        ),
        migrations.CreateModel(
            name="WikiPageFoeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "wiki page foe type",
                "verbose_name_plural": "wiki page foe types",
            },
        ),
        migrations.CreateModel(
            name="WikiPageGameValues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("health", models.IntegerField(default=6, verbose_name="health")),
                ("arcana", models.IntegerField(default=0, verbose_name="arcana")),
                (
                    "protection",
                    models.IntegerField(default=0, verbose_name="protection"),
                ),
                ("actions", models.IntegerField(default=2, verbose_name="actions")),
                ("quickness", models.IntegerField(default=1, verbose_name="quickness")),
                (
                    "minimum_roll",
                    models.IntegerField(default=5, verbose_name="minimum roll"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "resistances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wiki_page_game_values_resistance_set",
                        to="worlds.wikipagefoeresistanceorweakness",
                        verbose_name="resistances",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worlds.wikipagefoetype",
                        verbose_name="type",
                    ),
                ),
                (
                    "weaknesses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wiki_page_game_values_weakness_set",
                        to="worlds.wikipagefoeresistanceorweakness",
                        verbose_name="weaknesses",
                    ),
                ),
                (
                    "wiki_page",
                    models.ForeignKey(
                        help_text="The wiki page the values belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worlds.wikipage",
                        verbose_name="wiki page",
                    ),
                ),
            ],
            options={
                "verbose_name": "wiki page game values",
                "verbose_name_plural": "wiki page game values",
            },
        ),
        migrations.CreateModel(
            name="WikiPageGameAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                ("skill", models.IntegerField(default=6, verbose_name="skill")),
                ("effect_de", models.TextField(verbose_name="effect")),
                (
                    "effect_en",
                    models.TextField(blank=True, null=True, verbose_name="effect"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "wiki_page",
                    models.ForeignKey(
                        help_text="The wiki page the values belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worlds.wikipage",
                        verbose_name="wiki page",
                    ),
                ),
            ],
            options={
                "verbose_name": "wiki page game action",
                "verbose_name_plural": "wiki page game actions",
            },
        ),
    ]
