# Generated by Django 4.1.7 on 2023-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0026_wikipagefoeresistanceorweakness_wikipagefoetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="actions_heading_de",
            field=models.CharField(
                default="Aktionen", max_length=40, verbose_name="actions heading"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wikipage",
            name="actions_heading_en",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="actions heading"
            ),
        ),
    ]
