# Generated by Django 5.1.7 on 2025-03-22 21:36
import json

from django.db import migrations


def forward(apps, schema_editor):
    Extension = apps.get_model("rules", "Extension")
    Language = apps.get_model("worlds", "Language")
    LanguageGroup = apps.get_model("worlds", "LanguageGroup")

    modern = Extension.objects.get(identifier="modern")
    cold_war = Extension.objects.get(identifier="cw")
    imp = Extension.objects.get(identifier="imp")
    victorian = Extension.objects.get(identifier="victorian")
    medieval = Extension.objects.get(identifier="middleages")

    lg = LanguageGroup.objects.create(
        name_de="Klassische Sprachen",
        name_en="Classical Languages",
    )
    for language in get_classic_languages():
        if not modern.languages.filter(name_de=language["name_de"]).exists():
            l = Language.objects.create(
                name_de=language["name_de"],
                name_en=language["name_en"],
                country_name_de=language["country_name_de"],
                country_name_en=language["country_name_en"],
                group=lg,
                amount_of_people_speaking=0,
            )
            l.extensions.add(modern)
            l.extensions.add(cold_war)
            l.extensions.add(imp)
            l.extensions.add(victorian)
            l.extensions.add(medieval)


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0027_language_homebrew_campaign_and_more"),
    ]

    operations = [migrations.RunPython(forward)]


def get_classic_languages():
    return json.loads(
        """
    [
  {
    "name_en": "Latin",
    "name_de": "Latein",
    "country_name_en": "Roman Republic",
    "country_name_de": "Römische Republik",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Ancient Greek",
    "name_de": "Altgriechisch",
    "country_name_en": "Hellenistic Greece",
    "country_name_de": "Hellenistisches Griechenland",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Classical Chinese",
    "name_de": "Klassisches Chinesisch",
    "country_name_en": "Qin Dynasty",
    "country_name_de": "Qin-Dynastie",
    "amount_of_people_speaking": 20000000
  },
  {
    "name_en": "Sanskrit",
    "name_de": "Sanskrit",
    "country_name_en": "Maurya Empire",
    "country_name_de": "Maurya-Reich",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Old Persian",
    "name_de": "Altpersisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Aramaic",
    "name_de": "Aramäisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 2500000
  },
  {
    "name_en": "Egyptian (Demotic)",
    "name_de": "Ägyptisch (Demotisch)",
    "country_name_en": "Ptolemaic Egypt",
    "country_name_de": "Ptolemäisches Ägypten",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Hebrew",
    "name_de": "Hebräisch",
    "country_name_en": "Hasmonean Kingdom",
    "country_name_de": "Hasmonäisches Königreich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Gaulish",
    "name_de": "Gallisch",
    "country_name_en": "Gaul",
    "country_name_de": "Gallien",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Celtic (Various Dialects)",
    "name_de": "Keltisch (Verschiedene Dialekte)",
    "country_name_en": "Various Celtic Tribes",
    "country_name_de": "Verschiedene keltische Stämme",
    "amount_of_people_speaking": 7000000
  },
  {
    "name_en": "Punic",
    "name_de": "Punisch",
    "country_name_en": "Carthaginian Empire",
    "country_name_de": "Karthagisches Reich",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Phoenician",
    "name_de": "Phönizisch",
    "country_name_en": "Phoenician City-States",
    "country_name_de": "Phönizische Stadtstaaten",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Illyrian",
    "name_de": "Illyrisch",
    "country_name_en": "Kingdom of Illyria",
    "country_name_de": "Königreich Illyrien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Thracian",
    "name_de": "Thrakisch",
    "country_name_en": "Thrace",
    "country_name_de": "Thrakien",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Lydian",
    "name_de": "Lydisch",
    "country_name_en": "Lydia",
    "country_name_de": "Lydien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Scythian",
    "name_de": "Skythisch",
    "country_name_en": "Scythia",
    "country_name_de": "Skythien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Nubian",
    "name_de": "Nubisch",
    "country_name_en": "Kingdom of Kush",
    "country_name_de": "Königreich von Kusch",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Etruscan",
    "name_de": "Etruskisch",
    "country_name_en": "Etruria",
    "country_name_de": "Etrurien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Berber",
    "name_de": "Berberisch",
    "country_name_en": "Numidia",
    "country_name_de": "Numidien",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Germanic (Proto-Germanic)",
    "name_de": "Germanisch (Ur-Germanisch)",
    "country_name_en": "Germanic Tribes",
    "country_name_de": "Germanische Stämme",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Sogdian",
    "name_de": "Sogdisch",
    "country_name_en": "Sogdia",
    "country_name_de": "Sogdien",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Parthian",
    "name_de": "Parthisch",
    "country_name_en": "Parthian Empire",
    "country_name_de": "Parthisches Reich",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Anatolian (Various Languages)",
    "name_de": "Anatolisch (Verschiedene Sprachen)",
    "country_name_en": "Anatolia",
    "country_name_de": "Anatolien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Old Macedonian",
    "name_de": "Altmakedonisch",
    "country_name_en": "Macedonia",
    "country_name_de": "Makedonien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Armenian",
    "name_de": "Armenisch",
    "country_name_en": "Kingdom of Armenia",
    "country_name_de": "Königreich Armenien",
    "amount_of_people_speaking": 900000
  },
  {
    "name_en": "Goidelic (Primitive Irish)",
    "name_de": "Goidelisch (Primitives Irisch)",
    "country_name_en": "Ireland",
    "country_name_de": "Irland",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Brittonic",
    "name_de": "Brittonisch",
    "country_name_en": "Britannia",
    "country_name_de": "Britannien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Old Norse (Proto-Norse)",
    "name_de": "Altnordisch (Urnordisch)",
    "country_name_en": "Scandinavian Tribes",
    "country_name_de": "Skandinavische Stämme",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Epirote",
    "name_de": "Epirotisch",
    "country_name_en": "Epirus",
    "country_name_de": "Epirus",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Ligurian",
    "name_de": "Ligurisch",
    "country_name_en": "Liguria",
    "country_name_de": "Ligurien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Dacian",
    "name_de": "Dakisch",
    "country_name_en": "Dacia",
    "country_name_de": "Dakien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Hittite",
    "name_de": "Hethitisch",
    "country_name_en": "Neo-Hittite States",
    "country_name_de": "Neo-hethitische Staaten",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Gothic (Early)",
    "name_de": "Gotisch (Früh)",
    "country_name_en": "Gothic Tribes",
    "country_name_de": "Gotische Stämme",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Old Malayalam (Proto-Dravidian)",
    "name_de": "Alt-Malayalam (Ur-Dravidisch)",
    "country_name_en": "South India",
    "country_name_de": "Südindien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "Tamilakam",
    "country_name_de": "Tamilakam",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Kannada",
    "name_de": "Kannada",
    "country_name_en": "Karnata",
    "country_name_de": "Karnata",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "Andhra",
    "country_name_de": "Andhra",
    "amount_of_people_speaking": 900000
  },
  {
    "name_en": "Mayan Languages",
    "name_de": "Maya-Sprachen",
    "country_name_en": "Maya City-States",
    "country_name_de": "Maya-Stadtstaaten",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Zapotec",
    "name_de": "Zapotekisch",
    "country_name_en": "Zapotec Civilization",
    "country_name_de": "Zapotekische Zivilisation",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Quechua (Proto-Quechua)",
    "name_de": "Quechua (Ur-Quechua)",
    "country_name_en": "Andean Region",
    "country_name_de": "Andenregion",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Nahuatl (Proto-Nahuan)",
    "name_de": "Nahuatl (Ur-Nahuan)",
    "country_name_en": "Central Mexico",
    "country_name_de": "Zentralmexiko",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Japanese (Old Japanese)",
    "name_de": "Japanisch (Altjapanisch)",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Korean (Old Korean)",
    "name_de": "Koreanisch (Altkoreanisch)",
    "country_name_en": "Gojoseon",
    "country_name_de": "Gojoseon",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Vietnamese (Proto-Vietic)",
    "name_de": "Vietnamesisch (Ur-Vietic)",
    "country_name_en": "Âu Lạc",
    "country_name_de": "Âu Lạc",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Mongolic (Proto-Mongolic)",
    "name_de": "Mongolisch (Ur-Mongolisch)",
    "country_name_en": "Mongolian Steppes",
    "country_name_de": "Mongolische Steppen",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Turkic (Proto-Turkic)",
    "name_de": "Turkisch (Ur-Turkisch)",
    "country_name_en": "Central Asia",
    "country_name_de": "Zentralasien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Basque",
    "name_de": "Baskisch",
    "country_name_en": "Vasconia",
    "country_name_de": "Vasconia",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Umbrian",
    "name_de": "Umbrisch",
    "country_name_en": "Umbria",
    "country_name_de": "Umbrien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Oscan",
    "name_de": "Oskisch",
    "country_name_en": "Samnium",
    "country_name_de": "Samnium",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Venetic",
    "name_de": "Venetisch",
    "country_name_en": "Venetia",
    "country_name_de": "Venetien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Phrygian",
    "name_de": "Phrygisch",
    "country_name_en": "Phrygia",
    "country_name_de": "Phrygien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Luwian",
    "name_de": "Luwisch",
    "country_name_en": "Anatolia",
    "country_name_de": "Anatolien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Elamite",
    "name_de": "Elamisch",
    "country_name_en": "Elam",
    "country_name_de": "Elam",
    "amount_of_people_speaking": 150000
  },
  {
    "name_en": "Numidian",
    "name_de": "Numidisch",
    "country_name_en": "Numidia",
    "country_name_de": "Numidien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Edomite",
    "name_de": "Edomitisch",
    "country_name_en": "Edom",
    "country_name_de": "Edom",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Moabite",
    "name_de": "Moabitisch",
    "country_name_en": "Moab",
    "country_name_de": "Moab",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Ammonite",
    "name_de": "Ammonitisch",
    "country_name_en": "Ammon",
    "country_name_de": "Ammon",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Anasazi (Proto-Puebloan)",
    "name_de": "Anasazi (Ur-Pueblo)",
    "country_name_en": "Southwestern North America",
    "country_name_de": "Südwestliches Nordamerika",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Inuit (Proto-Inuit)",
    "name_de": "Inuit (Ur-Inuit)",
    "country_name_en": "Arctic Regions",
    "country_name_de": "Arktische Regionen",
    "amount_of_people_speaking": 40000
  },
  {
    "name_en": "Maori (Proto-Polynesian)",
    "name_de": "Maori (Ur-Polynesisch)",
    "country_name_en": "Polynesia",
    "country_name_de": "Polynesien",
    "amount_of_people_speaking": 60000
  },
  {
    "name_en": "Bantu Languages",
    "name_de": "Bantu-Sprachen",
    "country_name_en": "Sub-Saharan Africa",
    "country_name_de": "Subsahara-Afrika",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Yoruba",
    "name_de": "Yoruba",
    "country_name_en": "West Africa",
    "country_name_de": "Westafrika",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Igbo",
    "name_de": "Igbo",
    "country_name_en": "West Africa",
    "country_name_de": "Westafrika",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Zulu",
    "name_de": "Zulu",
    "country_name_en": "Southern Africa",
    "country_name_de": "Südliches Afrika",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Swahili (Proto-Sabaki)",
    "name_de": "Swahili (Ur-Sabaki)",
    "country_name_en": "East Africa",
    "country_name_de": "Ostafrika",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Avestan",
    "name_de": "Avestisch",
    "country_name_en": "Bactria",
    "country_name_de": "Baktrien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Old Armenian",
    "name_de": "Altarmenisch",
    "country_name_en": "Armenia",
    "country_name_de": "Armenien",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Kurdish (Proto-Kurdish)",
    "name_de": "Kurdisch (Ur-Kurdisch)",
    "country_name_en": "Median Empire",
    "country_name_de": "Mederreich",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Syriac",
    "name_de": "Syrisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Akkadian",
    "name_de": "Akkadisch",
    "country_name_en": "Mesopotamia",
    "country_name_de": "Mesopotamien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Sumerian",
    "name_de": "Sumerisch",
    "country_name_en": "Mesopotamia",
    "country_name_de": "Mesopotamien",
    "amount_of_people_speaking": 150000
  },
  {
    "name_en": "Hunnic",
    "name_de": "Hunisch",
    "country_name_en": "Hunnic Tribes",
    "country_name_de": "Hunnenstämme",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Lusitanian",
    "name_de": "Lusitanisch",
    "country_name_en": "Lusitania",
    "country_name_de": "Lusitanien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Elymian",
    "name_de": "Elymisch",
    "country_name_en": "Sicily",
    "country_name_de": "Sizilien",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Messapian",
    "name_de": "Messapisch",
    "country_name_en": "Apulia",
    "country_name_de": "Apulien",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Picene",
    "name_de": "Picenisch",
    "country_name_en": "Picenum",
    "country_name_de": "Picenum",
    "amount_of_people_speaking": 60000
  },
  {
    "name_en": "Lepontic",
    "name_de": "Lepontisch",
    "country_name_en": "Alpine Region",
    "country_name_de": "Alpenregion",
    "amount_of_people_speaking": 70000
  },
  {
    "name_en": "Raetic",
    "name_de": "Rätisch",
    "country_name_en": "Rhaetia",
    "country_name_de": "Rätien",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Venetic (Adriatic Venetic)",
    "name_de": "Venetisch (Adriatisch Venetisch)",
    "country_name_en": "Venetia",
    "country_name_de": "Venetien",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Hurrian",
    "name_de": "Hurrier",
    "country_name_en": "Hurrian States",
    "country_name_de": "Hurritische Staaten",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Minoan",
    "name_de": "Minoisch",
    "country_name_en": "Crete",
    "country_name_de": "Kreta",
    "amount_of_people_speaking": 40000
  },
  {
    "name_en": "Pelasgian",
    "name_de": "Pelasgisch",
    "country_name_en": "Greece",
    "country_name_de": "Griechenland",
    "amount_of_people_speaking": 30000
  },
  {
    "name_en": "Sabean",
    "name_de": "Sabaeisch",
    "country_name_en": "Kingdom of Saba",
    "country_name_de": "Königreich von Saba",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Ge'ez",
    "name_de": "Geʿez",
    "country_name_en": "Kingdom of Aksum",
    "country_name_de": "Königreich von Aksum",
    "amount_of_people_speaking": 150000
  }
]
    """
    )


def get_victorian_languages():
    return json.loads(
        """
        [
  {
    "name_en": "Mandarin Chinese",
    "name_de": "Mandarin-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 400000000
  },
  {
    "name_en": "Hindi",
    "name_de": "Hindi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 150000000
  },
  {
    "name_en": "English",
    "name_de": "Englisch",
    "country_name_en": "United Kingdom",
    "country_name_de": "Vereinigtes Königreich",
    "amount_of_people_speaking": 130000000
  },
  {
    "name_en": "Spanish",
    "name_de": "Spanisch",
    "country_name_en": "Spain",
    "country_name_de": "Spanien",
    "amount_of_people_speaking": 100000000
  },
  {
    "name_en": "Russian",
    "name_de": "Russisch",
    "country_name_en": "Russia",
    "country_name_de": "Russland",
    "amount_of_people_speaking": 80000000
  },
  {
    "name_en": "Bengali",
    "name_de": "Bengalisch",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 75000000
  },
  {
    "name_en": "Portuguese",
    "name_de": "Portugiesisch",
    "country_name_en": "Portugal",
    "country_name_de": "Portugal",
    "amount_of_people_speaking": 60000000
  },
  {
    "name_en": "German",
    "name_de": "Deutsch",
    "country_name_en": "Germany",
    "country_name_de": "Deutschland",
    "amount_of_people_speaking": 50000000
  },
  {
    "name_en": "Japanese",
    "name_de": "Japanisch",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 40000000
  },
  {
    "name_en": "French",
    "name_de": "Französisch",
    "country_name_en": "France",
    "country_name_de": "Frankreich",
    "amount_of_people_speaking": 35000000
  },
  {
    "name_en": "Italian",
    "name_de": "Italienisch",
    "country_name_en": "Italy",
    "country_name_de": "Italien",
    "amount_of_people_speaking": 30000000
  },
  {
    "name_en": "Turkish",
    "name_de": "Türkisch",
    "country_name_en": "Ottoman Empire",
    "country_name_de": "Osmanisches Reich",
    "amount_of_people_speaking": 25000000
  },
  {
    "name_en": "Vietnamese",
    "name_de": "Vietnamesisch",
    "country_name_en": "Vietnam",
    "country_name_de": "Vietnam",
    "amount_of_people_speaking": 20000000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 18000000
  },
  {
    "name_en": "Korean",
    "name_de": "Koreanisch",
    "country_name_en": "Korea",
    "country_name_de": "Korea",
    "amount_of_people_speaking": 15000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 13000000
  },
  {
    "name_en": "Marathi",
    "name_de": "Marathi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Urdu",
    "name_de": "Urdu",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 11000000
  },
  {
    "name_en": "Persian",
    "name_de": "Persisch",
    "country_name_en": "Persia",
    "country_name_de": "Persien",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Javanese",
    "name_de": "Javanisch",
    "country_name_en": "Java (Dutch East Indies)",
    "country_name_de": "Java (Niederländisch-Indien)",
    "amount_of_people_speaking": 9500000
  }
]
        """
    )
