# Generated by Django 4.1.7 on 2023-04-27 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0027_wikipage_actions_heading_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipagegameaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="wikipagegamevalues",
            name="created_by",
        ),
    ]
