# Generated by Django 4.1.7 on 2023-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0028_remove_wikipagegameaction_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipage",
            name="actions_heading_de",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="actions heading"
            ),
        ),
    ]
