# Generated by Django 4.1.7 on 2023-04-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0029_alter_wikipage_actions_heading_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldsiteconfiguration",
            name="brand_logo",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to="",
                verbose_name="Brand Logo",
            ),
        ),
    ]
