# Generated by Django 4.1.7 on 2023-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0030_worldsiteconfiguration_brand_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipagegamevalues",
            name="perception",
            field=models.IntegerField(default=2, verbose_name="perception"),
        ),
        migrations.AlterField(
            model_name="worldsiteconfiguration",
            name="brand_logo",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to="brand_logos",
                verbose_name="Brand Logo",
            ),
        ),
    ]
