# Generated by Django 4.1.7 on 2023-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0031_wikipagegamevalues_perception_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipagegamevalues",
            name="stress_test_failed_stress",
            field=models.IntegerField(
                default=0, verbose_name="stress test failed stress"
            ),
        ),
        migrations.AddField(
            model_name="wikipagegamevalues",
            name="stress_test_succeeded_stress",
            field=models.IntegerField(
                default=0, verbose_name="stress test succeeded stress"
            ),
        ),
        migrations.AddField(
            model_name="wikipagegamevalues",
            name="walking_range",
            field=models.IntegerField(default=4, verbose_name="walking range"),
        ),
    ]
