# Generated by Django 4.1.7 on 2023-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0032_wikipagegamevalues_stress_test_failed_stress_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipagegamevalues",
            options={
                "get_latest_by": "id",
                "verbose_name": "wiki page game values",
                "verbose_name_plural": "wiki page game values",
            },
        ),
    ]
