# Generated by Django 3.2.12 on 2022-03-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_boardsubscription_forumsettings_threadsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created_at',)},
        ),
    ]
