# Generated by Django 4.1.3 on 2022-12-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
    ]
