# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0001_initial"),
        ("campaigns", "0003_initial"),
        ("magic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spelltype",
            name="reference_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.attribute",
                verbose_name="reference attribute",
            ),
        ),
        migrations.AddField(
            model_name="spelltemplatemodifier",
            name="shape_change",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magic.spellshape",
                verbose_name="shape change",
            ),
        ),
        migrations.AddField(
            model_name="spelltemplatemodifier",
            name="spell_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="magic.spelltemplate"
            ),
        ),
        migrations.AddField(
            model_name="spelltemplatemodifier",
            name="type_change",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magic.spelltype",
                verbose_name="type change",
            ),
        ),
        migrations.AddField(
            model_name="spelltemplatemodifier",
            name="variant_change",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magic.spellvariant",
                verbose_name="variant change",
            ),
        ),
        migrations.AddField(
            model_name="spelltemplate",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="magic.spelltemplatecategory",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magic.spellorigin",
                verbose_name="origin",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="shape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magic.spellshape",
                verbose_name="shape",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="magic.spelltype",
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="basespell",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="magic.spellvariant",
                verbose_name="variant",
            ),
        ),
    ]
