# Generated by Django 5.1 on 2024-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0007_remove_basespell_is_tirakan_spell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basespell",
            name="power",
        ),
        migrations.AddField(
            model_name="basespell",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rounds", "rounds"),
                    ("minutes", "minutes"),
                    ("hours", "hours"),
                    ("days", "days"),
                    ("weeks", "weeks"),
                    ("months", "months"),
                    ("years", "years"),
                ],
                max_length=10,
                null=True,
                verbose_name="duration unit",
            ),
        ),
    ]
