# Generated by Django 5.1 on 2024-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0009_alter_basespell_duration_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basespell",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("actions", "actions"),
                    ("rounds", "rounds"),
                    ("seconds", "seconds"),
                    ("minutes", "minutes"),
                    ("hours", "hours"),
                    ("days", "days"),
                    ("nights", "nights"),
                    ("weeks", "weeks"),
                    ("months", "months"),
                    ("years", "years"),
                ],
                max_length=10,
                null=True,
                verbose_name="duration unit",
            ),
        ),
    ]
