# Generated by Django 5.2.6 on 2025-09-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0010_alter_basespell_duration_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spelltemplatemodifier",
            options={
                "verbose_name": "spell template modifier",
                "verbose_name_plural": "spell template modifiers",
            },
        ),
    ]
