# Generated by Django 5.2.6 on 2025-09-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0011_alter_spelltemplatemodifier_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spelltemplatemodifier",
            name="attribute",
            field=models.CharField(
                blank=True,
                choices=[
                    ("power", "Power"),
                    ("range", "Range"),
                    ("actions", "Actions"),
                    ("arcana_cost", "Arcana"),
                ],
                max_length=40,
                null=True,
                verbose_name="attribute",
            ),
        ),
    ]
