# Generated by Django 6.0.6 on 2026-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0013_alter_spellorigin_image_alter_spelltype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="basespell",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="spellorigin",
            name="essential_description",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential description",
            ),
        ),
        migrations.AddField(
            model_name="spellorigin",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
    ]
