# Generated by Django 5.2.7 on 2025-11-14 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0018_delete_foe"),
        ("characters", "0028_characterriotgear_is_equipped"),
        ("rules", "0022_extension_fa_icon_latex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                ("extensions", models.ManyToManyField(to="rules.extension")),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="campaigns.campaign",
                        verbose_name="homebrew campaign",
                    ),
                ),
                (
                    "homebrew_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_%(app_label)s_%(class)s_set",
                        to="characters.character",
                        verbose_name="homebrew character",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
    ]
