# Generated by Django 5.2.7 on 2025-11-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeDifficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe difficulty",
                "verbose_name_plural": "recipe difficulties",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="potions.recipedifficulty",
                verbose_name="difficulty",
            ),
            preserve_default=False,
        ),
    ]
