# Generated by Django 5.2.7 on 2025-11-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0033_alter_protectiontype_options_and_more"),
        ("potions", "0002_recipedifficulty_recipe_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredientUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe ingredient unit",
                "verbose_name_plural": "recipe ingredient units",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.item"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="potions.recipe"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="potions.recipeingredientunit",
                        verbose_name="unit",
                    ),
                ),
            ],
        ),
    ]
