# Generated by Django 5.2.8 on 2025-12-04 13:49

from django.db import migrations


def forward(apps, schema_editor):
    RecipeCategory = apps.get_model("potions", "RecipeCategory")
    RecipeCategory.objects.create(name_de="Tränke", name_en="Potions")


class Migration(migrations.Migration):

    dependencies = [
        ("potions", "0004_recipecategory_recipe_category"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
