# Generated by Django 5.2.8 on 2025-12-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potions", "0005_auto_20251204_1349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="potions.recipecategory",
            ),
            preserve_default=False,
        ),
    ]
