# Generated by Django 5.2.9 on 2025-12-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potions", "0006_alter_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="expected_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="expected amount"
            ),
        ),
    ]
