# Generated by Django 6.0.6 on 2026-06-11 07:34

import django.db.models.deletion
import phasesix.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("armory", "0036_alter_item_image_alter_weapon_image"),
        ("campaigns", "0025_campaign_ruleset"),
        ("magic", "0013_alter_spellorigin_image_alter_spelltype_image"),
        ("plots", "0018_alter_handout_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EssentialAncestry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=160, unique=True)),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("description_de", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("benefit_de", models.TextField(blank=True)),
                ("benefit_en", models.TextField(blank=True, null=True)),
                ("vulnerability_de", models.TextField(blank=True)),
                ("vulnerability_en", models.TextField(blank=True, null=True)),
                ("skills_de", models.TextField(blank=True)),
                ("skills_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name_de",),
            },
        ),
        migrations.CreateModel(
            name="EssentialBond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=160, unique=True)),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("description_de", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("benefit_de", models.TextField(blank=True)),
                ("benefit_en", models.TextField(blank=True, null=True)),
                ("vulnerability_de", models.TextField(blank=True)),
                ("vulnerability_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name_de",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EssentialPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=160, unique=True)),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("description_de", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("benefit_de", models.TextField(blank=True)),
                ("benefit_en", models.TextField(blank=True, null=True)),
                ("vulnerability_de", models.TextField(blank=True)),
                ("vulnerability_en", models.TextField(blank=True, null=True)),
                ("facet_de", models.TextField(blank=True)),
                ("facet_en", models.TextField(blank=True, null=True)),
                ("skills_de", models.TextField(blank=True)),
                ("skills_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name_de",),
            },
        ),
        migrations.CreateModel(
            name="EssentialSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EssentialArmorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protection", models.CharField(max_length=40)),
                ("load", models.CharField(max_length=40)),
                ("sealing", models.CharField(max_length=40)),
                ("properties", models.TextField(blank=True)),
                (
                    "riot_gear",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.riotgear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssentialCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("birth_date", models.CharField(blank=True, max_length=40)),
                ("century", models.PositiveSmallIntegerField(default=1)),
                ("concept", models.TextField(blank=True)),
                ("oath_or_debt", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to=phasesix.models.image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("mind", models.PositiveSmallIntegerField(default=0)),
                ("will", models.PositiveSmallIntegerField(default=0)),
                ("instinct", models.PositiveSmallIntegerField(default=0)),
                ("dexterity", models.PositiveSmallIntegerField(default=0)),
                ("body", models.PositiveSmallIntegerField(default=0)),
                ("presence", models.PositiveSmallIntegerField(default=0)),
                ("gift", models.PositiveSmallIntegerField(default=0)),
                ("perception", models.PositiveSmallIntegerField(default=0)),
                ("wounds", models.PositiveSmallIntegerField(default=0)),
                ("burden", models.PositiveSmallIntegerField(default=0)),
                ("omen", models.PositiveSmallIntegerField(default=0)),
                ("arkana", models.PositiveSmallIntegerField(default=0)),
                ("favor", models.PositiveSmallIntegerField(default=0)),
                ("corruption", models.PositiveSmallIntegerField(default=0)),
                ("focus", models.CharField(blank=True, max_length=200)),
                ("regeneration_ritual", models.TextField(blank=True)),
                (
                    "ancestry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialancestry",
                    ),
                ),
                (
                    "bond",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialbond",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "npc_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essential_npc_set",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essential_plot_npc_set",
                        to="plots.plot",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_favorite", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="EssentialCharacterArmor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipped", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialarmorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="armor",
            field=models.ManyToManyField(
                blank=True,
                through="essential_characters.EssentialCharacterArmor",
                to="essential_characters.essentialarmorprofile",
            ),
        ),
        migrations.CreateModel(
            name="EssentialCharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                through="essential_characters.EssentialCharacterItem",
                to="armory.item",
            ),
        ),
        migrations.CreateModel(
            name="EssentialMagicAspectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "spell_origin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magic.spellorigin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="magic_aspects",
            field=models.ManyToManyField(
                blank=True, to="essential_characters.essentialmagicaspectprofile"
            ),
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="essential_characters.essentialpath",
            ),
        ),
        migrations.CreateModel(
            name="EssentialCharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialskill",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="skills",
            field=models.ManyToManyField(
                through="essential_characters.EssentialCharacterSkill",
                to="essential_characters.essentialskill",
            ),
        ),
        migrations.CreateModel(
            name="EssentialSpellProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=80)),
                ("element", models.CharField(blank=True, max_length=80)),
                ("action", models.CharField(blank=True, max_length=80)),
                ("minimum_roll", models.CharField(blank=True, max_length=40)),
                ("cost", models.CharField(blank=True, max_length=40)),
                ("range", models.CharField(blank=True, max_length=80)),
                ("duration", models.CharField(blank=True, max_length=80)),
                ("area", models.CharField(blank=True, max_length=80)),
                ("casting_time", models.CharField(blank=True, max_length=80)),
                ("resisted", models.CharField(blank=True, max_length=40)),
                ("description", models.TextField(blank=True)),
                (
                    "aspect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialmagicaspectprofile",
                    ),
                ),
                (
                    "spell",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magic.basespell",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssentialCharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialspellprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="spells",
            field=models.ManyToManyField(
                blank=True,
                through="essential_characters.EssentialCharacterSpell",
                to="essential_characters.essentialspellprofile",
            ),
        ),
        migrations.CreateModel(
            name="EssentialWeaponProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=40)),
                ("range", models.CharField(max_length=80)),
                ("grip", models.CharField(max_length=40)),
                ("properties", models.TextField(blank=True)),
                (
                    "weapon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.weapon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssentialCharacterWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        max_length=20,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialweaponprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="essentialcharacter",
            name="weapons",
            field=models.ManyToManyField(
                blank=True,
                through="essential_characters.EssentialCharacterWeapon",
                to="essential_characters.essentialweaponprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="essentialcharacterskill",
            constraint=models.UniqueConstraint(
                fields=("character", "skill"), name="unique_essential_character_skill"
            ),
        ),
    ]
