# Generated by Django 6.0.6 on 2026-06-11 09:31

import django.db.models.deletion
import phasesix.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("armory", "0037_item_essential_enabled_riotgear_essential_enabled_and_more"),
        ("campaigns", "0025_campaign_ruleset"),
        ("magic", "0014_basespell_essential_enabled_and_more"),
        ("plots", "0018_alter_handout_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EssentialAncestry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(max_length=160, unique=True, verbose_name="name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "benefit_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="benefit"
                    ),
                ),
                (
                    "benefit_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="benefit"
                    ),
                ),
                (
                    "vulnerability_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="vulnerability"
                    ),
                ),
                (
                    "vulnerability_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="vulnerability",
                    ),
                ),
                (
                    "skills_de",
                    models.CharField(blank=True, max_length=500, verbose_name="skills"),
                ),
                (
                    "skills_en",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="skills"
                    ),
                ),
            ],
            options={
                "ordering": ("name_de",),
            },
        ),
        migrations.CreateModel(
            name="EssentialBond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(max_length=160, unique=True, verbose_name="name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "benefit_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="benefit"
                    ),
                ),
                (
                    "benefit_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="benefit"
                    ),
                ),
                (
                    "vulnerability_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="vulnerability"
                    ),
                ),
                (
                    "vulnerability_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ("name_de",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EssentialPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(max_length=160, unique=True, verbose_name="name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "benefit_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="benefit"
                    ),
                ),
                (
                    "benefit_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="benefit"
                    ),
                ),
                (
                    "vulnerability_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="vulnerability"
                    ),
                ),
                (
                    "vulnerability_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="vulnerability",
                    ),
                ),
                (
                    "facet_de",
                    models.CharField(blank=True, max_length=255, verbose_name="facet"),
                ),
                (
                    "facet_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="facet"
                    ),
                ),
                (
                    "skills_de",
                    models.CharField(blank=True, max_length=500, verbose_name="skills"),
                ),
                (
                    "skills_en",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="skills"
                    ),
                ),
            ],
            options={
                "ordering": ("name_de",),
            },
        ),
        migrations.CreateModel(
            name="EssentialCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="slug"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "birth_date",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="birth date"
                    ),
                ),
                (
                    "century",
                    models.PositiveSmallIntegerField(default=1, verbose_name="century"),
                ),
                (
                    "concept",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="concept"
                    ),
                ),
                (
                    "oath_or_debt",
                    models.TextField(blank=True, verbose_name="oath or debt"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to=phasesix.models.image_upload_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="is favorite"),
                ),
                (
                    "mind",
                    models.PositiveSmallIntegerField(default=0, verbose_name="mind"),
                ),
                (
                    "will",
                    models.PositiveSmallIntegerField(default=0, verbose_name="will"),
                ),
                (
                    "instinct",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="instinct"
                    ),
                ),
                (
                    "dexterity",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="dexterity"
                    ),
                ),
                (
                    "body",
                    models.PositiveSmallIntegerField(default=0, verbose_name="body"),
                ),
                (
                    "presence",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="presence"
                    ),
                ),
                (
                    "gift",
                    models.PositiveSmallIntegerField(default=0, verbose_name="gift"),
                ),
                (
                    "perception",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="perception"
                    ),
                ),
                (
                    "wounds",
                    models.PositiveSmallIntegerField(default=0, verbose_name="wounds"),
                ),
                (
                    "burden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="burden"),
                ),
                (
                    "omen",
                    models.PositiveSmallIntegerField(default=0, verbose_name="omen"),
                ),
                (
                    "arkana",
                    models.PositiveSmallIntegerField(default=0, verbose_name="arkana"),
                ),
                (
                    "favor",
                    models.PositiveSmallIntegerField(default=0, verbose_name="favor"),
                ),
                (
                    "corruption",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="corruption"
                    ),
                ),
                (
                    "focus",
                    models.CharField(blank=True, max_length=200, verbose_name="focus"),
                ),
                (
                    "regeneration_ritual",
                    models.TextField(blank=True, verbose_name="regeneration ritual"),
                ),
                (
                    "ancestry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialancestry",
                        verbose_name="ancestry",
                    ),
                ),
                (
                    "armor",
                    models.ManyToManyField(
                        blank=True, to="armory.riotgear", verbose_name="armor"
                    ),
                ),
                (
                    "bond",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialbond",
                        verbose_name="bond",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                        verbose_name="campaign",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="essential_characters.essentialcharacter",
                        verbose_name="cloned from",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, to="armory.item", verbose_name="items"
                    ),
                ),
                (
                    "magic_aspects",
                    models.ManyToManyField(
                        blank=True, to="magic.spellorigin", verbose_name="magic aspects"
                    ),
                ),
                (
                    "npc_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essential_npc_set",
                        to="campaigns.campaign",
                        verbose_name="NPC campaign",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essential_plot_npc_set",
                        to="plots.plot",
                        verbose_name="plot",
                    ),
                ),
                (
                    "spells",
                    models.ManyToManyField(
                        blank=True, to="magic.basespell", verbose_name="spells"
                    ),
                ),
                (
                    "weapons",
                    models.ManyToManyField(
                        blank=True, to="armory.weapon", verbose_name="weapons"
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="essential_characters.essentialpath",
                        verbose_name="path",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_favorite", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="EssentialCharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="name")),
                (
                    "rank",
                    models.PositiveSmallIntegerField(default=1, verbose_name="rank"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="essential_characters.essentialcharacter",
                        verbose_name="character",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "name"),
                        name="unique_essential_character_skill",
                    )
                ],
            },
        ),
    ]
