# Generated by Django 6.0.6 on 2026-06-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_campaign_backdrop_image_focal_x_and_more'),
        ('characters', '0037_character_backdrop_image_focal_x_and_more'),
        ('essential_characters', '0003_essentialcharacter_image_focal_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essentialbond',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='essentialbond',
            name='homebrew_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homebrew_%(app_label)s_%(class)s_set', to='campaigns.campaign', verbose_name='homebrew campaign'),
        ),
        migrations.AddField(
            model_name='essentialbond',
            name='homebrew_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homebrew_%(app_label)s_%(class)s_set', to='characters.character', verbose_name='homebrew character'),
        ),
        migrations.AddField(
            model_name='essentialbond',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='is homebrew'),
        ),
        migrations.AddField(
            model_name='essentialbond',
            name='keep_as_homebrew',
            field=models.BooleanField(default=False, help_text='This was not accepted as general spell and is kept as homebrew.', verbose_name='keep as homebrew'),
        ),
    ]
