# Generated by Django 6.0.6 on 2026-06-14 15:23

from django.db import migrations, models


def copy_existing_skill_names(apps, schema_editor):
    skill = apps.get_model("essential_characters", "EssentialCharacterSkill")
    skill.objects.filter(name_en__isnull=True).update(name_en=models.F("name_de"))


class Migration(migrations.Migration):

    dependencies = [
        ("essential_characters", "0004_essentialbond_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="essentialcharacterskill",
            options={"ordering": ("name_de",)},
        ),
        migrations.RemoveConstraint(
            model_name="essentialcharacterskill",
            name="unique_essential_character_skill",
        ),
        migrations.RenameField(
            model_name="essentialcharacterskill",
            old_name="name",
            new_name="name_de",
        ),
        migrations.AddField(
            model_name="essentialcharacterskill",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="name"
            ),
        ),
        migrations.RunPython(copy_existing_skill_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="essentialcharacterskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name_de"),
                name="unique_essential_character_skill_de",
            ),
        ),
        migrations.AddConstraint(
            model_name="essentialcharacterskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name_en"),
                name="unique_essential_character_skill_en",
            ),
        ),
    ]
