# Generated by Django 5.2.5 on 2025-09-02 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0028_characterriotgear_is_equipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="Handout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_handout_images",
                        verbose_name="Bild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_location_images",
                        verbose_name="Bild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("abstract", models.TextField(verbose_name="Zusammenfassung")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_images",
                        verbose_name="Bild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("r", "Plot Root"),
                            ("a", "Act"),
                            ("s", "Scene"),
                            ("e", "Encounter"),
                        ],
                        default="s",
                        max_length=1,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "gm_notes",
                    models.TextField(blank=True, null=True, verbose_name="GM notes"),
                ),
                (
                    "player_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="player summary"
                    ),
                ),
                ("handouts", models.ManyToManyField(to="plots.handout")),
                ("locations", models.ManyToManyField(to="plots.location")),
                ("npc", models.ManyToManyField(to="characters.character")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="plots.plotelement",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plots.plot",
                        verbose_name="Plot",
                    ),
                ),
            ],
        ),
    ]
