# Generated by Django 5.2.6 on 2025-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="description",
        ),
        migrations.AddField(
            model_name="plot",
            name="gm_description",
            field=models.TextField(default="", verbose_name="gm description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plot",
            name="player_abstract",
            field=models.TextField(default="", verbose_name="abstract for players"),
            preserve_default=False,
        ),
    ]
