# Generated by Django 5.2.6 on 2025-09-03 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0002_remove_plot_abstract_remove_plot_description_and_more"),
        ("rules", "0021_alter_extension_fixed_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="epoch_extension",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"is_mandatory": False, "type": "e"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_epoch_set",
                to="rules.extension",
                verbose_name="Epoche",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plot",
            name="extensions",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_mandatory": False, "type": "x"},
                to="rules.extension",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="world_extension",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"is_mandatory": False, "type": "w"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_world_set",
                to="rules.extension",
                verbose_name="Welt",
            ),
            preserve_default=False,
        ),
    ]
