# Generated by Django 5.2.6 on 2025-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0003_plot_epoch_extension_plot_extensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotelement",
            name="language",
            field=models.CharField(default="en", max_length=4, verbose_name="Sprache"),
        ),
    ]
