# Generated by Django 5.2.6 on 2025-09-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0004_plotelement_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotelement",
            name="language",
        ),
        migrations.AddField(
            model_name="plot",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English")],
                default="en",
                max_length=4,
                verbose_name="Sprache",
            ),
        ),
    ]
