# Generated by Django 5.2.6 on 2025-09-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0005_remove_plotelement_language_plot_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotelement",
            name="type",
            field=models.CharField(
                choices=[("a", "Act"), ("s", "Scene"), ("e", "Encounter")],
                default="s",
                max_length=1,
                verbose_name="Typ",
            ),
        ),
    ]
