# Generated by Django 5.2.6 on 2025-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0028_characterriotgear_is_equipped"),
        ("plots", "0006_alter_plotelement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotelement",
            name="handouts",
            field=models.ManyToManyField(blank=True, to="plots.handout"),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="locations",
            field=models.ManyToManyField(blank=True, to="plots.location"),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="npc",
            field=models.ManyToManyField(blank=True, to="characters.character"),
        ),
    ]
