# Generated by Django 5.2.6 on 2025-09-29 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0007_alter_plotelement_handouts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="gm_description",
            field=models.TextField(verbose_name="SL Beschreibung"),
        ),
        migrations.AlterField(
            model_name="plot",
            name="player_abstract",
            field=models.TextField(verbose_name="Zusammenfassung für Spieler"),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="gm_notes",
            field=models.TextField(blank=True, null=True, verbose_name="SL Notizen"),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="player_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Spielerzusammenfassung"
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plots.plot",
                verbose_name="Abenteuer",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="type",
            field=models.CharField(
                choices=[("a", "Akt"), ("s", "Szene"), ("e", "Begegnung")],
                default="s",
                max_length=1,
                verbose_name="Typ",
            ),
        ),
    ]
