# Generated by Django 5.2.9 on 2025-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0008_alter_plot_gm_description_alter_plot_player_abstract_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotelement",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="plotelement",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
        ),
    ]
