# Generated by Django 5.2.9 on 2025-12-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0009_alter_plotelement_options_plotelement_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("a", "Akt"),
                    ("s", "Szene"),
                    ("e", "Begegnung"),
                    ("i", "Info"),
                ],
                default="s",
                max_length=1,
                verbose_name="Typ",
            ),
        ),
    ]
