# Generated by Django 5.2.9 on 2025-12-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0011_plotelement_foes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotelement",
            name="type",
        ),
    ]
