# Generated by Django 5.2.9 on 2025-12-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0023_remove_campaign_plot"),
        ("plots", "0012_remove_plotelement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="campaign",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="campaign",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plots.plot",
                verbose_name="Geklont von",
            ),
        ),
    ]
