# Generated by Django 5.2.9 on 2025-12-31 00:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0023_remove_campaign_plot"),
        ("characters", "0036_alter_character_plot"),
        ("plots", "0013_plot_campaign_plot_cloned_from"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plot",
            options={"verbose_name": "plot", "verbose_name_plural": "plots"},
        ),
        migrations.AddField(
            model_name="plot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plot",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homebrew_%(app_label)s_%(class)s_set",
                to="campaigns.campaign",
                verbose_name="homebrew campaign",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="homebrew_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homebrew_%(app_label)s_%(class)s_set",
                to="characters.character",
                verbose_name="homebrew character",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="image_copyright",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="image copyright"
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="image_copyright_url",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="image copyright url",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_homebrew",
            field=models.BooleanField(default=False, verbose_name="is homebrew"),
        ),
        migrations.AddField(
            model_name="plot",
            name="keep_as_homebrew",
            field=models.BooleanField(
                default=False,
                help_text="This was not accepted as general spell and is kept as homebrew.",
                verbose_name="keep as homebrew",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
    ]
