# Generated by Django 5.2.9 on 2026-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0015_plot_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to="plot_location_images",
                verbose_name="Bild",
            ),
        ),
    ]
