# Generated by Django 5.2.9 on 2026-01-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0017_alter_plot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handout",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to="plot_handout_images",
                verbose_name="Bild",
            ),
        ),
    ]
