# Generated by Django 6.0.6 on 2026-06-11 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_campaign_ruleset'),
        ('essential_characters', '0001_initial'),
        ('plots', '0018_alter_handout_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Abenteuer', 'verbose_name_plural': 'Abenteuer'},
        ),
        migrations.AddField(
            model_name='plot',
            name='ruleset',
            field=models.CharField(choices=[('phasesix', 'PhaseSix'), ('tirakan_essential', 'Tirakan Essential')], default='phasesix', max_length=24, verbose_name='ruleset'),
        ),
        migrations.AddField(
            model_name='plotelement',
            name='essential_npc',
            field=models.ManyToManyField(blank=True, to='essential_characters.essentialcharacter'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='Kampagne'),
        ),
    ]
