# Generated by Django 6.0.6 on 2026-06-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0026_scene_essential_npc"),
        ("essential_characters", "0001_initial"),
        ("plots", "0018_alter_handout_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plot",
            options={"verbose_name": "Abenteuer", "verbose_name_plural": "Abenteuer"},
        ),
        migrations.AddField(
            model_name="plot",
            name="ruleset",
            field=models.CharField(
                choices=[
                    ("phasesix", "PhaseSix"),
                    ("tirakan_essential", "Tirakan Essential"),
                ],
                default="phasesix",
                max_length=24,
                verbose_name="ruleset",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="essential_npc",
            field=models.ManyToManyField(
                blank=True,
                related_name="essential_plot_elements",
                to="essential_characters.essentialcharacter",
                verbose_name="essential NPCs",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="campaign",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Kampagne",
            ),
        ),
    ]
