# Generated by Django 6.0.6 on 2026-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_characters', '0001_initial'),
        ('plots', '0019_alter_plot_options_plot_ruleset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotelement',
            name='essential_npc',
            field=models.ManyToManyField(blank=True, related_name='essential_plot_elements', to='essential_characters.essentialcharacter'),
        ),
    ]
