# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

VISIBILITY_CHOICES = (("G", _("GM Only")), ("P", _("GM and Players")), ("A", _("All")))
VISIBILITY_ORDER = {"G": 0, "P": 1, "A": 2}


def most_restrictive(*values):
    return min(values, key=lambda value: VISIBILITY_ORDER[value])


def copy_campaign_visibility(apps, schema_editor):
    Campaign = apps.get_model("campaigns", "Campaign")
    PlotElement = apps.get_model("plots", "PlotElement")

    for campaign in Campaign.objects.all().only(
        "id", "plot_visibility", "npc_visibility", "foe_visibility"
    ):
        elements = PlotElement.objects.filter(plot__campaign_id=campaign.id)
        elements.update(
            player_summary_visibility=campaign.plot_visibility,
            gm_notes_visibility="G",
            npc_visibility=most_restrictive(
                campaign.plot_visibility, campaign.npc_visibility
            ),
            handouts_visibility=campaign.plot_visibility,
            foes_visibility=most_restrictive(
                campaign.plot_visibility, campaign.foe_visibility
            ),
            locations_visibility=campaign.plot_visibility,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0030_campaign_plot_visibility"),
        ("plots", "0020_handout_image_focal_x_handout_image_focal_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotelement",
            name="player_summary_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="player summary visibility",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="gm_notes_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="GM notes visibility",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="npc_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="NPC visibility",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="handouts_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="handouts visibility",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="foes_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="foes visibility",
            ),
        ),
        migrations.AddField(
            model_name="plotelement",
            name="locations_visibility",
            field=models.CharField(
                choices=VISIBILITY_CHOICES,
                default="G",
                max_length=1,
                verbose_name="locations visibility",
            ),
        ),
        migrations.RunPython(copy_campaign_visibility, migrations.RunPython.noop),
    ]
