# Generated by Django 6.0.7 on 2026-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essential_characters", "0005_alter_essentialcharacterskill_options_and_more"),
        ("plots", "0021_plotelement_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="ruleset",
            field=models.CharField(
                choices=[
                    ("phasesix", "Phase Six"),
                    ("tirakan_essential", "Tirakan Essential"),
                ],
                default="phasesix",
                max_length=24,
                verbose_name="Regelsatz",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="essential_npc",
            field=models.ManyToManyField(
                blank=True,
                related_name="essential_plot_elements",
                to="essential_characters.essentialcharacter",
                verbose_name="Essential NSC",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="foes_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="foes visibility",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="gm_notes_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="GM notes visibility",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="handouts_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="handouts visibility",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="locations_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="locations visibility",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="npc_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="NPC visibility",
            ),
        ),
        migrations.AlterField(
            model_name="plotelement",
            name="player_summary_visibility",
            field=models.CharField(
                choices=[("G", "Nur SL"), ("P", "GM and Players"), ("A", "Alle")],
                default="G",
                max_length=1,
                verbose_name="player summary visibility",
            ),
        ),
    ]
