# Generated by Django 5.1 on 2024-08-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0006_rename_name_currencymapunit_name_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencymapunit",
            name="fa_icon_class",
            field=models.CharField(
                choices=[
                    ("fas fa-coins", "Coins"),
                    ("fas fa-euro-sign", "Euro"),
                    ("fas fa-dollar-sign", "Dollar"),
                    ("fas fa-rupee-sign", "Rupee"),
                    ("fas fa-pound-sign", "Pound"),
                    ("fas fa-lira-sign", "Lira"),
                    ("fas fa-shekel-sign", "Shekel"),
                    ("fas fa-yen-sign", "Yen"),
                    ("fas fa-won-sign", "Won"),
                    ("fas fa-cubes", "Cubes"),
                ],
                default="fas fa-coins",
                max_length=30,
                verbose_name="FA Icon Class",
            ),
        ),
    ]
