# Generated by Django 5.1.1 on 2024-10-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0008_riotgeartype_is_shield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("is_rare", models.BooleanField(default=False, verbose_name="is rare")),
                ("ordering", models.IntegerField(default=10, verbose_name="ordering")),
            ],
            options={
                "verbose_name": "keyword",
                "verbose_name_plural": "keywords",
                "ordering": ("-ordering",),
            },
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="encumbrance",
        ),
        migrations.AlterField(
            model_name="weaponmodificationattributechange",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("capacity", "Capacity"),
                    ("recoil_compensation", "Recoil compensation"),
                    ("actions_to_ready", "Actions to ready"),
                    ("crit_minimum_roll", "Crit minimum roll"),
                    ("damage_potential", "Damage potential"),
                    ("piercing", "Piercing"),
                    ("concealment", "Concealment"),
                    ("reload_actions", "Reload actions"),
                    ("range_meter", "Range (meter)"),
                ],
                max_length=40,
                verbose_name="attribute",
            ),
        ),
        migrations.CreateModel(
            name="WeaponKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=1, verbose_name="value")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.keyword"
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.weapon"
                    ),
                ),
            ],
            options={
                "verbose_name": "weapon keyword",
                "verbose_name_plural": "weapon keywords",
            },
        ),
        migrations.CreateModel(
            name="WeaponModificationKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0, verbose_name="value")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.keyword"
                    ),
                ),
                (
                    "weapon_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.weaponmodification",
                    ),
                ),
            ],
        ),
    ]
