# Generated by Django 5.1.1 on 2024-10-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0010_keyword_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="identifier",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="identifier"
            ),
        ),
    ]
