# Generated by Django 5.1.1 on 2024-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0011_alter_keyword_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="show_in_dice_rolls",
            field=models.BooleanField(default=False, verbose_name="show in dice rolls"),
        ),
    ]
