# Generated by Django 5.1.1 on 2024-10-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0015_auto_20241003_1718"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeaponAttackMode",
        ),
    ]
