# Generated by Django 5.1.1 on 2024-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0016_delete_weaponattackmode"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="is_evergreen",
            field=models.BooleanField(
                default=False,
                help_text="Evergreen keywords are the base of the combat mechanics.",
                verbose_name="is evergreen",
            ),
        ),
    ]
