# Generated by Django 5.1.1 on 2024-10-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0017_keyword_is_evergreen"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="show_in_summary",
            field=models.BooleanField(default=False, verbose_name="show in summary"),
        ),
    ]
