# Generated by Django 5.1.2 on 2024-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0018_keyword_show_in_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("ordering", models.IntegerField(default=10, verbose_name="ordering")),
                (
                    "rules",
                    models.TextField(
                        help_text="Rules for this protection type.",
                        verbose_name="rules",
                    ),
                ),
                (
                    "color_class",
                    models.CharField(
                        choices=[
                            ("text-white", "White"),
                            ("text-success", "Success"),
                            ("text-primary", "Primary"),
                            ("text-secondary", "Secondary"),
                            ("text-warning", "Warning"),
                            ("text-danger", "Danger"),
                        ],
                        default="text-warning",
                        max_length=30,
                    ),
                ),
                (
                    "fa_icon_class",
                    models.CharField(
                        choices=[("fas fa-shield-alt", "Shield")],
                        default="fas fa-shield-alt",
                        max_length=30,
                        verbose_name="FA Icon Class",
                    ),
                ),
            ],
            options={
                "ordering": ("-ordering",),
            },
        ),
    ]
