# Generated by Django 5.1.2 on 2024-11-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0019_protectiontype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protectiontype",
            name="fa_icon_class",
        ),
        migrations.AddField(
            model_name="protectiontype",
            name="icon_class",
            field=models.CharField(
                choices=[
                    ("fas fa-shield-alt", "Shield"),
                    ("delapouite-cross-shield", "Cross Shield"),
                    ("delapouite-dice-shield", "Dice Shield"),
                    ("delapouite-dragon-shield", "Dragon Shield"),
                    ("delapouite-griffin-shield", "Griffin Shield"),
                    ("delapouite-healing-shield", "Healing Shield"),
                    ("delapouite-heart-shield", "Heart Shield"),
                    ("delapouite-ribbon-shield", "Ribbon Shield"),
                    ("delapouite-roman-shield", "Roman Shield"),
                    ("delapouite-spiked-shield", "Spiked Shield"),
                    ("delapouite-templar-shield", "Templar Shield"),
                    ("delapouite-temporary-shield", "Temporary Shield"),
                    ("delapouite-tribal-shield", "Tribal Shield"),
                    ("delapouite-trident-shield", "Trident Shield"),
                    ("delapouite-vibrating-shield", "Vibrating Shield"),
                    ("delapouite-viking-shield", "Viking Shield"),
                ],
                default="fas fa-shield-alt",
                max_length=30,
                verbose_name="FA Icon Class",
            ),
        ),
        migrations.CreateModel(
            name="RiotGearProtection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=1, verbose_name="value")),
                (
                    "protection_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.protectiontype",
                    ),
                ),
                (
                    "riot_gear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.riotgear",
                    ),
                ),
            ],
            options={
                "verbose_name": "riot gear protection",
                "verbose_name_plural": "riot gear protections",
            },
        ),
    ]
