# Generated by Django 5.1.2 on 2024-11-02 17:53

from django.db import migrations


def forwards_func(apps, schema_editor):
    RiotGear = apps.get_model("armory", "RiotGear")
    RiotGear.objects.filter(name_de="Buckler").update(
        shield_cover=6,
    )
    RiotGear.objects.filter(name_de="Rundschild").update(
        shield_cover=5,
    )
    RiotGear.objects.filter(name_de="Turmschild").update(
        shield_cover=4,
    )
    RiotGear.objects.filter(id=36).update(
        shield_cover=4,
    )  # Personenschutzschild XUR-ASIA

    RiotGear.objects.filter(id=35).update(
        shield_cover=5,
    )  # Personenschutzschild Standard

    RiotGear.objects.filter(name_de="Schild des Drachenkönigs").update(
        shield_cover=4,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0022_remove_riotgear_protection_ballistic_and_more"),
    ]

    operations = [migrations.RunPython(forwards_func)]
