# Generated by Django 5.1.2 on 2024-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0024_alter_protectiontype_icon_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riotgear",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="price"
            ),
        ),
    ]
