# Generated by Django 5.1.2 on 2024-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0026_auto_20241103_2317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencymapunit",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("text-white", "White"),
                    ("text-info", "Info"),
                    ("text-success", "Success"),
                    ("text-primary", "Primary"),
                    ("text-secondary", "Secondary"),
                    ("text-warning", "Warning"),
                    ("text-danger", "Danger"),
                ],
                default="text-warning",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="protectiontype",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("text-white", "White"),
                    ("text-info", "Info"),
                    ("text-success", "Success"),
                    ("text-primary", "Primary"),
                    ("text-secondary", "Secondary"),
                    ("text-warning", "Warning"),
                    ("text-danger", "Danger"),
                ],
                default="text-primary",
                max_length=30,
            ),
        ),
    ]
