# Generated by Django 5.1.7 on 2025-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0027_alter_currencymapunit_color_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("c", "Common"),
                    ("u", "Uncommon"),
                    ("r", "Rare"),
                    ("1", "Unique"),
                    ("l", "Legendary"),
                ],
                default="c",
                max_length=1,
                verbose_name="rarity",
            ),
        ),
    ]
