# Generated by Django 5.1.7 on 2025-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0028_item_rarity"),
        ("rules", "0009_extension_exclusive_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AlterField(
            model_name="riotgear",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AlterField(
            model_name="weaponmodification",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
    ]
