# Generated by Django 5.2.4 on 2025-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0032_alter_riotgearmodifier_aspect"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protectiontype",
            options={
                "ordering": ("-ordering",),
                "verbose_name": "protection type",
                "verbose_name_plural": "protection types",
            },
        ),
        migrations.AddField(
            model_name="protectiontype",
            name="letter_de",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="letter"
            ),
        ),
        migrations.AddField(
            model_name="protectiontype",
            name="letter_en",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="letter"
            ),
        ),
    ]
