# Generated by Django 5.2.7 on 2025-11-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0033_alter_protectiontype_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBrewingEffect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "item brewing effect",
                "verbose_name_plural": "item brewing effects",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="brewing_effect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.itembrewingeffect",
            ),
        ),
    ]
