# Generated by Django 5.2.7 on 2025-11-19 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0034_itembrewingeffect_item_brewing_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponmodification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weaponmodification",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
    ]
