# Generated by Django 6.0.6 on 2026-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0036_alter_item_image_alter_weapon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="essential_load",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="essential load"
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="essential_properties",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential properties",
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="essential_protection",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="essential protection",
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="essential_sealing",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="essential sealing"
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="essential_damage",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="essential damage"
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="essential_enabled",
            field=models.BooleanField(default=False, verbose_name="essential enabled"),
        ),
        migrations.AddField(
            model_name="weapon",
            name="essential_grip",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="essential grip"
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="essential_properties",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="essential properties",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="essential_range",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="essential range"
            ),
        ),
    ]
