# Generated by Django 6.0.6 on 2026-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0037_item_essential_enabled_riotgear_essential_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
    ]
