# Generated by Codex on 2026-06-28

from django.db import migrations, models


def copy_brewing_effect_to_brewing_effects(apps, schema_editor):
    Item = apps.get_model("armory", "Item")

    for item in Item.objects.exclude(brewing_effect__isnull=True):
        item.brewing_effects.add(item.brewing_effect_id)


def copy_brewing_effects_to_brewing_effect(apps, schema_editor):
    Item = apps.get_model("armory", "Item")

    for item in Item.objects.prefetch_related("brewing_effects"):
        brewing_effect = item.brewing_effects.first()
        if brewing_effect is not None:
            item.brewing_effect_id = brewing_effect.id
            item.save(update_fields=["brewing_effect"])


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0038_item_image_focal_x_item_image_focal_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="brewing_effects",
            field=models.ManyToManyField(
                blank=True,
                to="armory.itembrewingeffect",
                verbose_name="brewing effects",
            ),
        ),
        migrations.RunPython(
            copy_brewing_effect_to_brewing_effects,
            copy_brewing_effects_to_brewing_effect,
        ),
    ]
