# Generated by Django 4.1.10 on 2023-08-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0004_worldbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="book_claim_de",
            field=models.CharField(
                default="", max_length=80, verbose_name="book claim"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worldbook",
            name="book_claim_en",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="book claim"
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="book_heading_font",
            field=models.CharField(
                default="Oxanium", max_length=20, verbose_name="book heading font"
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="book_title_de",
            field=models.CharField(
                default="", max_length=80, verbose_name="book title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worldbook",
            name="book_title_en",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="book title"
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="book_title_image",
            field=models.ImageField(
                default="",
                upload_to="rulebook_title_images",
                verbose_name="book title image",
            ),
            preserve_default=False,
        ),
    ]
