# Generated by Django 4.1.10 on 2023-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0005_worldbook_book_claim_de_worldbook_book_claim_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="book_body_font",
            field=models.CharField(
                choices=[
                    ("Oxanium", "Oxanium"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("Baskervville", "Baskervville"),
                ],
                default="Baskervville",
                max_length=20,
                verbose_name="book body font",
            ),
        ),
        migrations.AlterField(
            model_name="worldbook",
            name="book_heading_font",
            field=models.CharField(
                choices=[
                    ("Oxanium", "Oxanium"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("Baskervville", "Baskervville"),
                ],
                default="Oxanium",
                max_length=20,
                verbose_name="book heading font",
            ),
        ),
        migrations.AlterField(
            model_name="worldbook",
            name="book_title_image",
            field=models.ImageField(
                choices=[
                    ("Oxanium", "Oxanium"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("Baskervville", "Baskervville"),
                ],
                upload_to="rulebook_title_images",
                verbose_name="book title image",
            ),
        ),
    ]
