# Generated by Django 4.1.10 on 2023-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0006_worldbook_book_body_font_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldbook",
            name="book_title_image",
            field=models.ImageField(
                upload_to="rulebook_title_images", verbose_name="book title image"
            ),
        ),
    ]
