# Generated by Django 4.1.10 on 2023-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0007_alter_worldbook_book_title_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldbook",
            name="book_title_image",
            field=models.ImageField(
                max_length=256,
                upload_to="rulebook_title_images",
                verbose_name="book title image",
            ),
        ),
    ]
