# Generated by Django 4.1.10 on 2023-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0008_alter_worldbook_book_title_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="identifier",
            field=models.CharField(
                default="", max_length=40, verbose_name="identifier"
            ),
            preserve_default=False,
        ),
    ]
