# Generated by Django 5.2.1 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0010_alter_chapter_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldbook",
            name="book_body_font",
            field=models.CharField(
                choices=[
                    ("Oxanium", "Oxanium"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("Baskervville", "Libre Baskerville"),
                ],
                default="Baskervville",
                max_length=20,
                verbose_name="book body font",
            ),
        ),
        migrations.AlterField(
            model_name="worldbook",
            name="book_heading_font",
            field=models.CharField(
                choices=[
                    ("Oxanium", "Oxanium"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("Baskervville", "Libre Baskerville"),
                ],
                default="Oxanium",
                max_length=20,
                verbose_name="book heading font",
            ),
        ),
    ]
