# Generated by Django 5.2.3 on 2025-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0012_alter_worldbook_book_body_font_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="disabled_chapters",
            field=models.ManyToManyField(blank=True, to="rulebook.chapter"),
        ),
    ]
