# Generated by Django 5.2.3 on 2025-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0013_worldbook_disabled_chapters"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="book_website",
            field=models.URLField(blank=True, null=True, verbose_name="book website"),
        ),
    ]
