# Generated by Django 5.2.3 on 2025-06-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0014_worldbook_book_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worldbook",
            name="pdf_de",
        ),
        migrations.RemoveField(
            model_name="worldbook",
            name="pdf_en",
        ),
        migrations.AddField(
            model_name="worldbook",
            name="pdf_online_de",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rulebook_pdf",
                verbose_name="PDF german online",
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="pdf_online_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rulebook_pdf",
                verbose_name="PDF english online",
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="pdf_print_de",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rulebook_pdf",
                verbose_name="PDF german print",
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="pdf_print_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rulebook_pdf",
                verbose_name="PDF english print",
            ),
        ),
    ]
