# Generated by Django 5.2.3 on 2025-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0015_remove_worldbook_pdf_de_remove_worldbook_pdf_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="preview_image_de",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="rulebook_preview_images",
                verbose_name="preview image german",
            ),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="preview_image_en",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="rulebook_preview_images",
                verbose_name="preview image english",
            ),
        ),
        migrations.AlterField(
            model_name="worldbook",
            name="book_body_font",
            field=models.CharField(
                choices=[
                    ("Carolingia", "Carolingia"),
                    ("Gutenberg Textura", "Gutenberg Textura"),
                    ("Mokgech", "Mokgech"),
                    ("Morris Roman", "Morris Roman"),
                    ("Noto Sans", "Noto Sans"),
                    ("Oxanium", "Oxanium"),
                    ("Playfair Display", "Playfair Display"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("gameicons", "gameicons"),
                ],
                default="Playfair Display",
                max_length=20,
                verbose_name="book body font",
            ),
        ),
    ]
