# Generated by Django 5.2.7 on 2025-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0016_worldbook_preview_image_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldbook",
            name="book_body_font",
            field=models.CharField(
                choices=[
                    ("Carolingia", "Carolingia"),
                    ("Gutenberg Textura", "Gutenberg Textura"),
                    ("Mokgech", "Mokgech"),
                    ("Morris Roman", "Morris Roman"),
                    ("Noto Sans", "Noto Sans"),
                    ("Oxanium", "Oxanium"),
                    ("Playfair Display", "Playfair Display"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("gameicons", "gameicons"),
                    ("metamorphousregular", "metamorphousregular"),
                ],
                default="Playfair Display",
                max_length=20,
                verbose_name="book body font",
            ),
        ),
        migrations.AlterField(
            model_name="worldbook",
            name="book_heading_font",
            field=models.CharField(
                choices=[
                    ("Carolingia", "Carolingia"),
                    ("Gutenberg Textura", "Gutenberg Textura"),
                    ("Mokgech", "Mokgech"),
                    ("Morris Roman", "Morris Roman"),
                    ("Noto Sans", "Noto Sans"),
                    ("Oxanium", "Oxanium"),
                    ("Playfair Display", "Playfair Display"),
                    ("UnifrakturMaguntia", "UnifrakturMaguntia"),
                    ("gameicons", "gameicons"),
                    ("metamorphousregular", "metamorphousregular"),
                ],
                default="Oxanium",
                max_length=20,
                verbose_name="book heading font",
            ),
        ),
    ]
