# Generated by Django 5.2.9 on 2025-12-23 14:32

import phasesix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0017_alter_worldbook_book_body_font_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
    ]
