# Generated by Django 5.2.9 on 2026-01-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0018_alter_book_image_alter_chapter_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldbook",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="worldbook",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
