# Generated by Django 5.2.9 on 2026-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulebook", "0019_worldbook_description_de_worldbook_description_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worldbook",
            options={"ordering": ("ordering",)},
        ),
        migrations.AddField(
            model_name="worldbook",
            name="ordering",
            field=models.IntegerField(default=0, verbose_name="ordering"),
        ),
    ]
