# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0001_initial"),
        ("worlds", "0001_initial"),
        ("campaigns", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("ordering", models.IntegerField(default=10, verbose_name="ordering")),
            ],
            options={
                "verbose_name": "entity category",
                "verbose_name_plural": "entity categories",
                "ordering": ("-ordering",),
            },
        ),
        migrations.CreateModel(
            name="PriestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("grace_cost", models.IntegerField(verbose_name="grace cost")),
                ("name_de", models.CharField(max_length=80, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="name"
                    ),
                ),
                ("rules_de", models.TextField(verbose_name="rules")),
                (
                    "rules_en",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "quote",
                    models.TextField(blank=True, null=True, verbose_name="quote"),
                ),
                (
                    "quote_author",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="quote author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "priest action",
                "verbose_name_plural": "priest actions",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PriestActionRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_roll_name_de",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="custom roll name",
                    ),
                ),
                (
                    "custom_roll_name_en",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="custom roll name",
                    ),
                ),
                (
                    "custom_roll_dice",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="custom roll dice",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.attribute",
                        verbose_name="attribute for usage",
                    ),
                ),
                (
                    "priest_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pantheon.priestaction",
                        verbose_name="priest action",
                    ),
                ),
            ],
            options={
                "verbose_name": "priest action roll",
                "verbose_name_plural": "priest action rolls",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general item and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("name_de", models.CharField(max_length=256, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "short_name_de",
                    models.CharField(
                        blank=True,
                        help_text="An optional short name for selections.",
                        max_length=90,
                        null=True,
                        verbose_name="short name",
                    ),
                ),
                (
                    "short_name_en",
                    models.CharField(
                        blank=True,
                        help_text="An optional short name for selections.",
                        max_length=90,
                        null=True,
                        verbose_name="short name",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="entity_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                ("ordering", models.IntegerField(default=100, verbose_name="ordering")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pantheon.entitycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                ("extensions", models.ManyToManyField(to="rules.extension")),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "wiki_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worlds.wikipage",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
            },
        ),
    ]
