# Generated by Django 4.1.6 on 2023-02-13 19:15
from django.core.files.base import ContentFile
from django.db import migrations

from rules.templatetags.rules_extras import replace_tags, urpg_markup, to_first_linebreak


def forward(apps, schema_editor):
    WikiPage = apps.get_model('worlds', 'WikiPage')
    EntityCategory = apps.get_model('pantheon', 'EntityCategory')

    for wiki_category in WikiPage.objects.get(id=1).wikipage_set.all():
        entity_category = EntityCategory.objects.create(
            name_de=wiki_category.name_de,
            name_en=wiki_category.name_en,
            description_de=to_first_linebreak(wiki_category.text_de),
            description_en=to_first_linebreak(wiki_category.text_en),
            ordering=wiki_category.ordering
        )
        for page in wiki_category.wikipage_set.all():
            entity = entity_category.entity_set.create(
                name_de=page.name_de,
                name_en=page.name_en,
                short_name_de=page.short_name_de,
                short_name_en=page.short_name_en,
                description_de=to_first_linebreak(page.text_de),
                description_en=to_first_linebreak(page.text_en),
                ordering=page.ordering
            )
            image_copy = ContentFile(page.image.read())
            new_name = page.image.name.split('/')[-1]
            entity.image.save(new_name, image_copy)
            entity.extensions.add(page.world.extension)


class Migration(migrations.Migration):
    dependencies = [
        ('pantheon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
