# Generated by Django 4.1.7 on 2023-05-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0033_alter_wikipagegamevalues_options"),
        ("pantheon", "0002_auto_20230213_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="wiki_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="worlds.wikipage",
            ),
        ),
    ]
