# Generated by Django 4.1.7 on 2023-05-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0022_campaign_foe_visibility_and_more"),
        ("pantheon", "0003_entity_wiki_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "is_homebrew",
                    models.BooleanField(default=False, verbose_name="is homebrew"),
                ),
                (
                    "keep_as_homebrew",
                    models.BooleanField(
                        default=False,
                        help_text="This was not accepted as general spell and is kept as homebrew.",
                        verbose_name="keep as homebrew",
                    ),
                ),
                ("favor_cost", models.IntegerField(verbose_name="favor cost")),
                ("name_de", models.CharField(max_length=80, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="name"
                    ),
                ),
                ("rules_de", models.TextField(verbose_name="rules")),
                (
                    "rules_en",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "quote",
                    models.TextField(blank=True, null=True, verbose_name="quote"),
                ),
                (
                    "quote_author",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="quote author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "homebrew_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "priest action",
                "verbose_name_plural": "priest actions",
                "ordering": ("id",),
            },
        ),
    ]
