# Generated by Django 4.1.11 on 2023-09-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pantheon", "0003_entity_homebrew_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priestaction",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[("lesser", "Lesser"), ("higher", "Higher")],
                max_length=6,
                null=True,
                verbose_name="work type",
            ),
        ),
    ]
