# Generated by Django 4.1.7 on 2023-05-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0095_templatemodifier_unlocks_spell_origin"),
        ("pantheon", "0004_priestaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriestActionRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_roll_name",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="custom roll name",
                    ),
                ),
                (
                    "custom_roll_dice",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="custom roll dice",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.attribute",
                        verbose_name="attribute for usage",
                    ),
                ),
                (
                    "priest_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pantheon.priestaction",
                        verbose_name="priest action",
                    ),
                ),
            ],
        ),
    ]
