# Generated by Django 4.1.7 on 2023-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pantheon", "0005_priestactionroll"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priestactionroll",
            options={
                "verbose_name": "priest action roll",
                "verbose_name_plural": "priest action rolls",
            },
        ),
        migrations.RenameField(
            model_name="priestactionroll",
            old_name="custom_roll_name",
            new_name="custom_roll_name_de",
        ),
        migrations.AddField(
            model_name="priestactionroll",
            name="custom_roll_name_en",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="custom roll name"
            ),
        ),
    ]
