# Generated by Django 4.1.7 on 2023-06-02 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pantheon", "0006_alter_priestactionroll_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="priestaction",
            old_name="favor_cost",
            new_name="grace_cost",
        ),
    ]
