# Generated by Django 4.1.7 on 2023-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pantheon", "0007_rename_favor_cost_priestaction_grace_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priestaction",
            name="grace_cost",
            field=models.IntegerField(verbose_name="grace cost"),
        ),
    ]
