# Generated by Django 4.2.6 on 2023-10-17 10:18

from django.db import migrations


def forward(apps, schema_editor):
    PriestAction = apps.get_model('pantheon', 'PriestAction')
    PriestAction.objects.filter(id=3).update(work_type='lesser')
    PriestAction.objects.filter(id=4).update(work_type='higher')


class Migration(migrations.Migration):

    dependencies = [
        ('pantheon', '0004_priestaction_work_type'),
    ]

    operations = [
            migrations.RunPython(forward),
    ]
