# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rules", "0001_initial"),
        ("horror", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quirkmodifier",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.attribute",
                verbose_name="attribute",
            ),
        ),
        migrations.AddField(
            model_name="quirkmodifier",
            name="quirk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="horror.quirk",
                verbose_name="quirk",
            ),
        ),
        migrations.AddField(
            model_name="quirkmodifier",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.skill",
                verbose_name="skill",
            ),
        ),
        migrations.AddField(
            model_name="quirk",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="horror.quirkcategory",
                verbose_name="category",
            ),
        ),
    ]
