# Generated by Django 4.1.10 on 2023-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horror", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quirkmodifier",
            name="aspect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base_max_health", "max health"),
                    ("base_max_arcana", "max arcana"),
                    ("base_spell_points", "spell points"),
                    ("base_actions", "actions"),
                    ("base_minimum_roll", "minimum roll"),
                    ("base_rest_minimum_roll", "rest minimum roll"),
                    ("base_protection", "protection"),
                    ("base_evasion", "evasion"),
                    ("base_bonus_dice", "bonus dice"),
                    ("base_destiny_dice", "destiny dice"),
                    ("base_rerolls", "rerolls"),
                    ("base_max_stress", "max stress"),
                ],
                max_length=40,
                null=True,
                verbose_name="aspect",
            ),
        ),
    ]
