# Generated by Django 3.2.9 on 2022-01-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0010_alter_quirkmodifier_attribute'),
    ]

    operations = [
        migrations.RenameField('QuirkModifier', 'attribute', 'aspect'),
        migrations.RenameField('QuirkModifier', 'attribute_modifier', 'aspect_modifier'),
    ]
