# Generated by Django 3.2.9 on 2022-01-03 23:38

from django.db import migrations


def assign_attributes(apps, schema_editor):
    QuirkModifier = apps.get_model('horror', 'QuirkModifier')
    Attribute = apps.get_model('rules', 'Attribute')

    for q in QuirkModifier.objects.all():
        aspect_name = q.aspect.replace('base_', '') if q.aspect is not None else ''
        try:
            attribute = Attribute.objects.get(name_en__iexact=aspect_name)
        except Attribute.DoesNotExist:
            pass
        else:
            q.attribute = attribute
            q.attribute_modifier = q.aspect_modifier
            q.aspect = None
            q.aspect_modifier = None
            q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0013_auto_20220103_2327'),
    ]

    operations = [
        migrations.RunPython(assign_attributes)
    ]
