# Generated by Django 3.2.9 on 2022-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0015_alter_quirkmodifier_aspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='quirk',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='quirk',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
