# Generated by Django 3.2.12 on 2022-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0016_auto_20220113_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='quirk',
            name='rules_de',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
        migrations.AddField(
            model_name='quirk',
            name='rules_en',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
    ]
