# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("armory", "0002_initial"),
        ("rules", "0001_initial"),
        ("worlds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foe",
            name="wiki_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="worlds.wikipage"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="currency_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.currencymap"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="epoch",
            field=models.ForeignKey(
                limit_choices_to={"is_mandatory": False, "type": "e"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_epoch_set",
                to="rules.extension",
                verbose_name="Epoch",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="extensions",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_mandatory": False, "type": "x"},
                to="rules.extension",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="forbidden_templates",
            field=models.ManyToManyField(blank=True, to="rules.template"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="world",
            field=models.ForeignKey(
                limit_choices_to={"is_mandatory": False, "type": "w"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_world_set",
                to="rules.extension",
                verbose_name="World",
            ),
        ),
    ]
