# Generated by Django 4.1.9 on 2023-07-05 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
