# Generated by Django 3.2.7 on 2021-11-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0036_currencymap_currencymapunit'),
        ('campaigns', '0005_auto_20210726_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='currency_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armory.currencymap'),
        ),
    ]
