# Generated by Django 3.2.9 on 2021-12-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='roll',
            name='header',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='roll',
            name='roll_string',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='roll string'),
        ),
    ]
