# Generated by Django 3.2.9 on 2022-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20211222_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discord_webhook_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='discord webhook url'),
        ),
    ]
