# Generated by Django 3.2.9 on 2022-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0078_auto_20220107_2205'),
        ('campaigns', '0009_campaign_discord_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text="Create a discord webhook and paste it's url here to display dice results.", max_length=256, null=True, verbose_name='discord webhook url'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='forbidden_templates',
            field=models.ManyToManyField(blank=True, to='rules.Template'),
        ),
    ]
