# Generated by Django 3.2.12 on 2022-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0050_auto_20220103_1217'),
        ('campaigns', '0010_auto_20220109_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character'),
        ),
    ]
