# Generated by Django 3.2.12 on 2022-04-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_roll_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='character_visibility',
            field=models.CharField(choices=[('G', 'GM Only'), ('A', 'All')], default='G', max_length=1, verbose_name='character visibility'),
        ),
    ]
