# Generated by Django 3.2.12 on 2022-04-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_auto_20220410_1919'),
        ('campaigns', '0012_campaign_character_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='epoch',
            field=models.ForeignKey(limit_choices_to={'is_epoch': True, 'is_mandatory': False}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_epoch_set', to='rules.extension', verbose_name='Epoch'),
        ),
    ]
