# Generated by Django 3.2.15 on 2022-09-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0084_remove_extension_is_epoch'),
        ('campaigns', '0013_alter_campaign_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='epoch',
            field=models.ForeignKey(limit_choices_to={'is_mandatory': False, 'type': 'e'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_epoch_set', to='rules.extension', verbose_name='Epoch'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='extensions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_mandatory': False, 'type': 'x'}, to='rules.Extension'),
        ),
    ]
