# Generated by Django 3.2.15 on 2022-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20220908_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
