# Generated by Django 3.2.15 on 2022-10-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0086_alter_extension_fixed_epoch'),
        ('campaigns', '0015_alter_roll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='world',
            field=models.ForeignKey(default=16, limit_choices_to={'is_mandatory': False, 'type': 'w'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_world_set', to='rules.extension', verbose_name='World'),
            preserve_default=False,
        ),
    ]
