# Generated by Django 4.1.3 on 2022-12-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0054_item_is_container'),
        ('campaigns', '0016_campaign_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='currency_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armory.currencymap'),
            preserve_default=False,
        ),
    ]
