# Generated by Django 4.1.3 on 2022-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_campaign_currency_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='seed_money',
            field=models.IntegerField(default=2000, verbose_name='seed money'),
        ),
    ]
