# Generated by Django 4.1.3 on 2022-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaign_seed_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='starting_template_points',
            field=models.IntegerField(default=0, verbose_name='additional starting career points'),
        ),
    ]
