# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_campaign_starting_template_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='backdrop_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='campaign_backdrop_images', verbose_name='backdrop image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='campaign_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='campaign_handouts', verbose_name='image'),
        ),
    ]
