# Generated by Django 4.1.7 on 2023-05-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0032_wikipagegamevalues_stress_test_failed_stress_and_more"),
        (
            "campaigns",
            "0020_alter_campaign_backdrop_image_alter_campaign_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Foe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "wiki_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worlds.wikipage",
                    ),
                ),
            ],
        ),
    ]
