# Generated by Django 4.1.7 on 2023-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0021_foe"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="foe_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="A",
                max_length=1,
                verbose_name="foe visibility",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="character_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="A",
                max_length=1,
                verbose_name="character visibility",
            ),
        ),
    ]
