# Generated by Django 4.1.7 on 2023-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0022_campaign_foe_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="game_log_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="A",
                max_length=1,
                verbose_name="game log visibility",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="npc_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="A",
                max_length=1,
                verbose_name="npc visibility",
            ),
        ),
    ]
