# Generated by Django 4.1.7 on 2023-05-30 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0023_campaign_game_log_visibility_campaign_npc_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roll",
            options={"ordering": ("-created_at",)},
        ),
    ]
