# Generated by Django 4.1.7 on 2023-06-08 13:03

from django.db import migrations


def forward(apps, schema_editor):
    Roll = apps.get_model('campaigns', 'Roll')
    for roll in Roll.objects.all():
        if "+" in roll.roll_string:
            roll.modifier = int(roll.roll_string.split("+")[-1])
        if "-" in roll.roll_string:
            try:
                roll.modifier = -1 * int(roll.roll_string.split("-")[-1])
            except ValueError:
                roll.modifier = 0
        roll.save()

    for roll in Roll.objects.all():
        results = [int(v) for v in roll.results_csv.strip().split(',') if v]
        roll.result_sum = sum(results) + roll.modifier
        roll.save()


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0025_roll_minimum_roll_roll_modifier_roll_result_sum"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
