# Generated by Django 4.1.7 on 2023-06-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0026_auto_20230608_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roll",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
    ]
