# Generated by Django 4.1.7 on 2023-06-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0071_remove_character_favor_character_grace"),
        ("campaigns", "0027_alter_roll_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roll",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="roll",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.character",
            ),
        ),
    ]
