# Generated by Django 4.1.7 on 2023-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0029_remove_roll_result_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="roll",
            name="crit_count",
            field=models.IntegerField(default=0, verbose_name="crit count"),
        ),
        migrations.AddField(
            model_name="roll",
            name="crit_sum",
            field=models.IntegerField(default=0, verbose_name="crit sum"),
        ),
        migrations.AddField(
            model_name="roll",
            name="exploded_dice_count",
            field=models.IntegerField(default=0, verbose_name="exploded dice count"),
        ),
        migrations.AddField(
            model_name="roll",
            name="exploded_dice_sum",
            field=models.IntegerField(default=0, verbose_name="exploded dice sum"),
        ),
        migrations.AddField(
            model_name="roll",
            name="fails_count",
            field=models.IntegerField(default=0, verbose_name="fails count"),
        ),
        migrations.AddField(
            model_name="roll",
            name="fails_sum",
            field=models.IntegerField(default=0, verbose_name="fails sum"),
        ),
        migrations.AddField(
            model_name="roll",
            name="highest_single_roll",
            field=models.IntegerField(default=0, verbose_name="highest single roll"),
        ),
        migrations.AddField(
            model_name="roll",
            name="successes_count",
            field=models.IntegerField(default=0, verbose_name="successes count"),
        ),
        migrations.AddField(
            model_name="roll",
            name="successes_sum",
            field=models.IntegerField(default=0, verbose_name="successes sum"),
        ),
        migrations.AddField(
            model_name="roll",
            name="total_sum",
            field=models.IntegerField(default=0, verbose_name="total sum"),
        ),
    ]
