# Generated by Django 4.1.7 on 2023-06-08 20:20

from django.db import migrations


def forward(apps, schema_editor):
    Roll = apps.get_model('campaigns', 'Roll')
    for roll in Roll.objects.all():
        dice_list = [int(v) for v in roll.results_csv.strip().split(',') if v]
        successes = [v for v in dice_list if v >= roll.minimum_roll]
        fails = [v for v in dice_list if v < roll.minimum_roll]
        exploded = [v for v in dice_list if v >= 6]
        crits = [v for v in dice_list if v >= 11]

        roll.crit_count = len(crits)
        roll.crit_sum = sum(crits)
        roll.exploded_dice_count = len(exploded)
        roll.exploded_dice_sum = sum(exploded)
        roll.highest_single_roll = max(dice_list, default=0)
        roll.successes_count = len(successes)
        roll.successes_sum = sum(successes)
        roll.fails_count = len(fails)
        roll.fails_sum = sum(fails)
        roll.total_sum = sum(dice_list) + roll.modifier
        roll.save()


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0030_roll_exploded_dice_count_roll_fails_count_and_more"),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
