# Generated by Django 2.0.5 on 2018-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0001_initial'),
    ]

    operations = [
    ]
