# Generated by Django 4.1.10 on 2023-08-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0002_world_foe_overview_wiki_page"),
        ("rulebook", "0003_book_homebrew_character_chapter_homebrew_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_de",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rulebook_pdf",
                        verbose_name="PDF german",
                    ),
                ),
                (
                    "pdf_en",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rulebook_pdf",
                        verbose_name="PDF english",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rulebook.book"
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worlds.world"
                    ),
                ),
            ],
        ),
    ]
