# Generated by Django 3.2.15 on 2022-08-14 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0013_alter_campaign_epoch'),
        ('rulebook', '0007_auto_20191115_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homebrew', models.BooleanField(default=False, verbose_name='is homebrew')),
                ('keep_as_homebrew', models.BooleanField(default=False, help_text='This was not accepted as general spell and is kept as homebrew.', verbose_name='keep as homebrew')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('name_de', models.CharField(max_length=40, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='name')),
                ('number', models.IntegerField(default=1, verbose_name='number')),
                ('fa_icon_class', models.CharField(max_length=32, verbose_name='fa icon class')),
                ('text_de', models.TextField(verbose_name='text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('homebrew_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='homebrew campaign')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homebrew', models.BooleanField(default=False, verbose_name='is homebrew')),
                ('keep_as_homebrew', models.BooleanField(default=False, help_text='This was not accepted as general spell and is kept as homebrew.', verbose_name='keep as homebrew')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images', verbose_name='image')),
                ('image_copyright', models.CharField(blank=True, max_length=40, null=True, verbose_name='image copyright')),
                ('image_copyright_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='image copyright url')),
                ('name_de', models.CharField(max_length=40, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='name')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('homebrew_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='homebrew campaign')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('ordering',),
            },
        ),
    ]
