# Generated by Django 3.2.15 on 2022-09-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0008_book_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_images', verbose_name='image'),
        ),
    ]
