# Generated by Django 4.1.10 on 2023-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0009_chapter_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="identifier",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="identifier"
            ),
        ),
    ]
