# Generated by Django 3.2.15 on 2022-09-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0009_auto_20220901_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rulebook.book'),
            preserve_default=False,
        ),
    ]
