# Generated by Django 4.1.3 on 2022-12-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0010_chapter_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='rules_file_de',
            field=models.FileField(blank=True, null=True, upload_to='rulebook/', verbose_name='rules file'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='rules_file_en',
            field=models.FileField(blank=True, null=True, upload_to='rulebook/', verbose_name='rules file'),
        ),
    ]
