# Generated by Django 4.1.3 on 2022-12-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0011_chapter_rules_file_de_chapter_rules_file_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='text_en',
        ),
    ]
