# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0012_remove_chapter_text_de_remove_chapter_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='book_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='chapter_images', verbose_name='image'),
        ),
    ]
