# Generated by Django 5.1.7 on 2025-04-01 20:18

import json

from django.db import migrations


def forwards_func(apps, schema_editor):
    SocketLocation = apps.get_model("body_modifications", "SocketLocation")
    BodyModificationType = apps.get_model("body_modifications", "BodyModificationType")
    BodyModification = apps.get_model("body_modifications", "BodyModification")

    rarity_mapping = {
        "common": "c",
        "uncommon": "u",
        "rare": "r",
        "legendary": "l",
        "unique": "1",
    }

    locations = {
        "head": SocketLocation.objects.create(name_en="Head", name_de="Kopf"),
        "torso": SocketLocation.objects.create(name_en="Torso", name_de="Torso"),
        "left_arm": SocketLocation.objects.create(
            name_en="Left Arm", name_de="Linker Arm"
        ),
        "right_arm": SocketLocation.objects.create(
            name_en="Right Arm", name_de="Rechter Arm"
        ),
        "left_leg": SocketLocation.objects.create(
            name_en="Left Leg", name_de="Linkes Bein"
        ),
        "right_leg": SocketLocation.objects.create(
            name_en="Right Leg", name_de="Rechtes Bein"
        ),
    }

    types = {
        "generators": BodyModificationType.objects.create(
            name_en="Generators", name_de="Generatoren"
        ),
        "weapons": BodyModificationType.objects.create(
            name_en="Weapons", name_de="Waffen"
        ),
        "senses": BodyModificationType.objects.create(
            name_en="Senses", name_de="Sinne"
        ),
        "limbs": BodyModificationType.objects.create(
            name_en="Artificial Limbs", name_de="Künstliche Gliedmaßen"
        ),
        "protection": BodyModificationType.objects.create(
            name_en="Protection", name_de="Schutz"
        ),
        "enhancements": BodyModificationType.objects.create(
            name_en="Enhancements", name_de="Verbesserungen"
        ),
    }

    data_sets = [json.loads(get_generators()), json.loads(get_consumers())]
    for data in data_sets:
        for obj in data:
            body_modification = BodyModification.objects.create(
                name_en=obj["name_en"],
                name_de=obj["name_de"],
                description_en=obj["description_en"],
                description_de=obj["description_de"],
                price=obj["price"],
                rarity=rarity_mapping[obj["rarity"]],
                bio_strain=obj["bio_strain"],
                energy_consumption_ma=obj["energy_consumption_ma"],
                type=types[obj["type"]],
            )
            for location, amount in obj["locations"]:
                body_modification.bodymodificationsocketlocation_set.create(
                    socket_location=locations[location],
                    socket_amount=amount,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0003_alter_bodymodification_name_de_and_more"),
    ]

    operations = [migrations.RunPython(forwards_func)]


def get_generators():
    return """
    [
  {
    "price": 800,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 0,
    "energy_consumption_ma": -2,
    "name_de": "Solarkopfhaut",
    "name_en": "Solar Skin",
    "description_de": "Eine künstliche Hautschicht, die Sonnenlicht in Energie umwandelt.",
    "description_en": "An artificial skin layer that converts sunlight into energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 3000,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -8,
    "name_de": "Kinetischer Generator",
    "name_en": "Kinetic Generator",
    "description_de": "Ein Implantat, das Bewegungsenergie in elektrische Energie umwandelt.",
    "description_en": "An implant that converts kinetic energy into electrical energy.",
    "locations": [
      ["left_arm", 1],
      ["right_arm", 1]
    ]
  },
  {
    "price": 1800,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -6,
    "name_de": "Thermo-Konverter",
    "name_en": "Thermo Converter",
    "description_de": "Ein Implantat, das Körperwärme in nutzbare Energie umwandelt.",
    "description_en": "An implant that converts body heat into usable energy.",
    "locations": [
      ["torso", 3]
    ]
  },
  {
    "price": 1700,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -4,
    "name_de": "Atemluft-Turbine",
    "name_en": "Breath Turbine",
    "description_de": "Ein Gerät, das die kinetische Energie des Atmens in elektrische Energie umwandelt.",
    "description_en": "A device that converts the kinetic energy of breathing into electrical energy.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 1200,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -3,
    "name_de": "Elektrostatischer Sammler",
    "name_en": "Electrostatic Collector",
    "description_de": "Ein Gerät, das statische Elektrizität aus der Umgebung sammelt und speichert.",
    "description_en": "A device that collects and stores static electricity from the environment.",
    "locations": [
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 1900,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -5,
    "name_de": "Piezoelektrischer Geh-Generator",
    "name_en": "Piezoelectric Walk Generator",
    "description_de": "Ein Implantat in den Füßen, das Druck in elektrische Energie umwandelt.",
    "description_en": "An implant in feet that converts pressure into electrical energy.",
    "locations": [
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 2100,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -6,
    "name_de": "Magnetfeld-Harvester",
    "name_en": "Magnetic Field Harvester",
    "description_de": "Ein Implantat, das Energie aus natürlichen oder künstlichen Magnetfeldern gewinnt.",
    "description_en": "An implant that harvests energy from natural or artificial magnetic fields.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 2600,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 4,
    "energy_consumption_ma": -9,
    "name_de": "Blutfluss-Dynamo",
    "name_en": "Blood Flow Dynamo",
    "description_de": "Ein kleiner Generator, der durch den Blutfluss angetrieben wird.",
    "description_en": "A small generator driven by blood flow.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 1000,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -4,
    "name_de": "Schallwellen-Konverter",
    "name_en": "Sound Wave Converter",
    "description_de": "Ein Implantat, das Umgebungsgeräusche in Energie umwandelt.",
    "description_en": "An implant that converts ambient noise into energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -7,
    "name_de": "Photosynthese-Haut",
    "name_en": "Photosynthetic Skin",
    "description_de": "Eine künstliche Haut, die wie Pflanzen Licht in Energie umwandelt.",
    "description_en": "An artificial skin that converts light into energy like plants.",
    "locations": [
      ["left_arm", 1],
      ["right_arm", 1]
    ]
  },
  {
    "price": 2000,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -5,
    "name_de": "Muskelkontraktions-Generator",
    "name_en": "Muscle Contraction Generator",
    "description_de": "Ein Implantat, das Energie aus Muskelbewegungen gewinnt.",
    "description_en": "An implant that generates energy from muscle movements.",
    "locations": [
      ["left_arm", 1],
      ["right_arm", 1],
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 1700,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -3,
    "name_de": "Feuchtigkeits-Kondensator",
    "name_en": "Moisture Condenser",
    "description_de": "Ein Gerät, das Feuchtigkeit aus der Luft kondensiert und in Energie umwandelt.",
    "description_en": "A device that condenses moisture from the air and converts it into energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -6,
    "name_de": "Radiofrequenz-Empfänger",
    "name_en": "Radio Frequency Receiver",
    "description_de": "Ein Implantat, das Energie aus Radiofrequenzwellen sammelt.",
    "description_en": "An implant that collects energy from radio frequency waves.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2400,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 4,
    "energy_consumption_ma": -8,
    "name_de": "Chemischer Energie-Extraktor",
    "name_en": "Chemical Energy Extractor",
    "description_de": "Ein Implantat, das chemische Reaktionen im Körper nutzt, um Energie zu erzeugen.",
    "description_en": "An implant that uses chemical reactions in the body to generate energy.",
    "locations": [
      ["torso", 2]
    ]
  },
  {
    "price": 1500,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -2,
    "name_de": "Mikrowellen-Absorber",
    "name_en": "Microwave Absorber",
    "description_de": "Sammelt Energie aus Mikrowellenstrahlung.",
    "description_en": "Collects energy from microwave radiation.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 1600,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -3,
    "name_de": "Ultraschall-Generator",
    "name_en": "Ultrasound Generator",
    "description_de": "Wandelt Ultraschallwellen in Energie um.",
    "description_en": "Converts ultrasound waves into energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 1700,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -2,
    "name_de": "Ionen-Kollektor",
    "name_en": "Ion Collector",
    "description_de": "Sammelt Ionen aus der Luft und wandelt sie in Energie um.",
    "description_en": "Collects ions from the air and converts them into energy.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 1800,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -4,
    "name_de": "Elektromagnetischer Induktor",
    "name_en": "Electromagnetic Inductor",
    "description_de": "Nutzt elektromagnetische Felder zur Energiegewinnung.",
    "description_en": "Uses electromagnetic fields to generate energy.",
    "locations": [
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 1900,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -6,
    "name_de": "Infrarot-Absorber",
    "name_en": "Infrared Absorber",
    "description_de": "Wandelt Infrarotstrahlung in elektrische Energie um.",
    "description_en": "Converts infrared radiation into electrical energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 1500,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -1,
    "name_de": "Piezoelektrischer Hautsensor",
    "name_en": "Piezoelectric Skin Sensor",
    "description_de": "Erzeugt Energie durch Druck auf die Haut.",
    "description_en": "Generates energy through pressure on the skin.",
    "locations": [
      ["left_arm", 1],
      ["right_arm", 1],
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -10,
    "name_de": "Bio-Brennstoffzelle",
    "name_en": "Bio Fuel Cell",
    "description_de": "Nutzt organische Stoffe im Körper zur Energieerzeugung.",
    "description_en": "Uses organic substances in the body to generate energy.",
    "locations": [
      ["torso", 3]
    ]
  },
  {
    "price": 1600,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -3,
    "name_de": "Akustischer Resonator",
    "name_en": "Acoustic Resonator",
    "description_de": "Wandelt Schallwellen in elektrische Energie um.",
    "description_en": "Converts sound waves into electrical energy.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -8,
    "name_de": "Thermoelektrischer Generator",
    "name_en": "Thermoelectric Generator",
    "description_de": "Nutzt Temperaturunterschiede zur Energiegewinnung.",
    "description_en": "Uses temperature differences to generate energy.",
    "locations": [
      ["head", 1],
      ["left_arm", 1],
      ["right_arm", 1],
      ["left_leg", 1],
      ["right_leg", 1]
    ]
  },
  {
    "price": 1500,
    "rarity": "common",
    "type": "generators",
    "bio_strain": 1,
    "energy_consumption_ma": -2,
    "name_de": "Elektrostatischer Luftfilter",
    "name_en": "Electrostatic Air Filter",
    "description_de": "Sammelt elektrische Ladungen aus der Luft.",
    "description_en": "Collects electrical charges from the air.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2300,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -5,
    "name_de": "Nanobot-Energieernter",
    "name_en": "Nanobot Energy Harvester",
    "description_de": "Kleine Roboter, die Energie aus der Umgebung sammeln.",
    "description_en": "Small robots that harvest energy from the environment.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 2000,
    "rarity": "uncommon",
    "type": "generators",
    "bio_strain": 2,
    "energy_consumption_ma": -4,
    "name_de": "Osmotischer Druckgenerator",
    "name_en": "Osmotic Pressure Generator",
    "description_de": "Nutzt osmotischen Druck zur Energieerzeugung.",
    "description_en": "Uses osmotic pressure to generate energy.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 2100,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -7,
    "name_de": "Photovoltaischer Hautfleck",
    "name_en": "Photovoltaic Skin Patch",
    "description_de": "Kleine photovoltaische Zellen, die Licht in Energie umwandeln.",
    "description_en": "Small photovoltaic cells that convert light into energy.",
    "locations": [
      ["left_arm", 1],
      ["right_arm", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 3,
    "energy_consumption_ma": -6,
    "name_de": "Elektrolytischer Zellgenerator",
    "name_en": "Electrolytic Cell Generator",
    "description_de": "Nutzt elektrolytische Prozesse zur Energiegewinnung.",
    "description_en": "Uses electrolytic processes to generate energy.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "rare",
    "type": "generators",
    "bio_strain": 4,
    "energy_consumption_ma": -9,
    "name_de": "Quantenpunkt-Solarzelle",
    "name_en": "Quantum Dot Solar Cell",
    "description_de": "Hochmoderne Solarzellen, die Licht effizient in Energie umwandeln.",
    "description_en": "Advanced solar cells that efficiently convert light into energy.",
    "locations": [
      ["head", 1]
    ]
  }
]"""


def get_consumers():
    return """
    [
  {
    "price": 2000,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Cyberaugen I",
    "name_en": "Cybereyes I",
    "description_de": "Ersetzt die natürlichen Augen und bietet verbesserte Sicht.",
    "description_en": "Replaces natural eyes and offers enhanced vision.",
    "rule_de": "Erhöht die Wahrnehmung um +1.",
    "rule_en": "Increases perception by +1.",
    "locations": [
     ["head", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "uncommon",
    "type": "weapons",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Smartlink",
    "name_en": "Smartlink",
    "description_de": "Verbindet Waffen direkt mit dem Gehirn für bessere Zielgenauigkeit.",
    "description_en": "Connects weapons directly to the brain for improved accuracy.",
    "rule_de": "Gewährt einen Bonus von +1 auf Schusswaffen-Fertigkeiten.",
    "rule_en": "Grants a +1 bonus to firearm skills.",
    "locations": [
        ["left_arm", 1],
        ["right_arm", 1]
    ]
  },
  {
    "price": 3000,
    "rarity": "rare",
    "type": "limbs",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cyberarm",
    "name_en": "Cyberarm",
    "description_de": "Ein künstlicher Arm mit erhöhter Stärke und Funktionalität.",
    "description_en": "An artificial arm with increased strength and functionality.",
    "rule_de": "Erhöht die Stärke um +2.",
    "rule_en": "Increases strength by +2.",
    "locations": [
       ["left_arm", 3],
       ["right_arm", 3]
    ]
  },
  {
    "price": 2200,
    "rarity": "uncommon",
    "type": "protection",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Dermalpanzer",
    "name_en": "Dermal Armor",
    "description_de": "Eine Hautverstärkung, die zusätzlichen Schutz bietet.",
    "description_en": "Skin reinforcement that provides additional protection.",
    "rule_de": "Erhöht die Rüstung um +1.",
    "rule_en": "Increases armor by +1.",
    "locations": [
      ["torso", 1]
    ]
  },
  {
    "price": 2800,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Neuralverstärker",
    "name_en": "Neural Enhancer",
    "description_de": "Verbessert die Reaktionszeit und kognitiven Fähigkeiten.",
    "description_en": "Enhances reaction time and cognitive abilities.",
    "rule_de": "Erhöht die Initiative um +1.",
    "rule_en": "Increases initiative by +1.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 1500,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Audioverstärker",
    "name_en": "Audio Enhancer",
    "description_de": "Verbessert das Gehör und ermöglicht das Erkennen von Geräuschen aus größerer Entfernung.",
    "description_en": "Enhances hearing and allows detection of sounds from greater distances.",
    "rule_de": "Erhöht die Wahrnehmung um +1 bei Hörtests.",
    "rule_en": "Increases perception by +1 on hearing tests.",
    "locations": [
      ["head", 1]
    ]
  },
  {
    "price": 3500,
    "rarity": "rare",
    "type": "limbs",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cyberbeine",
    "name_en": "Cyberlegs",
    "description_de": "Künstliche Beine, die Geschwindigkeit und Sprungkraft erhöhen.",
    "description_en": "Artificial legs that increase speed and jumping power.",
    "rule_de": "Erhöht die Bewegungsrate um +2.",
    "rule_en": "Increases movement rate by +2.",
    "locations": [
     ["left_leg", 1],
     ["right_leg", 1]
    ]   
  },
  {
    "price": 2000,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Subdermale Panzerung",
    "name_en": "Subdermal Armor",
    "description_de": "Panzerung unter der Haut, die vor physischen Angriffen schützt.",
    "description_en": "Armor under the skin that protects against physical attacks.",
    "rule_de": "Erhöht die Rüstung um +2.",
    "rule_en": "Increases armor by +2.",
    "locations": [
     ["torso", 2]
    ]
  },
  {
    "price": 2700,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Reflexverstärker",
    "name_en": "Reflex Booster",
    "description_de": "Verbessert die Reflexe und Reaktionszeiten.",
    "description_en": "Enhances reflexes and reaction times.",
    "rule_de": "Erhöht die Initiative um +2.",
    "rule_en": "Increases initiative by +2.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 1800,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Datenbuchse",
    "name_en": "Data Jack",
    "description_de": "Ermöglicht die direkte Verbindung mit Computersystemen.",
    "description_en": "Allows direct connection to computer systems.",
    "rule_de": "Ermöglicht direkten Datenzugriff und -transfer.",
    "rule_en": "Allows direct data access and transfer.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2400,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Knochenverstärkung",
    "name_en": "Bone Lacing",
    "description_de": "Verstärkt die Knochenstruktur und erhöht die Widerstandsfähigkeit.",
    "description_en": "Reinforces bone structure and increases durability.",
    "rule_de": "Erhöht die Rüstung um +1.",
    "rule_en": "Increases armor by +1.",
    "locations": [
        ["torso", 2]
    ]
  },
  {
    "price": 3000,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Muskelverstärker",
    "name_en": "Muscle Augmentation",
    "description_de": "Erhöht die Muskelkraft und Ausdauer.",
    "description_en": "Increases muscle strength and endurance.",
    "rule_de": "Erhöht die Stärke um +2.",
    "rule_en": "Increases strength by +2.",
    "locations": [
        ["left_arm", 2],
        ["right_arm", 2],
        ["left_leg", 2],
        ["left_leg", 2]
    ]
  },
  {
    "price": 2100,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Infrarotsicht",
    "name_en": "Infrared Vision",
    "description_de": "Ermöglicht das Sehen von Wärmesignaturen.",
    "description_en": "Allows seeing heat signatures.",
    "rule_de": "Erhöht die Wahrnehmung in Dunkelheit oder bei Rauch.",
    "rule_en": "Increases perception in darkness or smoke.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2600,
    "rarity": "uncommon",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Giftfilter",
    "name_en": "Toxin Filter",
    "description_de": "Filtert Gifte und Schadstoffe aus dem Körper.",
    "description_en": "Filters toxins and pollutants from the body.",
    "rule_de": "Erhöht den Widerstand gegen Gifte.",
    "rule_en": "Increases resistance to toxins.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 3300,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cyberherz",
    "name_en": "Cyberheart",
    "description_de": "Ein künstliches Herz, das die Ausdauer und Leistung verbessert.",
    "description_en": "An artificial heart that improves endurance and performance.",
    "rule_de": "Erhöht die Ausdauer um +2.",
    "rule_en": "Increases endurance by +2.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 1900,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Nachtsicht",
    "name_en": "Night Vision",
    "description_de": "Verbessert die Sicht bei schlechten Lichtverhältnissen.",
    "description_en": "Enhances vision in low-light conditions.",
    "rule_de": "Erhöht die Wahrnehmung in Dunkelheit.",
    "rule_en": "Increases perception in darkness.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "uncommon",
    "bio_strain": 2,
    "type": "enhancements",
    "energy_consumption_ma": 1,
    "name_de": "Schalldämpfer",
    "name_en": "Sound Dampener",
    "description_de": "Reduziert die Lautstärke von Schritten und Bewegungen.",
    "description_en": "Reduces the noise from footsteps and movements.",
    "rule_de": "Erhöht die Heimlichkeit um +1.",
    "rule_en": "Increases stealth by +1.",
    "locations": [
        ["left_leg", 1],
        ["right_leg", 1]
    ]
  },
  {
    "price": 3100,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Cyberlunge",
    "name_en": "Cyberlung",
    "description_de": "Eine künstliche Lunge, die die Sauerstoffaufnahme verbessert.",
    "description_en": "An artificial lung that improves oxygen intake.",
    "rule_de": "Erhöht die Ausdauer um +2.",
    "rule_en": "Increases endurance by +2.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 2000,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Gedächtnisverstärker",
    "name_en": "Memory Enhancer",
    "description_de": "Verbessert das Gedächtnis und die Erinnerungsfähigkeit.",
    "description_en": "Enhances memory and recall ability.",
    "rule_de": "Erhöht die Intelligenz um +1.",
    "rule_en": "Increases intelligence by +1.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 3400,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cybergehirn",
    "name_en": "Cyberbrain",
    "description_de": "Ein künstliches Gehirn, das kognitive Fähigkeiten verbessert.",
    "description_en": "An artificial brain that enhances cognitive abilities.",
    "rule_de": "Erhöht die Intelligenz um +2.",
    "rule_en": "Increases intelligence by +2.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Tarnhaut",
    "name_en": "Chameleon Skin",
    "description_de": "Verändert die Hautfarbe, um sich an die Umgebung anzupassen.",
    "description_en": "Changes skin color to blend with the environment.",
    "rule_de": "Erhöht die Heimlichkeit um +2.",
    "rule_en": "Increases stealth by +2.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 2900,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Adrenalinpumpe",
    "name_en": "Adrenal Pump",
    "description_de": "Erhöht kurzfristig die Kampffähigkeiten.",
    "description_en": "Temporarily boosts combat abilities.",
    "rule_de": "Erhöht die Stärke und Geschwindigkeit für kurze Zeit.",
    "rule_en": "Increases strength and speed for a short duration.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3600,
    "rarity": "rare",
    "type": "senses",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cyberaugen II",
    "name_en": "Cybereyes II",
    "description_de": "Verbesserte Version der Cyberaugen mit zusätzlichen Funktionen.",
    "description_en": "Enhanced version of cybereyes with additional features.",
    "rule_de": "Erhöht die Wahrnehmung um +2.",
    "rule_en": "Increases perception by +2.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2300,
    "rarity": "common",
    "type": "weapons",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Giftklauen",
    "name_en": "Poison Claws",
    "description_de": "Klauen, die mit einem tödlichen Gift überzogen sind.",
    "description_en": "Claws coated with a deadly poison.",
    "rule_de": "Fügt zusätzlichen Giftschaden hinzu.",
    "rule_en": "Adds additional poison damage.",
    "locations": [
        ["left_arm", 1],
        ["right_arm", 1]
    ]
  },
  {
    "price": 3700,
    "rarity": "rare",
    "type": "weapons",
    "bio_strain": 4,
    "energy_consumption_ma": 9,
    "name_de": "Plasmawerfer",
    "name_en": "Plasma Cannon",
    "description_de": "Ein implantierter Werfer, der Plasma-Projektile abfeuert.",
    "description_en": "An implanted launcher that fires plasma projectiles.",
    "rule_de": "Fügt Plasmaschaden hinzu.",
    "rule_en": "Adds plasma damage.",
    "locations": [
        ["left_arm", 1],
        ["right_arm", 1]
    ]
  },
  {
    "price": 3100,
    "rarity": "uncommon",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Energieschild",
    "name_en": "Energy Shield",
    "description_de": "Ein Schild, das Energieangriffe abwehrt.",
    "description_en": "A shield that deflects energy attacks.",
    "rule_de": "Erhöht den Widerstand gegen Energieangriffe.",
    "rule_en": "Increases resistance to energy attacks.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3800,
    "rarity": "rare",
    "type": "protection",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Nanobot-Heiler",
    "name_en": "Nanobot Healer",
    "description_de": "Nanobots, die Verletzungen schnell heilen.",
    "description_en": "Nanobots that quickly heal injuries.",
    "rule_de": "Erhöht die Heilungsrate.",
    "rule_en": "Increases healing rate.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Tarnfeldgenerator",
    "name_en": "Stealth Field Generator",
    "description_de": "Erzeugt ein Feld, das den Träger unsichtbar macht.",
    "description_en": "Generates a field that makes the wearer invisible.",
    "rule_de": "Erhöht die Heimlichkeit erheblich.",
    "rule_en": "Significantly increases stealth.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3200,
    "rarity": "uncommon",
    "type": "limbs",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Kybernetischer Schwanz",
    "name_en": "Cybernetic Tail",
    "description_de": "Ein Schwanz, der als zusätzliche Gliedmaße verwendet werden kann.",
    "description_en": "A tail that can be used as an additional limb.",
    "rule_de": "Erhöht die Geschicklichkeit um +1.",
    "rule_en": "Increases agility by +1.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3900,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Neuralinterface",
    "name_en": "Neural Interface",
    "description_de": "Ermöglicht die direkte Kommunikation mit Maschinen.",
    "description_en": "Allows direct communication with machines.",
    "rule_de": "Erhöht die Fähigkeit, Maschinen zu kontrollieren.",
    "rule_en": "Increases the ability to control machines.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 2600,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Infrarot-Scanner",
    "name_en": "Infrared Scanner",
    "description_de": "Ermöglicht das Scannen von Wärmesignaturen.",
    "description_en": "Allows scanning of heat signatures.",
    "rule_de": "Erhöht die Wahrnehmung in Dunkelheit oder bei Rauch.",
    "rule_en": "Increases perception in darkness or smoke.",
    "locations": [
        ["head", 1]
    ]
  },
  {
    "price": 3300,
    "rarity": "uncommon",
    "type": "weapons",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Elektro-Peitsche",
    "name_en": "Electro-Whip",
    "description_de": "Eine Peitsche, die elektrische Schocks verursacht.",
    "description_en": "A whip that delivers electric shocks.",
    "rule_de": "Fügt zusätzlichen Elektroschaden hinzu.",
    "rule_en": "Adds additional electric damage.",
    "locations": [
        ["right_arm", 1],
        ["left_arm", 1]
    ]
  },
  {
    "price": 4000,
    "rarity": "rare",
    "type": "weapons",
    "bio_strain": 4,
    "energy_consumption_ma": 3,
    "name_de": "Cyber-Kralle",
    "name_en": "Cyber Claw",
    "description_de": "Eine kraftvolle Kralle, die physischen Schaden verursacht.",
    "description_en": "A powerful claw that deals physical damage.",
    "rule_de": "Fügt zusätzlichen physischen Schaden hinzu.",
    "rule_en": "Adds additional physical damage.",
    "locations": [
        ["right_arm", 1],
        ["left_arm", 1]
    ]
  },
  {
    "price": 2700,
    "rarity": "common",
    "bio_strain": 2,
    "type": "weapons",
    "energy_consumption_ma": 1,
    "name_de": "Schallwerfer",
    "name_en": "Sonic Launcher",
    "description_de": "Eine Vorichtung in der Hand, die Schallwellen erzeugt, um Feinde zu betäuben.",
    "description_en": "A hand implant that generates sound waves to stun enemies.",
    "rule_de": "Betäubt Feinde für kurze Zeit.",
    "rule_en": "Stuns enemies for a short duration.",
    "locations": [
        ["right_arm", 1],
        ["left_arm", 1]
    ]
  },
  {
    "price": 3400,
    "rarity": "uncommon",
    "type": "weapons",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "EMP-Generator",
    "name_en": "EMP Generator",
    "description_de": "Erzeugt einen elektromagnetischen Impuls, der elektronische Geräte deaktiviert.",
    "description_en": "Generates an electromagnetic pulse that disables electronic devices.",
    "rule_de": "Deaktiviert elektronische Geräte in der Nähe.",
    "rule_en": "Disables nearby electronic devices.",
    "locations": [
        ["right_arm", 1],
        ["left_arm", 1]
    ]
  },
  {
    "price": 4100,
    "rarity": "rare",
    "bio_strain": 4,
    "type": "weapons",
    "energy_consumption_ma": 3,
    "name_de": "Nanobot-Schwarm",
    "name_en": "Nanobot Swarm",
    "description_de": "Ein Schwarm von Nanobots, der Feinde angreift.",
    "description_en": "A swarm of nanobots that attacks enemies.",
    "rule_de": "Fügt kontinuierlichen Schaden hinzu.",
    "rule_en": "Adds continuous damage.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3500,
    "rarity": "uncommon",
    "type": "weapons",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Plasma-Klinge",
    "name_en": "Plasma Blade",
    "description_de": "Eine Klinge, die mit Plasma überzogen ist.",
    "description_en": "A blade coated with plasma.",
    "rule_de": "Fügt zusätzlichen Plasmaschaden hinzu.",
    "rule_en": "Adds additional plasma damage.",
    "locations": [
        ["right_arm", 1],
        ["left_arm", 1]
    ]
  },
  {
    "price": 4200,
    "rarity": "rare",
    "bio_strain": 4,
    "type": "enhancements",
    "energy_consumption_ma": 3,
    "name_de": "Gravitations-Manipulator",
    "name_en": "Gravity Manipulator",
    "description_de": "Ermöglicht die Manipulation der Schwerkraft.",
    "description_en": "Allows manipulation of gravity.",
    "rule_de": "Erhöht die Sprungweite und -höhe.",
    "rule_en": "Increases jump distance and height.",
    "locations": [
        ["torso", 1]
    ]
  },

  {
    "price": 2500,
    "rarity": "uncommon",
    "bio_strain": 2,
    "type": "enhancements",
    "energy_consumption_ma": 1,
    "name_de": "Bio-Lumineszenz-Tattoos",
    "name_en": "Bio-Luminescent Tattoos",
    "description_de": "Tattoos, die Licht abgeben und in verschiedenen Farben leuchten können.",
    "description_en": "Tattoos that emit light and can glow in different colors.",
    "rule_de": "Erhöht die Sichtbarkeit in dunklen Umgebungen.",
    "rule_en": "Increases visibility in dark environments.",
    "locations": [
        ["torso", 1]
    ]
  },
  {
    "price": 3000,
    "rarity": "rare",
    "bio_strain": 3,
    "type": "senses",
    "energy_consumption_ma": 2,
    "name_de": "Sonar-Implantat",
    "name_en": "Sonar Implant",
    "description_de": "Ermöglicht die Wahrnehmung der Umgebung durch Schallwellen.",
    "description_en": "Allows perception of the environment through sound waves.",
    "rule_de": "Erhöht die Wahrnehmung unter Wasser oder in dunklen Räumen.",
    "rule_en": "Increases perception underwater or in dark rooms.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "common",
    "bio_strain": 1,
    "type": "senses",
    "energy_consumption_ma": 1,
    "name_de": "Emotionssensor",
    "name_en": "Emotion Sensor",
    "description_de": "Ermöglicht das Erkennen und Analysieren von Emotionen bei anderen Personen.",
    "description_en": "Allows detection and analysis of emotions in others.",
    "rule_de": "Erhöht die soziale Wahrnehmung.",
    "rule_en": "Increases social perception.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2800,
    "rarity": "uncommon",
    "bio_strain": 2,
    "type": "enhancements",
    "energy_consumption_ma": 1,
    "name_de": "Holografischer Projektor",
    "name_en": "Holographic Projector",
    "description_de": "Projiziert Hologramme zur Kommunikation oder Ablenkung.",
    "description_en": "Projects holograms for communication or distraction.",
    "rule_de": "Erhöht die Fähigkeit, Informationen zu präsentieren oder Feinde zu täuschen.",
    "rule_en": "Increases the ability to present information or deceive enemies.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3500,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Nano-Reparatur-Bots",
    "name_en": "Nano Repair Bots",
    "description_de": "Kleine Bots, die kleinere Verletzungen oder Schäden sofort reparieren.",
    "description_en": "Small bots that instantly repair minor injuries or damage.",
    "rule_de": "Erhöht die Heilungsrate bei kleineren Verletzungen.",
    "rule_en": "Increases healing rate for minor injuries.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 1900,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Chemischer Analysator",
    "name_en": "Chemical Analyzer",
    "description_de": "Ermöglicht die Analyse von Chemikalien und Giften in der Umgebung.",
    "description_en": "Allows analysis of chemicals and toxins in the environment.",
    "rule_de": "Erhöht die Fähigkeit, Gefahren in der Umgebung zu erkennen.",
    "rule_en": "Increases the ability to detect environmental hazards.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3200,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Magnetische Greifhaken",
    "name_en": "Magnetic Grapples",
    "description_de": "Ermöglicht das Klettern an metallischen Oberflächen.",
    "description_en": "Allows climbing on metallic surfaces.",
    "rule_de": "Erhöht die Kletterfähigkeit an bestimmten Oberflächen.",
    "rule_en": "Increases climbing ability on specific surfaces.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 2]
    ]
  },
  {
    "price": 3800,
    "rarity": "rare",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Elektrostatische Barriere",
    "name_en": "Electrostatic Barrier",
    "description_de": "Erzeugt eine Barriere, die elektrische Angriffe abwehrt.",
    "description_en": "Creates a barrier that deflects electrical attacks.",
    "rule_de": "Erhöht den Widerstand gegen elektrische Angriffe.",
    "rule_en": "Increases resistance to electrical attacks.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 2400,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Thermoregulator",
    "name_en": "Thermoregulator",
    "description_de": "Hält die Körpertemperatur konstant, unabhängig von der Umgebung.",
    "description_en": "Keeps body temperature constant regardless of the environment.",
    "rule_de": "Erhöht den Widerstand gegen extreme Temperaturen.",
    "rule_en": "Increases resistance to extreme temperatures.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 3000,
    "rarity": "uncommon",
    "type": "protection",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Chamäleon-Haut",
    "name_en": "Chameleon Skin",
    "description_de": "Passt die Hautfarbe an die Umgebung an, um sich zu tarnen.",
    "description_en": "Adapts skin color to the environment for camouflage.",
    "rule_de": "Erhöht die Heimlichkeit in natürlichen Umgebungen.",
    "rule_en": "Increases stealth in natural environments.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 3600,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Neuro-Stimulator",
    "name_en": "Neuro Stimulator",
    "description_de": "Erhöht die kognitiven Fähigkeiten und Reaktionszeiten.",
    "description_en": "Enhances cognitive abilities and reaction times.",
    "rule_de": "Erhöht die Intelligenz und Initiative.",
    "rule_en": "Increases intelligence and initiative.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2100,
    "rarity": "common",
    "type": "senses",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Ultraschall-Ortung",
    "name_en": "Ultrasonic Locator",
    "description_de": "Ermöglicht die Ortung von Objekten und Personen durch Ultraschall.",
    "description_en": "Allows location of objects and people through ultrasound.",
    "rule_de": "Erhöht die Wahrnehmung in dunklen oder verrauchten Umgebungen.",
    "rule_en": "Increases perception in dark or smoky environments.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2700,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Elektro-Muskelstimulator",
    "name_en": "Electro-Muscle Stimulator",
    "description_de": "Erhöht die Muskelkraft und Ausdauer durch elektrische Stimulation.",
    "description_en": "Increases muscle strength and endurance through electrical stimulation.",
    "rule_de": "Erhöht die Stärke und Ausdauer.",
    "rule_en": "Increases strength and endurance.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1],
       ["left_leg", 1],
       ["right_leg", 1]
    ]
  },
  {
    "price": 3400,
    "rarity": "rare",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Photonen-Schild",
    "name_en": "Photon Shield",
    "description_de": "Erzeugt ein Schild, das Licht und Laserstrahlen abwehrt.",
    "description_en": "Creates a shield that deflects light and laser beams.",
    "rule_de": "Erhöht den Widerstand gegen Licht- und Laserangriffe.",
    "rule_en": "Increases resistance to light and laser attacks.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 2000,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Bio-Feedback-Sensor",
    "name_en": "Bio-Feedback Sensor",
    "description_de": "Überwacht die Vitalwerte und warnt vor gesundheitlichen Problemen.",
    "description_en": "Monitors vital signs and alerts to health issues.",
    "rule_de": "Erhöht die Überlebensfähigkeit durch frühzeitige Warnungen.",
    "rule_en": "Increases survivability through early warnings.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2900,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Quanten-Verschränkung",
    "name_en": "Quantum Entanglement",
    "description_de": "Ermöglicht die Kommunikation über große Entfernungen ohne Verzögerung.",
    "description_en": "Allows communication over large distances without delay.",
    "rule_de": "Erhöht die Kommunikationsfähigkeiten in abgelegenen Gebieten.",
    "rule_en": "Increases communication capabilities in remote areas.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3700,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Nano-Konstruktions-Bots",
    "name_en": "Nano Construction Bots",
    "description_de": "Kleine Bots, die Strukturen und Werkzeuge aus Rohmaterialien herstellen.",
    "description_en": "Small bots that construct structures and tools from raw materials.",
    "rule_de": "Erhöht die Fähigkeit, schnell Werkzeuge oder Unterkünfte zu bauen.",
    "rule_en": "Increases the ability to quickly build tools or shelters.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2300,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Elektro-Magnetische Tarnung",
    "name_en": "Electromagnetic Cloaking",
    "description_de": "Macht den Träger unsichtbar für elektromagnetische Sensoren.",
    "description_en": "Makes the wearer invisible to electromagnetic sensors.",
    "rule_de": "Erhöht die Heimlichkeit gegen elektromagnetische Überwachung.",
    "rule_en": "Increases stealth against electromagnetic surveillance.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3100,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Schallwellen-Manipulator",
    "name_en": "Sonic Wave Manipulator",
    "description_de": "Ermöglicht die Manipulation von Schallwellen zur Kommunikation oder Ablenkung.",
    "description_en": "Allows manipulation of sound waves for communication or distraction.",
    "rule_de": "Erhöht die Fähigkeit, Feinde zu verwirren oder zu täuschen.",
    "rule_en": "Increases the ability to confuse or deceive enemies.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3900,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Plasma-Schneider",
    "name_en": "Plasma Cutter",
    "description_de": "Ein Werkzeug, das Plasma verwendet, um durch Materialien zu schneiden.",
    "description_en": "A tool that uses plasma to cut through materials.",
    "rule_de": "Erhöht die Fähigkeit, schnell durch Hindernisse zu schneiden.",
    "rule_en": "Increases the ability to quickly cut through obstacles.",
    "locations": [
       ["right_arm", 1],
       ["left_arm", 1]
    ]
  },
  {
    "price": 3200,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Gravitations-Stabilisator",
    "name_en": "Gravity Stabilizer",
    "description_de": "Stabilisiert den Körper in Umgebungen mit unterschiedlicher Schwerkraft.",
    "description_en": "Stabilizes the body in environments with varying gravity.",
    "rule_de": "Erhöht die Beweglichkeit in unterschiedlichen Schwerkraftbedingungen.",
    "rule_en": "Increases agility in varying gravity conditions.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 3800,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Neuro-Link-Kommunikator",
    "name_en": "Neuro-Link Communicator",
    "description_de": "Ermöglicht die direkte Kommunikation mit anderen über neurale Verbindungen.",
    "description_en": "Allows direct communication with others through neural links.",
    "rule_de": "Erhöht die Kommunikationsfähigkeiten und Sicherheit.",
    "rule_en": "Increases communication capabilities and security.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 2200,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Infrarot-Tarnung",
    "name_en": "Infrared Cloaking",
    "description_de": "Macht den Träger unsichtbar für Infrarot-Sensoren.",
    "description_en": "Makes the wearer invisible to infrared sensors.",
    "rule_de": "Erhöht die Heimlichkeit gegen Wärmebildkameras.",
    "rule_en": "Increases stealth against thermal imaging.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 2900,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Elektro-Magnetische Greifer",
    "name_en": "Electromagnetic Grippers",
    "description_de": "Ermöglicht das Greifen und Bewegen von metallischen Objekten.",
    "description_en": "Allows gripping and moving metallic objects.",
    "rule_de": "Erhöht die Fähigkeit, schwere Objekte zu bewegen.",
    "rule_en": "Increases the ability to move heavy objects.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 3600,
    "rarity": "rare",
    "type": "weapons",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Photonen-Kanone",
    "name_en": "Photon Cannon",
    "description_de": "Eine Waffe, die Photonenstrahlen abfeuert.",
    "description_en": "A weapon that fires photon beams.",
    "rule_de": "Fügt Photonenschaden hinzu.",
    "rule_en": "Adds photon damage.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 2100,
    "rarity": "common",
    "type": "protection",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Ultraschall-Heiler",
    "name_en": "Ultrasonic Healer",
    "description_de": "Nutzt Ultraschallwellen, um Verletzungen zu heilen.",
    "description_en": "Uses ultrasonic waves to heal injuries.",
    "rule_de": "Erhöht die Heilungsrate.",
    "rule_en": "Increases healing rate.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 3500,
    "rarity": "rare",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Nano-Reparatur-Schaum",
    "name_en": "Nano Repair Foam",
    "description_de": "Ein Schaum, der kleinere Verletzungen sofort repariert.",
    "description_en": "A foam that instantly repairs minor injuries.",
    "rule_de": "Erhöht die Heilungsrate bei kleineren Verletzungen.",
    "rule_en": "Increases healing rate for minor injuries.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 3000,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Elektro-Magnetische Wurfanker",
    "name_en": "Electromagnetic Grappling Hook",
    "description_de": "Ein Wurfanker, der sich an metallischen Oberflächen festhält.",
    "description_en": "A grappling hook that attaches to metallic surfaces.",
    "rule_de": "Erhöht die Kletterfähigkeit an bestimmten Oberflächen.",
    "rule_en": "Increases climbing ability on specific surfaces.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 2400,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Ultraschall-Scanner",
    "name_en": "Ultrasonic Scanner",
    "description_de": "Ermöglicht das Scannen von Objekten und Personen durch Ultraschall.",
    "description_en": "Allows scanning of objects and people through ultrasound.",
    "rule_de": "Erhöht die Wahrnehmung in dunklen oder verrauchten Umgebungen.",
    "rule_en": "Increases perception in dark or smoky environments.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 3100,
    "rarity": "uncommon",
    "type": "weapons",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Elektro-Magnetische Klinge",
    "name_en": "Electromagnetic Blade",
    "description_de": "Eine Klinge, die durch elektromagnetische Felder verstärkt wird.",
    "description_en": "A blade enhanced by electromagnetic fields.",
    "rule_de": "Fügt zusätzlichen physischen Schaden hinzu.",
    "rule_en": "Adds additional physical damage.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  },
  {
    "price": 3800,
    "rarity": "rare",
    "type": "protection",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Plasma-Schild",
    "name_en": "Plasma Shield",
    "description_de": "Erzeugt ein Schild, das physische und Energieangriffe abwehrt.",
    "description_en": "Creates a shield that deflects physical and energy attacks.",
    "rule_de": "Erhöht den Widerstand gegen physische und Energieangriffe.",
    "rule_en": "Increases resistance to physical and energy attacks.",
    "locations": [
       ["torso", 1]
    ]
  },
  {
    "price": 2500,
    "rarity": "common",
    "type": "enhancements",
    "bio_strain": 1,
    "energy_consumption_ma": 1,
    "name_de": "Holografischer Kommunikator",
    "name_en": "Holographic Communicator",
    "description_de": "Ermöglicht die Kommunikation über Hologramme.",
    "description_en": "Allows communication through holograms.",
    "rule_de": "Erhöht die Kommunikationsfähigkeiten und Sicherheit.",
    "rule_en": "Increases communication capabilities and security.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 3200,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Gravitations-Manipulator",
    "name_en": "Gravity Manipulator",
    "description_de": "Ermöglicht die Manipulation der Schwerkraft.",
    "description_en": "Allows manipulation of gravity.",
    "rule_de": "Erhöht die Sprungweite und -höhe.",
    "rule_en": "Increases jump distance and height.",
    "locations": [
       ["left_leg", 1],
       ["right_leg", 1]
    ]
  },
  {
    "price": 3300,
    "rarity": "uncommon",
    "type": "enhancements",
    "bio_strain": 2,
    "energy_consumption_ma": 1,
    "name_de": "Schallwellen-Manipulator",
    "name_en": "Sonic Wave Manipulator",
    "description_de": "Ermöglicht die Manipulation von Schallwellen zur Kommunikation oder Ablenkung.",
    "description_en": "Allows manipulation of sound waves for communication or distraction.",
    "rule_de": "Erhöht die Fähigkeit, Feinde zu verwirren oder zu täuschen.",
    "rule_en": "Increases the ability to confuse or deceive enemies.",
    "locations": [
       ["head", 1]
    ]
  },
  {
    "price": 4000,
    "rarity": "rare",
    "type": "enhancements",
    "bio_strain": 3,
    "energy_consumption_ma": 2,
    "name_de": "Plasma-Schneider",
    "name_en": "Plasma Cutter",
    "description_de": "Ein Werkzeug, das Plasma verwendet, um durch Materialien zu schneiden.",
    "description_en": "A tool that uses plasma to cut through materials.",
    "rule_de": "Erhöht die Fähigkeit, schnell durch Hindernisse zu schneiden.",
    "rule_en": "Increases the ability to quickly cut through obstacles.",
    "locations": [
       ["left_arm", 1],
       ["right_arm", 1]
    ]
  }
]"""
