# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("armory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "may_appear_on_start_page",
                    models.BooleanField(
                        default=False,
                        help_text="This character may appear on the anonymous start page (i.E. if it has only free images",
                        verbose_name="may appear on start page",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(blank=True, null=True, verbose_name="size"),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="weight"),
                ),
                (
                    "date_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                ("attitude", models.IntegerField(default=50, verbose_name="attitude")),
                ("grace", models.IntegerField(default=0, verbose_name="grace")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="character_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "image_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "image_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                (
                    "backdrop_image",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="character_backdrop_images",
                        verbose_name="backdrop image",
                    ),
                ),
                (
                    "backdrop_copyright",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="image copyright",
                    ),
                ),
                (
                    "backdrop_copyright_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="image copyright url",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "reputation",
                    models.IntegerField(default=0, verbose_name="reputation"),
                ),
                ("health", models.IntegerField(default=6, verbose_name="health")),
                ("boost", models.IntegerField(default=0, verbose_name="boost")),
                ("arcana", models.IntegerField(default=3, verbose_name="arcana")),
                ("stress", models.IntegerField(default=0, verbose_name="stress")),
                (
                    "bonus_dice_used",
                    models.IntegerField(default=0, verbose_name="Bonus dice used"),
                ),
                (
                    "destiny_dice_used",
                    models.IntegerField(default=0, verbose_name="Destiny dice used"),
                ),
                (
                    "rerolls_used",
                    models.IntegerField(default=0, verbose_name="Rerolls used"),
                ),
                (
                    "latest_initiative",
                    models.IntegerField(default=0, verbose_name="latest initiative"),
                ),
                (
                    "quirks_gained",
                    models.IntegerField(
                        default=0,
                        help_text="The amount of quirks gained by excess stress",
                        verbose_name="quirks gained",
                    ),
                ),
                (
                    "quirks_healed",
                    models.IntegerField(
                        default=0,
                        help_text="The amount of quirks healed by treatment.",
                        verbose_name="quirks healed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ("attribute__name_de",),
            },
        ),
        migrations.CreateModel(
            name="CharacterCurrency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="quantity")),
            ],
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "charges_used",
                    models.IntegerField(default=0, verbose_name="Charges used"),
                ),
                ("ordering", models.IntegerField(default=1, verbose_name="Ordering")),
            ],
            options={
                "ordering": ("ordering",),
            },
        ),
        migrations.CreateModel(
            name="CharacterNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="is private"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="subject"
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                ("ordering", models.IntegerField(default=1, verbose_name="ordering")),
            ],
            options={
                "ordering": ("ordering", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="CharacterRiotGear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.IntegerField(default=100, verbose_name="condition"),
                ),
            ],
            options={
                "ordering": ("riot_gear__id",),
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ("skill__name_de",),
            },
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="custom name"
                    ),
                ),
            ],
            options={
                "ordering": ("spell__id",),
            },
        ),
        migrations.CreateModel(
            name="CharacterSpellTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterStatusEffect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_value",
                    models.IntegerField(default=0, verbose_name="base value"),
                ),
            ],
            options={
                "ordering": ("status_effect__ordering",),
            },
        ),
        migrations.CreateModel(
            name="CharacterWeapon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.IntegerField(default=100)),
                (
                    "capacity_used",
                    models.IntegerField(default=0, verbose_name="capacity used"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "modifications",
                    models.ManyToManyField(to="armory.weaponmodification"),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.weapon"
                    ),
                ),
            ],
            options={
                "ordering": ("weapon__id",),
            },
        ),
        migrations.CreateModel(
            name="CharacterTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ("template__category__sort_order",),
            },
        ),
    ]
