# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0003_initial"),
        ("armory", "0002_initial"),
        ("rules", "0001_initial"),
        ("pantheon", "0001_initial"),
        ("horror", "0002_initial"),
        ("magic", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rules.template"
            ),
        ),
        migrations.AddField(
            model_name="characterstatuseffect",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characterstatuseffect",
            name="status_effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rules.statuseffect"
            ),
        ),
        migrations.AddField(
            model_name="characterspelltemplate",
            name="character_spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.characterspell",
            ),
        ),
        migrations.AddField(
            model_name="characterspelltemplate",
            name="spell_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="magic.spelltemplate"
            ),
        ),
        migrations.AddField(
            model_name="characterspell",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characterspell",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="magic.basespell"
            ),
        ),
        migrations.AddField(
            model_name="characterskill",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characterskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rules.skill"
            ),
        ),
        migrations.AddField(
            model_name="characterriotgear",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characterriotgear",
            name="riot_gear",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.riotgear"
            ),
        ),
        migrations.AddField(
            model_name="characternote",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="in_container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="characters.characteritem",
            ),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.item"
            ),
        ),
        migrations.AddField(
            model_name="charactercurrency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="charactercurrency",
            name="currency_map_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.currencymapunit"
            ),
        ),
        migrations.AddField(
            model_name="characterattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rules.attribute"
            ),
        ),
        migrations.AddField(
            model_name="characterattribute",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Characters without user will be cleaned daily.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="currency_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.currencymap",
                verbose_name="currency map",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pantheon.entity",
                verbose_name="entity",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="extensions",
            field=models.ManyToManyField(
                limit_choices_to={"is_mandatory": False}, to="rules.extension"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="lineage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.lineage",
                verbose_name="lineage",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="npc_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="npc_set",
                to="campaigns.campaign",
                verbose_name="NPC Campaign",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="quirks",
            field=models.ManyToManyField(
                blank=True, to="horror.quirk", verbose_name="quirks"
            ),
        ),
    ]
