# Generated by Django 5.1.2 on 2024-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_characterriotgearprotectionused"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterattribute",
            name="modifier",
            field=models.IntegerField(default=0, verbose_name="Modifier"),
        ),
    ]
