# Generated by Django 5.1.7 on 2025-03-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0007_alter_character_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pronoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nominative_de",
                    models.CharField(max_length=12, verbose_name="pronoun"),
                ),
                (
                    "nominative_en",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="pronoun"
                    ),
                ),
                ("dative_de", models.CharField(max_length=12, verbose_name="pronoun")),
                (
                    "dative_en",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="pronoun"
                    ),
                ),
                (
                    "possessive_de",
                    models.CharField(max_length=12, verbose_name="pronoun"),
                ),
                (
                    "possessive_en",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="pronoun"
                    ),
                ),
                (
                    "copula_verb_de",
                    models.CharField(max_length=12, verbose_name="pronoun"),
                ),
                (
                    "copula_verb_en",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="pronoun"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="pronoun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="characters.pronoun",
                verbose_name="pronoun",
            ),
        ),
    ]
