# Generated by Django 5.1.7 on 2025-03-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0011_alter_character_pronoun"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="is favorite"),
        ),
    ]
