# Generated by Django 5.1.7 on 2025-04-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0005_bodymodification_activation"),
        ("characters", "0013_alter_character_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterBodyModification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "body_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_modifications.bodymodification",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ("body_modification__rarity",),
            },
        ),
    ]
