# Generated by Django 5.1.7 on 2025-04-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_modifications", "0008_auto_20250414_1101"),
        ("characters", "0014_characterbodymodification"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterbodymodification",
            name="socket_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="body_modifications.socketlocation",
            ),
            preserve_default=False,
        ),
    ]
