# Generated by Django 5.1.7 on 2025-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0015_characterbodymodification_socket_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterbodymodification",
            name="socket_amount",
            field=models.IntegerField(default=1, verbose_name="socket amount"),
        ),
    ]
