# Generated by Django 5.1.7 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0016_characterbodymodification_socket_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterbodymodification",
            name="charges_used",
            field=models.IntegerField(default=0, verbose_name="charges used"),
        ),
    ]
