# Generated by Django 5.2.1 on 2025-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0018_characterbodymodification_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="slug",
            field=models.SlugField(default="", max_length=220, verbose_name="slug"),
            preserve_default=False,
        ),
    ]
