# Generated by Django 5.2.1 on 2025-05-15 10:15

from django.db import migrations

from worlds.unique_slugify import unique_slugify


def forwards_func(apps, schema_editor):
    Character = apps.get_model("characters", "Character")
    Campaign = apps.get_model("campaigns", "Campaign")

    for c in Character.objects.all():
        unique_slugify(c, c.name)
        c.save()

    for c in Campaign.objects.all():
        unique_slugify(c, c.name)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0019_character_slug"),
    ]

    operations = [migrations.RunPython(forwards_func)]
