# Generated by Django 5.2.1 on 2025-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0020_auto_20250515_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="slug",
            field=models.SlugField(max_length=220, unique=True, verbose_name="slug"),
        ),
    ]
