# Generated by Django 5.2.3 on 2025-06-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0020_auto_20250515_1015"),
        ("rules", "0014_template_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category__name_en": "Occupation"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ("name",),
            },
        ),
    ]
