# Generated by Django 5.2.4 on 2025-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0021_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="base_stress",
            field=models.IntegerField(default=0, verbose_name="base stress"),
        ),
    ]
