# Generated by Django 5.2.4 on 2025-07-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0022_character_base_stress"),
        ("rules", "0020_alter_foe_resistances_alter_foe_weaknesses"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterFoe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health", models.IntegerField(default=0, verbose_name="health")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
                (
                    "is_familiar",
                    models.BooleanField(default=False, verbose_name="is familiar"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "foe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.foe"
                    ),
                ),
            ],
        ),
    ]
