# Generated by Django 5.2.4 on 2025-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0023_characterfoe"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterfoe",
            name="max_health",
            field=models.IntegerField(default=0, verbose_name="max health"),
        ),
    ]
