# Generated by Django 5.2.4 on 2025-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0024_characterfoe_max_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterfoe",
            name="boost",
            field=models.IntegerField(default=0, verbose_name="boost"),
        ),
    ]
