# Generated by Django 5.2.4 on 2025-07-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0025_characterfoe_boost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterfoe",
            options={
                "ordering": ("name", "foe__name_de"),
                "verbose_name": "character foe",
                "verbose_name_plural": "character foes",
            },
        ),
    ]
