# Generated by Django on 2025-08-11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0026_alter_characterfoe_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterfoe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="character_foe_images",
                max_length=256,
                verbose_name="image",
            ),
        ),
    ]
