# Generated by Django 5.2.5 on 2025-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0027_characterfoe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterriotgear",
            name="is_equipped",
            field=models.BooleanField(default=True, verbose_name="is equipped"),
        ),
    ]
