# Generated by Django 5.2.9 on 2025-12-09 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0029_characterrecipe"),
        ("horror", "0009_quirk_created_at_quirk_modified_at"),
    ]

    def copy_quirks_forward(apps, schema_editor):
        CharacterQuirk = apps.get_model("characters", "CharacterQuirk")
        connection = schema_editor.connection
        table_names = connection.introspection.table_names()
        m2m_table = "characters_character_quirks"
        if m2m_table not in table_names:
            return
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT character_id, quirk_id FROM {m2m_table}")
            rows = cursor.fetchall()
        for character_id, quirk_id in rows:
            CharacterQuirk.objects.get_or_create(
                character_id=character_id, quirk_id=quirk_id
            )

    def copy_quirks_backward(apps, schema_editor):
        # No reverse migration: the legacy M2M table will not exist after removal.
        pass

    operations = [
        migrations.CreateModel(
            name="CharacterQuirk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "quirk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="horror.quirk"
                    ),
                ),
            ],
            options={
                "ordering": ("quirk__id",),
                "unique_together": {("character", "quirk")},
            },
        ),
        migrations.RunPython(copy_quirks_forward, copy_quirks_backward),
        migrations.RemoveField(
            model_name="character",
            name="quirks",
        ),
    ]
