# Generated by Django 5.2.9 on 2025-12-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0030_remove_character_quirks_characterquirk"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="characters.character",
                verbose_name="cloned from",
            ),
        ),
    ]
