# Generated by Django 5.2.9 on 2025-12-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0033_alter_character_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="plot_campaign",
            new_name="plot",
        ),
    ]
