# Generated by Django 5.2.9 on 2025-12-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0034_rename_plot_campaign_character_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="characters.character",
                verbose_name="cloned from",
            ),
        ),
    ]
