# Generated by Django 5.2.9 on 2025-12-31 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0035_alter_character_cloned_from"),
        ("plots", "0013_plot_campaign_plot_cloned_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plot_npc_set",
                to="plots.plot",
                verbose_name="Plot",
            ),
        ),
    ]
