# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0037_character_backdrop_image_focal_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterrecipe",
            name="prepared_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="prepared amount"),
        ),
    ]
