# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="npc",
            field=models.ManyToManyField(to="characters.character"),
        ),
        migrations.AddField(
            model_name="roll",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="roll",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.character",
            ),
        ),
        migrations.AddField(
            model_name="handout",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaigns.scene"
            ),
        ),
        migrations.AddField(
            model_name="foe",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaigns.campaign"
            ),
        ),
    ]
