# Generated by Django 5.0.6 on 2024-07-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="may_appear_on_start_page",
            field=models.BooleanField(
                default=False,
                help_text="This campaign may appear on the anonymous start page (i.E. if it has only free images",
                verbose_name="may appear on start page",
            ),
        ),
    ]
