# Generated by Django 5.0.6 on 2024-07-17 21:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    Campaign = apps.get_model("campaigns", "Campaign")
    Campaign.objects.filter(id__in=[15, 13, 5, 4, 2]).update(
        may_appear_on_start_page=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaign_may_appear_on_start_page"),
    ]

    operations = [migrations.RunPython(forwards_func)]
