# Generated by Django 5.1.7 on 2025-03-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_auto_20240717_2137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
    ]
