# Generated by Django 5.1.7 on 2025-03-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="is favorite"),
        ),
    ]
