# Generated by Django 5.1.7 on 2025-03-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_campaign_is_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ("-is_favorite", "-created_at"),
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
    ]
