# Generated by Django 5.2 on 2025-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="discord_integration",
            field=models.BooleanField(
                default=False,
                help_text="Enables the integration with the discord bot. Requires a webhook url.",
                verbose_name="discord integration",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="roll_on_site",
            field=models.BooleanField(
                default=True,
                help_text="Shows dice results on this platform.",
                verbose_name="roll on site",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tale_spire_integration",
            field=models.BooleanField(
                default=False,
                help_text="Enables TaleSpire integration. All roll links are generated so that the TaleSpire game is accessed.",
                verbose_name="tale spire integration",
            ),
        ),
    ]
