# Generated by Django 5.2.1 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0010_campaign_discord_integration_campaign_roll_on_site_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="epoch",
            new_name="epoch_extension",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="world",
            new_name="world_extension",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="discord_integration",
            field=models.BooleanField(
                default=False,
                help_text="Enables the integration with discord. Requires a webhook url.",
                verbose_name="discord integration",
            ),
        ),
    ]
