# Generated by Django 5.2.1 on 2025-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_rename_epoch_campaign_epoch_extension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(default="", max_length=220, verbose_name="slug"),
            preserve_default=False,
        ),
    ]
