# Generated by Django 5.2.1 on 2025-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_campaign_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="act_date",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name=""
            ),
        ),
    ]
