# Generated by Django 5.2.1 on 2025-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_campaign_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(max_length=220, unique=True, verbose_name="slug"),
        ),
    ]
