# Generated by Django 5.2.1 on 2025-05-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0013_campaign_act_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="act_date",
        ),
        migrations.AddField(
            model_name="campaign",
            name="ingame_act_date",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="in game act date"
            ),
        ),
    ]
