# Generated by Django 5.2.4 on 2025-07-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_remove_campaign_act_date_campaign_ingame_act_date"),
        ("worlds", "0032_auto_20250522_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foe",
            name="wiki_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_foe_set",
                to="worlds.wikipage",
            ),
        ),
    ]
