# Generated by Django 5.2.4 on 2025-07-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_alter_foe_wiki_page"),
        ("rules", "0020_alter_foe_resistances_alter_foe_weaknesses"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignFoe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health", models.IntegerField(default=6, verbose_name="health")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "foe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.foe"
                    ),
                ),
            ],
        ),
    ]
