# Generated by Django 5.2.4 on 2025-07-14 10:13

from django.db import migrations


def forwards_func(apps, schema_editor):
    Foe = apps.get_model("campaigns", "Foe")
    RulesFoe = apps.get_model("rules", "Foe")
    CampaignFoe = apps.get_model("campaigns", "CampaignFoe")

    for foe in Foe.objects.all():
        try:
            rules_foe = RulesFoe.objects.get(name_en=foe.wiki_page.name_en)
        except RulesFoe.DoesNotExist:
            print(f"RulesFoe {foe.wiki_page.name_en} does not exist")
        else:
            CampaignFoe.objects.create(
                campaign=foe.campaign,
                foe=rules_foe,
                health=foe.wiki_page.wikipagegamevalues_set.first().health,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0016_campaignfoe"),
    ]

    operations = [migrations.RunPython(forwards_func)]
