# Generated by Django 5.2.4 on 2025-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_copy_foe_to_campaign_foe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Foe",
        ),
    ]
