# Generated by Django 5.2.9 on 2025-12-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0020_campaign_cloned_from"),
        ("plots", "0010_alter_plotelement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_set",
                to="plots.plot",
                verbose_name="plot",
            ),
        ),
    ]
