# Generated by Django 5.2.9 on 2025-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0022_alter_campaign_image_alter_handout_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="plot",
        ),
    ]
