# Generated by Django 5.2.9 on 2026-01-09 20:11

import phasesix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0023_remove_campaign_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="backdrop_image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to="campaign_backdrop_images",
                verbose_name="backdrop image",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="handout",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
    ]
