# Generated by Django 6.0.6 on 2026-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_alter_campaign_backdrop_image_alter_campaign_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ruleset',
            field=models.CharField(choices=[('phasesix', 'PhaseSix'), ('tirakan_essential', 'Tirakan Essential')], default='phasesix', max_length=24, verbose_name='ruleset'),
        ),
    ]
