# Generated by Django 6.0.6 on 2026-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_campaign_ruleset"),
        ("essential_characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="essential_npc",
            field=models.ManyToManyField(
                blank=True,
                related_name="essential_scenes",
                to="essential_characters.essentialcharacter",
                verbose_name="essential NPCs",
            ),
        ),
    ]
