# Generated by Django 6.0.6 on 2026-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_scene_essential_npc'),
        ('essential_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='essential_npc',
            field=models.ManyToManyField(blank=True, related_name='essential_scenes', to='essential_characters.essentialcharacter'),
        ),
    ]
