# Generated by Django 6.0.6 on 2026-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0026_scene_essential_npc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="character_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="G",
                max_length=1,
                verbose_name="character visibility",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="foe_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="G",
                max_length=1,
                verbose_name="foe visibility",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="game_log_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="G",
                max_length=1,
                verbose_name="game log visibility",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="npc_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("A", "All")],
                default="G",
                max_length=1,
                verbose_name="npc visibility",
            ),
        ),
    ]
