# Generated by Django 6.0.6 on 2026-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_alter_campaign_character_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='backdrop_image_focal_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='backdrop_image_focal_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
        migrations.AddField(
            model_name='handout',
            name='image_focal_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point x'),
        ),
        migrations.AddField(
            model_name='handout',
            name='image_focal_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='image focal point y'),
        ),
    ]
