# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0029_campaign_visibility_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="plot_visibility",
            field=models.CharField(
                choices=[("G", "GM Only"), ("P", "GM and Players"), ("A", "All")],
                default="G",
                max_length=1,
                verbose_name="plot visibility",
            ),
        ),
    ]
