# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0030_campaign_plot_visibility"),
        ("plots", "0021_plotelement_visibility"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaign", name="foe_visibility"),
        migrations.RemoveField(model_name="campaign", name="npc_visibility"),
        migrations.RemoveField(model_name="campaign", name="plot_visibility"),
    ]
