# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0031_remove_deprecated_plot_visibility"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaign", name="character_visibility"),
        migrations.RemoveField(model_name="campaign", name="game_log_visibility"),
    ]
