# Generated by Django 2.0.5 on 2018-05-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Ist Pflicht')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Erweiterung',
                'verbose_name_plural': 'Erweiterungen',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('add_to_all_characters', models.BooleanField(default=True, verbose_name='Zu allen Charakteren hinzufügen')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'Wissen',
                'verbose_name_plural': 'Wissen',
            },
        ),
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'shadow',
                'verbose_name_plural': 'shadows',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('add_to_all_characters', models.BooleanField(default=True, verbose_name='Zu allen Charakteren hinzufügen')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'Fertigkeit',
                'verbose_name_plural': 'Fertigkeiten',
            },
        ),
    ]
