# Generated by Django 2.0.2 on 2018-02-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='is mandatory')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('short_name_de', models.CharField(max_length=20, verbose_name='short name')),
                ('short_name_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='short name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('add_to_all_characters', models.BooleanField(default=True, verbose_name='add to all characters')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
        ),
    ]
