# Generated by Django 2.0.5 on 2018-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('cost', models.IntegerField(default=1, verbose_name='cost')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'character template',
                'verbose_name_plural': 'character templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, choices=[('intelligence', 'Intelligenz'), ('deftness', 'Geschick'), ('strength', 'Kraft'), ('attractiveness', 'Attraktivität'), ('endurance', 'Ausdauer'), ('resistance', 'Resistenz'), ('quickness', 'Schnelligkeit'), ('openness', 'Offenheit'), ('conscientiousness', 'Gewissenhaftigkeit'), ('extraversion', 'Extraversion'), ('agreeableness', 'Verträglichkeit'), ('neuroticism', 'Neurotizismus')], help_text='Leave empty if the knowledge or skill modifier is used.', max_length=40, null=True, verbose_name='attribute')),
                ('attribute_modifier', models.IntegerField(blank=True, help_text='Leave empty if the knowledge or skill modifier is used.', null=True, verbose_name='attribute_modifier')),
                ('skill_modifier', models.IntegerField(blank=True, help_text='Leave empty if the attribute or knowledge modifier is used.', null=True, verbose_name='attribute_modifier')),
                ('knowledge_modifier', models.IntegerField(blank=True, help_text='Leave empty if the skill or attribute modifier is used.', null=True, verbose_name='knowledge modifier')),
                ('knowledge', models.ForeignKey(blank=True, help_text='Leave empty if the skill or attribute modifier is used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge', verbose_name='Wissen')),
                ('skill', models.ForeignKey(blank=True, help_text='Leave empty if the attribute or knowledge modifier is used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Skill', verbose_name='Fertigkeit')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_template_requirement_set', to='rules.Template')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='template')),
            ],
        ),
    ]
