# Generated by Django 2.0.2 on 2018-02-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'gifts',
                'verbose_name': 'gift',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('add_to_all_characters', models.BooleanField(default=True, verbose_name='add to all characters')),
            ],
            options={
                'verbose_name_plural': 'knowledge',
                'verbose_name': 'knowledge',
            },
        ),
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'quirks',
                'verbose_name': 'quirk',
            },
        ),
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'extension', 'verbose_name_plural': 'extensions'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AddField(
            model_name='quirk',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='gift',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
        ),
    ]
