# Generated by Django 2.0.2 on 2018-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20180218_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'Erweiterung', 'verbose_name_plural': 'Erweiterungen'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Gabe', 'verbose_name_plural': 'Gaben'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': 'Wissen', 'verbose_name_plural': 'Wissen'},
        ),
        migrations.AlterModelOptions(
            name='quirk',
            options={'verbose_name': 'Eigenart', 'verbose_name_plural': 'Eigenarten'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Fertigkeit', 'verbose_name_plural': 'Fertigkeiten'},
        ),
        migrations.RemoveField(
            model_name='extension',
            name='short_name_de',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='short_name_en',
        ),
        migrations.AlterField(
            model_name='extension',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='Ist Pflicht'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='add_to_all_characters',
            field=models.BooleanField(default=True, verbose_name='Zu allen Charakteren hinzufügen'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='add_to_all_characters',
            field=models.BooleanField(default=True, verbose_name='Zu allen Charakteren hinzufügen'),
        ),
    ]
