# Generated by Django 2.0.5 on 2018-05-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_template_templatemodifier_templaterequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shadow',
            options={'verbose_name': 'Schatten', 'verbose_name_plural': 'Schatten'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Charaktervorlage', 'verbose_name_plural': 'Charaktervorlagen'},
        ),
        migrations.AddField(
            model_name='template',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute',
            field=models.CharField(blank=True, choices=[('intelligence', 'Intelligenz'), ('deftness', 'Geschick'), ('strength', 'Kraft'), ('attractiveness', 'Attraktivität'), ('endurance', 'Ausdauer'), ('resistance', 'Resistenz'), ('quickness', 'Schnelligkeit'), ('openness', 'Offenheit'), ('conscientiousness', 'Gewissenhaftigkeit'), ('extraversion', 'Extraversion'), ('agreeableness', 'Verträglichkeit'), ('neuroticism', 'Neurotizismus')], help_text='Leer lassen wenn Wissens- oder Fertigkeitsmodifikatoren benutzt werden.', max_length=40, null=True, verbose_name='Attribut'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute_modifier',
            field=models.IntegerField(blank=True, help_text='Leer lassen wenn Wissens- oder Fertigkeitsmodifikatoren benutzt werden.', null=True, verbose_name='Attributsmodifikator'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge',
            field=models.ForeignKey(blank=True, help_text='Leer lassen wenn Fertigkeits- oder Attributsmodifikatoren benutzt werden.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge', verbose_name='Wissen'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge_modifier',
            field=models.IntegerField(blank=True, help_text='Leer lassen wenn Fertigkeits- oder Attributsmodifikatoren benutzt werden.', null=True, verbose_name='Wissensmodifikator'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Leer lassen wenn Attribut- oder Wissensmodifikatoren benutzt werden.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Skill', verbose_name='Fertigkeit'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill_modifier',
            field=models.IntegerField(blank=True, help_text='Leer lassen wenn Attribut- oder Wissensmodifikatoren benutzt werden.', null=True, verbose_name='Fertigkeitsmodifikator'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='Vorlage'),
        ),
        migrations.AlterField(
            model_name='templaterequirement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='Vorlage'),
        ),
    ]
