# Generated by Django 2.0.5 on 2018-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20180502_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'template category',
                'verbose_name_plural': 'template categories',
            },
        ),
    ]
