# Generated by Django 5.1.2 on 2024-11-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_statuseffect_color_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extension",
            name="select_spells_by",
        ),
    ]
