# Generated by Django 2.0.5 on 2018-05-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_templatecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.TemplateCategory'),
            preserve_default=False,
        ),
    ]
