# Generated by Django 3.2.5 on 2021-07-16 20:05

from django.db import migrations

def skill_changes(apps, schema_editor):
    Skill = apps.get_model('rules', 'Skill')

    s = Skill.object.get(name_en='Mindfulness')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'conscientiousness'
    s.save()

    s = Skill.object.get(name_en='Perception')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'quickness'
    s.save()

    s = Skill.object.get(name_en='Intimidation')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'willpower'
    s.save()

    s = Skill.object.get(name_en='Empathy')
    s.dominant_attribute = 'conscientiousness'
    s.supplemental_attribute = 'charm'
    s.save()

    # <<<<<<<<<<<<<< here elin.md


    s = Skill.objects.get(name_en="Esthetics")
    s.name_en = 'Peformance'
    s.name_de = 'Darbietung'
    s.save()

    s = Skill.objects.get(name_en="Improvising")
    s.name_en = 'Acrobatics'
    s.name_de = 'Akrobatik'
    s.save()

    s = Skill.objects.create(
        name_en="Investigation",
        name_de="Untersuchen",
        kind="m"
    )

    s = Skill.objects.create(
        name_en="Nature",
        name_de="Naturkunde",
        kind="p"
    )

    s = Skill.objects.create(
        name_en="History",
        name_de="Historie",
        kind="p"
    )

    s = Skill.objects.create(
        name_en="Politics",
        name_de="Politik",
        kind="m"
    )

    s = Skill.objects.create(
        name_en="Religion",
        name_de="Religion",
        kind="m"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0056_auto_20210716_2001'),
    ]

    operations = [
        migrations.RunPython(skill_changes)
    ]
