# Generated by Django 3.2.7 on 2021-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0060_alter_templatemodifier_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuseffect',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
