# Generated by Django 3.2.7 on 2021-10-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0061_statuseffect_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='show_on_combat_tab',
        ),
    ]
