# Generated by Django 3.2.9 on 2022-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0064_auto_20211229_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
