# Generated by Django 3.2.9 on 2022-01-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0065_auto_20220103_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('kind', models.CharField(choices=[('per', 'persona'), ('phy', 'physis')], max_length=3, verbose_name='kind')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
    ]
