# Generated by Django 3.2.9 on 2022-01-03 12:01

from django.db import migrations


def create_attributes(apps, schema_editor):
    Attribute = apps.get_model('rules', 'Attribute')
    Attribute.objects.create(kind='per', name_en='Education', name_de='Bildung')
    Attribute.objects.create(kind='per', name_en='Logic', name_de='Logik')
    Attribute.objects.create(kind='per', name_en='Conscientiousness', name_de='Gewissenhaftigkeit')
    Attribute.objects.create(kind='per', name_en='Willpower', name_de='Willenskraft')
    Attribute.objects.create(kind='per', name_en='Apprehension', name_de='Auffassungsgabe')
    Attribute.objects.create(kind='per', name_en='Charm', name_de='Charme')
    Attribute.objects.create(kind='phy', name_en='Deftness', name_de='Geschick')
    Attribute.objects.create(kind='phy', name_en='Strength', name_de='Kraft')
    Attribute.objects.create(kind='phy', name_en='Attractiveness', name_de='Attraktivität')
    Attribute.objects.create(kind='phy', name_en='Endurance', name_de='Ausdauer')
    Attribute.objects.create(kind='phy', name_en='Resistance', name_de='Resistenz')
    Attribute.objects.create(kind='phy', name_en='Quickness', name_de='Schnelligkeit')


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0066_attribute'),
    ]

    operations = [
        migrations.RunPython(create_attributes)
    ]
