# Generated by Django 3.2.9 on 2022-01-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0067_auto_20220103_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
    ]
