# Generated by Django 3.2.9 on 2022-01-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0068_alter_attribute_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='reference_attribute_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_attribute_1_set', to='rules.attribute', verbose_name='reference attribute 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='reference_attribute_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_attribute_2_set', to='rules.attribute', verbose_name='reference attribute 2'),
            preserve_default=False,
        ),
    ]
