# Generated by Django 3.2.9 on 2022-01-03 16:47

from django.db import migrations


def assign_attributes(apps, schema_editor):
    Skill = apps.get_model('rules', 'Skill')
    Attribute = apps.get_model('rules', 'Attribute')

    for s in Skill.objects.all():
        s.reference_attribute_1 = Attribute.objects.get(name_en__iexact=s.dominant_attribute.strip())
        s.reference_attribute_2 = Attribute.objects.get(name_en__iexact=s.supplemental_attribute.strip())
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0069_auto_20220103_1645'),
    ]

    operations = [
        migrations.RunPython(assign_attributes)
    ]
