# Generated by Django 3.2.9 on 2022-01-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0070_auto_20220103_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='dominant_attribute',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='supplemental_attribute',
        ),
    ]
