# Generated by Django 3.2.9 on 2022-01-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0071_auto_20220103_1700'),
    ]

    operations = [
        migrations.RenameField('TemplateModifier', 'attribute', 'aspect'),
        migrations.RenameField('TemplateModifier', 'attribute_modifier', 'aspect_modifier'),
    ]
