# Generated by Django 3.2.9 on 2022-01-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0073_auto_20220103_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodifier',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.attribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='templatemodifier',
            name='attribute_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='attribute modifier'),
        ),
    ]
