# Generated by Django 3.2.9 on 2022-01-03 23:28

from django.db import migrations


def assign_attributes(apps, schema_editor):
    TemplateModifier = apps.get_model('rules', 'TemplateModifier')
    Attribute = apps.get_model('rules', 'Attribute')

    for t in TemplateModifier.objects.all():
        aspect_name = t.aspect.replace('base_', '') if t.aspect is not None else ''
        try:
            attribute = Attribute.objects.get(name_en__iexact=aspect_name)
        except Attribute.DoesNotExist:
            pass
        else:
            t.attribute = attribute
            t.attribute_modifier = t.aspect_modifier
            t.aspect = None
            t.aspect_modifier = None
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0074_auto_20220103_2320'),
    ]

    operations = [
        migrations.RunPython(assign_attributes)
    ]
