# Generated by Django 3.2.9 on 2022-01-07 12:49

from django.db import migrations


def set_attribute_identifiers(apps, schema_editor):
    Attribute = apps.get_model('rules', 'Attribute')
    for a in Attribute.objects.all():
        a.identifier = a.name_en.lower()
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0076_auto_20220107_1248'),
    ]

    operations = [
        migrations.RunPython(set_attribute_identifiers)
    ]
