# Generated by Django 3.2.9 on 2022-01-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0077_auto_20220107_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineage',
            name='base_apprehension',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_attractiveness',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_charm',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_conscientiousness',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_deftness',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_education',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_endurance',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_logic',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_quickness',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_resistance',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_strength',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='base_willpower',
        ),
    ]
