# Generated by Django 3.2.12 on 2022-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0078_auto_20220107_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
