# Generated by Django 3.2.12 on 2022-04-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0079_auto_20220409_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='show_rules_in_shadows',
        ),
        migrations.RemoveField(
            model_name='templatemodifier',
            name='shadow',
        ),
        migrations.DeleteModel(
            name='Shadow',
        ),
    ]
