# Generated by Django 3.2.12 on 2022-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_auto_20220410_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='show_in_attack_dice_rolls',
            field=models.BooleanField(default=False, help_text='Show the name in attack dice rolls.', verbose_name='Show in attack dice rolls'),
        ),
    ]
