# Generated by Django 3.2.15 on 2022-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0081_template_show_in_attack_dice_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='type',
            field=models.CharField(choices=[('x', 'Extension'), ('e', 'Epoch'), ('w', 'World')], default='x', max_length=1, verbose_name='type'),
        ),
    ]
