# Generated by Django 3.2.15 on 2022-09-08 13:31

from django.db import migrations


def set_extension_type(apps, schema_editor):
    Extension = apps.get_model('rules', 'Extension')
    for e in Extension.objects.all():
        if e.is_epoch:
            e.type = 'e'


class Migration(migrations.Migration):
    dependencies = [
        ('rules', '0082_extension_type'),
    ]

    operations = [
        migrations.RunPython(set_extension_type)
    ]
