# Generated by Django 3.2.15 on 2022-09-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0083_auto_20220908_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='is_epoch',
        ),
    ]
