# Generated by Django 3.2.15 on 2022-10-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0084_remove_extension_is_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='fixed_epoch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.extension'),
        ),
    ]
