# Generated by Django 3.2.15 on 2022-10-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0085_extension_fixed_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='fixed_epoch',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'e'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.extension'),
        ),
    ]
