# Generated by Django 3.2.15 on 2022-10-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0086_alter_extension_fixed_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.template'),
        ),
    ]
