# Generated by Django 4.1.3 on 2022-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0087_lineage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineage',
            name='template_points',
            field=models.IntegerField(default=20, verbose_name='template points'),
        ),
    ]
