# Generated by Django 4.1.3 on 2022-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0088_lineage_template_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='allow_at_character_creation',
            field=models.BooleanField(default=True, verbose_name='Allow at character creation'),
        ),
    ]
