# Generated by Django 4.1.3 on 2022-12-12 09:30

from django.db import migrations


def forwards(apps, schema_editor):
    TemplateCategory = apps.get_model('rules', 'TemplateCategory')
    TemplateCategory.objects.filter(id=8).update(allow_at_character_creation=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0089_templatecategory_allow_at_character_creation'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
