# Generated by Django 4.1.3 on 2022-12-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0090_auto_20221212_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineageTemplatePoints',
        ),
    ]
