# Generated by Django 4.1.3 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0091_delete_lineagetemplatepoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'ordering': ('sort_order',), 'verbose_name': 'template category', 'verbose_name_plural': 'template categories'},
        ),
        migrations.AlterField(
            model_name='extension',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='extension_images', verbose_name='image'),
        ),
    ]
