# Generated by Django 4.1.6 on 2023-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0092_alter_templatecategory_options_alter_extension_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='fixed_extensions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'x'}, to='rules.extension'),
        ),
    ]
