# Generated by Django 4.1.7 on 2023-03-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0093_extension_fixed_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='select_spells_by',
            field=models.CharField(choices=[('t', 'Type'), ('o', 'Origin')], default='t', help_text='Select spells by type (terra, nexus) or origin (tirakan)', max_length=1, verbose_name='select spells by'),
        ),
    ]
