# Generated by Django 4.1.7 on 2023-03-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0035_alter_spellorigin_image'),
        ('rules', '0094_extension_select_spells_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodifier',
            name='unlocks_spell_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magic.spellorigin', verbose_name='unlocks spell origin'),
        ),
    ]
