# Generated by Django 4.1.7 on 2023-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0095_templatemodifier_unlocks_spell_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemodifier",
            name="allows_priest_actions",
            field=models.BooleanField(
                default=False, verbose_name="allows priest actions"
            ),
        ),
    ]
