# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quirk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=60, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="name"
                    ),
                ),
                (
                    "rules_de",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "rules_en",
                    models.TextField(blank=True, null=True, verbose_name="rules"),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "quirk",
                "verbose_name_plural": "quirks",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="QuirkCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "quirk category",
                "verbose_name_plural": "quirk categories",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="QuirkModifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base_max_health", "max health"),
                            ("base_max_arcana", "max arcana"),
                            ("base_spell_points", "spell points"),
                            ("base_actions", "actions"),
                            ("base_minimum_roll", "minimum roll"),
                            ("base_protection", "protection"),
                            ("base_evasion", "evasion"),
                            ("base_bonus_dice", "bonus dice"),
                            ("base_destiny_dice", "destiny dice"),
                            ("base_rerolls", "rerolls"),
                            ("base_max_stress", "max stress"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="aspect",
                    ),
                ),
                (
                    "aspect_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="aspect modifier"
                    ),
                ),
                (
                    "attribute_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="attribute modifier"
                    ),
                ),
                (
                    "skill_modifier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="skill modifier"
                    ),
                ),
            ],
        ),
    ]
