# Generated by Django 5.1.7 on 2025-04-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horror", "0004_quirk_homebrew_campaign_quirk_homebrew_character_and_more"),
        ("magic", "0010_alter_basespell_duration_unit"),
        ("rules", "0014_template_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quirkmodifier",
            name="allows_priest_actions",
            field=models.BooleanField(
                default=False, verbose_name="allows priest actions"
            ),
        ),
        migrations.AddField(
            model_name="quirkmodifier",
            name="knowledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.knowledge",
                verbose_name="knowledge",
            ),
        ),
        migrations.AddField(
            model_name="quirkmodifier",
            name="knowledge_modifier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="knowledge modifier"
            ),
        ),
        migrations.AddField(
            model_name="quirkmodifier",
            name="unlocks_spell_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magic.spellorigin",
                verbose_name="unlocks spell origin",
            ),
        ),
    ]
