# Generated by Django 5.2.3 on 2025-07-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horror", "0006_alter_quirkmodifier_aspect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quirk",
            name="rules_de",
        ),
        migrations.RemoveField(
            model_name="quirk",
            name="rules_en",
        ),
        migrations.AddField(
            model_name="quirk",
            name="negative_effects_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="negative effects"
            ),
        ),
        migrations.AddField(
            model_name="quirk",
            name="negative_effects_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="negative effects"
            ),
        ),
        migrations.AddField(
            model_name="quirk",
            name="positive_effects_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="positive effects"
            ),
        ),
        migrations.AddField(
            model_name="quirk",
            name="positive_effects_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="positive effects"
            ),
        ),
    ]
