# Generated by Django 5.2.7 on 2025-11-19 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horror", "0008_alter_quirkmodifier_aspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="quirk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quirk",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
    ]
