# Generated by Django 4.1.10 on 2023-08-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="foe_overview_wiki_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foe_overview_world_set",
                to="worlds.wikipage",
            ),
        ),
    ]
