# Generated by Django 4.1.10 on 2023-08-27 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0005_auto_20230827_1656"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="brand_logo",
        ),
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="brand_name_de",
        ),
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="brand_name_en",
        ),
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="worldsiteconfiguration",
            name="template_addon",
        ),
    ]
