# Generated by Django 4.1.10 on 2023-08-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0006_remove_worldsiteconfiguration_brand_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="is default"),
        ),
    ]
