# Generated by Django 4.1.10 on 2023-08-27 17:18

from django.db import migrations


def forward(apps, schema_editor):
    World = apps.get_model("worlds", "World")
    World.objects.filter(name_de="NEXUS").update(is_default=True)


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0007_world_is_default"),
    ]

    operations = [migrations.RunPython(forward)]
