# Generated by Django 4.1.11 on 2023-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0013_rename_brand_claim_world_brand_claim_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="exclude_from_foe_search",
            field=models.BooleanField(
                default=False, verbose_name="excelude from foe search"
            ),
        ),
    ]
