# Generated by Django 4.1.11 on 2023-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0014_wikipage_exclude_from_foe_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipagegameaction",
            name="entity_work_type",
            field=models.CharField(
                blank=True,
                choices=[("lesser", "Lesser"), ("higher", "Higher")],
                help_text="Leave this empty if the Wikipage doesn't describe an entity.",
                max_length=6,
                null=True,
                verbose_name="entity work type",
            ),
        ),
    ]
