# Generated by Django 4.2.6 on 2023-10-17 10:21

from django.db import migrations


def forward(apps, schema_editor):
    WikiPageGameAction = apps.get_model('worlds', 'WikiPageGameAction')
    for wpga in WikiPageGameAction.objects.all():
        if wpga.name_en is not None and wpga.name_en.startswith('Higher'):
            wpga.entity_work_type = "higher"
            wpga.save()
        if wpga.name_en is not None and wpga.name_en.startswith('Lesser'):
            wpga.entity_work_type = "lesser"
            wpga.save()


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_wikipagegameaction_entity_work_type'),
    ]

    operations = [
            migrations.RunPython(forward),
    ]
