# Generated by Django 5.0.6 on 2024-07-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0017_auto_20231122_1841"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="world",
            name="index_template",
        ),
    ]
