# Generated by Django 5.1 on 2024-08-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0018_remove_world_index_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldLeadImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=256,
                        upload_to="world_lead_images",
                        verbose_name="image",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worlds.world"
                    ),
                ),
            ],
            options={
                "verbose_name": "world lead image",
                "verbose_name_plural": "world lead images",
            },
        ),
    ]
