# Generated by Django 5.1.2 on 2024-11-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_characterriotgearprotectionused"),
        ("worlds", "0019_worldleadimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldleadimage",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="characters.character",
                verbose_name="character",
            ),
        ),
    ]
