# Generated by Django 5.1.2 on 2024-11-18 16:58

from django.db import migrations


def forward(apps, schema_editor):
    WikiPage = apps.get_model("worlds", "WikiPage")
    for wp in WikiPage.objects.filter(exclude_from_foe_search=True):
        wp.actions_heading_de = "Wirken"
        wp.actions_heading_en = "Work"
        wp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0020_worldleadimage_character"),
    ]

    operations = [migrations.RunPython(forward)]
