# Generated by Django 5.1.2 on 2024-12-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_characterattribute_modifier"),
        ("magic", "0010_alter_basespell_duration_unit"),
        ("worlds", "0021_auto_20241118_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipagegameaction",
            name="wiki_page",
            field=models.ForeignKey(
                help_text="The wiki page the values belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="worlds.wikipage",
                verbose_name="wiki page",
            ),
        ),
        migrations.CreateModel(
            name="WikiPageEmbedding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="characters.character",
                    ),
                ),
                (
                    "spell_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="magic.spellorigin",
                    ),
                ),
                (
                    "wiki_page",
                    models.ForeignKey(
                        help_text="The wiki page the embedding belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worlds.wikipage",
                        verbose_name="wiki page",
                    ),
                ),
            ],
        ),
    ]
