# Generated by Django 5.1.5 on 2025-01-29 21:12

import json

from django.db import migrations


def forward(apps, schema_editor):
    Extension = apps.get_model("rules", "Extension")
    Language = apps.get_model("worlds", "Language")

    modern = Extension.objects.get(identifier="modern")
    cold_war = Extension.objects.get(identifier="cw")
    imp = Extension.objects.get(identifier="imp")

    for language in get_modern_languages():
        l = Language.objects.create(
            name_de=language["name_de"],
            name_en=language["name_en"],
            country_name_de=language["country_name_de"],
            country_name_en=language["country_name_en"],
            amount_of_people_speaking=language["amount_of_people_speaking"],
        )
        l.extensions.add(modern)
        l.extensions.add(cold_war)
        l.extensions.add(imp)

    victorian = Extension.objects.get(identifier="victorian")
    for language in get_victorian_languages():
        l = Language.objects.create(
            name_de=language["name_de"],
            name_en=language["name_en"],
            country_name_de=language["country_name_de"],
            country_name_en=language["country_name_en"],
            amount_of_people_speaking=language["amount_of_people_speaking"],
        )
        l.extensions.add(victorian)

    medieval = Extension.objects.get(identifier="middleages")
    for language in get_medieval_languages():
        l = Language.objects.create(
            name_de=language["name_de"],
            name_en=language["name_en"],
            country_name_de=language["country_name_de"],
            country_name_en=language["country_name_en"],
            amount_of_people_speaking=language["amount_of_people_speaking"],
        )
        l.extensions.add(medieval)

    antiquity = Extension.objects.get(identifier="ca")
    for language in get_classic_languages():
        l = Language.objects.create(
            name_de=language["name_de"],
            name_en=language["name_en"],
            country_name_de=language["country_name_de"],
            country_name_en=language["country_name_en"],
            amount_of_people_speaking=language["amount_of_people_speaking"],
        )
        l.extensions.add(antiquity)


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0023_language"),
    ]

    operations = [migrations.RunPython(forward)]


def get_modern_languages():
    return json.loads(
        """
    [
  {
    "name_en": "Mandarin Chinese",
    "name_de": "Mandarin-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 918000000
  },
  {
    "name_en": "Spanish",
    "name_de": "Spanisch",
    "country_name_en": "Spain",
    "country_name_de": "Spanien",
    "amount_of_people_speaking": 460000000
  },
  {
    "name_en": "English",
    "name_de": "Englisch",
    "country_name_en": "United Kingdom",
    "country_name_de": "Vereinigtes Königreich",
    "amount_of_people_speaking": 379000000
  },
  {
    "name_en": "Hindi",
    "name_de": "Hindi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 341000000
  },
  {
    "name_en": "Bengali",
    "name_de": "Bengalisch",
    "country_name_en": "Bangladesh",
    "country_name_de": "Bangladesch",
    "amount_of_people_speaking": 228000000
  },
  {
    "name_en": "Portuguese",
    "name_de": "Portugiesisch",
    "country_name_en": "Portugal",
    "country_name_de": "Portugal",
    "amount_of_people_speaking": 221000000
  },
  {
    "name_en": "Russian",
    "name_de": "Russisch",
    "country_name_en": "Russia",
    "country_name_de": "Russland",
    "amount_of_people_speaking": 154000000
  },
  {
    "name_en": "Japanese",
    "name_de": "Japanisch",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 128000000
  },
  {
    "name_en": "Lahnda (Western Punjabi)",
    "name_de": "Lahnda (West-Panjabi)",
    "country_name_en": "Pakistan",
    "country_name_de": "Pakistan",
    "amount_of_people_speaking": 118000000
  },
  {
    "name_en": "Marathi",
    "name_de": "Marathi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 95000000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 93000000
  },
  {
    "name_en": "Wu Chinese",
    "name_de": "Wu-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 81000000
  },
  {
    "name_en": "Turkish",
    "name_de": "Türkisch",
    "country_name_en": "Turkey",
    "country_name_de": "Türkei",
    "amount_of_people_speaking": 75000000
  },
  {
    "name_en": "Korean",
    "name_de": "Koreanisch",
    "country_name_en": "South Korea",
    "country_name_de": "Südkorea",
    "amount_of_people_speaking": 77000000
  },
  {
    "name_en": "French",
    "name_de": "Französisch",
    "country_name_en": "France",
    "country_name_de": "Frankreich",
    "amount_of_people_speaking": 76000000
  },
  {
    "name_en": "German",
    "name_de": "Deutsch",
    "country_name_en": "Germany",
    "country_name_de": "Deutschland",
    "amount_of_people_speaking": 76000000
  },
  {
    "name_en": "Vietnamese",
    "name_de": "Vietnamesisch",
    "country_name_en": "Vietnam",
    "country_name_de": "Vietnam",
    "amount_of_people_speaking": 76000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 75000000
  },
  {
    "name_en": "Yue Chinese (Cantonese)",
    "name_de": "Yue-Chinesisch (Kantonesisch)",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 68000000
  },
  {
    "name_en": "Urdu",
    "name_de": "Urdu",
    "country_name_en": "Pakistan",
    "country_name_de": "Pakistan",
    "amount_of_people_speaking": 68000000
  },
    {
    "name_en": "Gujarati",
    "name_de": "Gujarati",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 55000000
  },
  {
    "name_en": "Jin Chinese",
    "name_de": "Jin-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 45500000
  },
  {
    "name_en": "Persian",
    "name_de": "Persisch",
    "country_name_en": "Iran",
    "country_name_de": "Iran",
    "amount_of_people_speaking": 55000000
  },
  {
    "name_en": "Punjabi",
    "name_de": "Panjabi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 33000000
  },
  {
    "name_en": "Bhojpuri",
    "name_de": "Bhojpuri",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 51000000
  },
  {
    "name_en": "Malayalam",
    "name_de": "Malayalam",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 38000000
  },
  {
    "name_en": "Oriya (Odia)",
    "name_de": "Oriya (Odia)",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 37000000
  },
  {
    "name_en": "Maithili",
    "name_de": "Maithili",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 34000000
  },
  {
    "name_en": "Hausa",
    "name_de": "Hausa",
    "country_name_en": "Nigeria",
    "country_name_de": "Nigeria",
    "amount_of_people_speaking": 39000000
  },
  {
    "name_en": "Sindhi",
    "name_de": "Sindhi",
    "country_name_en": "Pakistan",
    "country_name_de": "Pakistan",
    "amount_of_people_speaking": 32000000
  },
  {
    "name_en": "Burmese",
    "name_de": "Birmanisch",
    "country_name_en": "Myanmar",
    "country_name_de": "Myanmar",
    "amount_of_people_speaking": 33000000
  },
  {
    "name_en": "Hakka Chinese",
    "name_de": "Hakka-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 30000000
  },
  {
    "name_en": "Ukrainian",
    "name_de": "Ukrainisch",
    "country_name_en": "Ukraine",
    "country_name_de": "Ukraine",
    "amount_of_people_speaking": 32000000
  },
  {
    "name_en": "Igbo",
    "name_de": "Igbo",
    "country_name_en": "Nigeria",
    "country_name_de": "Nigeria",
    "amount_of_people_speaking": 27000000
  },
  {
    "name_en": "Thai",
    "name_de": "Thailändisch",
    "country_name_en": "Thailand",
    "country_name_de": "Thailand",
    "amount_of_people_speaking": 25000000
  },
  {
    "name_en": "Yoruba",
    "name_de": "Yoruba",
    "country_name_en": "Nigeria",
    "country_name_de": "Nigeria",
    "amount_of_people_speaking": 40000000
  },
  {
    "name_en": "Kannada",
    "name_de": "Kannada",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 43000000
  },
  {
    "name_en": "Romanian",
    "name_de": "Rumänisch",
    "country_name_en": "Romania",
    "country_name_de": "Rumänien",
    "amount_of_people_speaking": 24000000
  },
  {
    "name_en": "Azerbaijani",
    "name_de": "Aserbaidschanisch",
    "country_name_en": "Azerbaijan",
    "country_name_de": "Aserbaidschan",
    "amount_of_people_speaking": 23000000
  },
  {
    "name_en": "Dutch",
    "name_de": "Niederländisch",
    "country_name_en": "Netherlands",
    "country_name_de": "Niederlande",
    "amount_of_people_speaking": 22000000
  },
  {
    "name_en": "Kurdish",
    "name_de": "Kurdisch",
    "country_name_en": "Turkey",
    "country_name_de": "Türkei",
    "amount_of_people_speaking": 20000000
  },
  {
    "name_en": "Serbo-Croatian",
    "name_de": "Serbokroatisch",
    "country_name_en": "Serbia",
    "country_name_de": "Serbien",
    "amount_of_people_speaking": 21000000
  },
  {
    "name_en": "Malagasy",
    "name_de": "Malagasy",
    "country_name_en": "Madagascar",
    "country_name_de": "Madagaskar",
    "amount_of_people_speaking": 25000000
  },
  {
    "name_en": "Nepali",
    "name_de": "Nepalesisch",
    "country_name_en": "Nepal",
    "country_name_de": "Nepal",
    "amount_of_people_speaking": 17000000
  },
  {
    "name_en": "Chittagonian",
    "name_de": "Chittagonisch",
    "country_name_en": "Bangladesh",
    "country_name_de": "Bangladesch",
    "amount_of_people_speaking": 16000000
  },
  {
    "name_en": "Cebuano",
    "name_de": "Cebuano",
    "country_name_en": "Philippines",
    "country_name_de": "Philippinen",
    "amount_of_people_speaking": 21000000
  },
  {
    "name_en": "Madurese",
    "name_de": "Maduresisch",
    "country_name_en": "Indonesia",
    "country_name_de": "Indonesien",
    "amount_of_people_speaking": 15000000
  },
  {
    "name_en": "Sinhala",
    "name_de": "Singhalesisch",
    "country_name_en": "Sri Lanka",
    "country_name_de": "Sri Lanka",
    "amount_of_people_speaking": 17000000
  },
  {
    "name_en": "Haitian Creole",
    "name_de": "Haitianisch-Kreolisch",
    "country_name_en": "Haiti",
    "country_name_de": "Haiti",
    "amount_of_people_speaking": 11000000
  },
  {
    "name_en": "Khmer",
    "name_de": "Khmer",
    "country_name_en": "Cambodia",
    "country_name_de": "Kambodscha",
    "amount_of_people_speaking": 16000000
  },
  {
    "name_en": "Shona",
    "name_de": "Shona",
    "country_name_en": "Zimbabwe",
    "country_name_de": "Simbabwe",
    "amount_of_people_speaking": 15000000
  },
  {
    "name_en": "Zulu",
    "name_de": "Zulu",
    "country_name_en": "South Africa",
    "country_name_de": "Südafrika",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Kinyarwanda",
    "name_de": "Kinyarwanda",
    "country_name_en": "Rwanda",
    "country_name_de": "Ruanda",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Xhosa",
    "name_de": "Xhosa",
    "country_name_en": "South Africa",
    "country_name_de": "Südafrika",
    "amount_of_people_speaking": 8200000
  },
  {
    "name_en": "Belarusian",
    "name_de": "Weißrussisch",
    "country_name_en": "Belarus",
    "country_name_de": "Weißrussland",
    "amount_of_people_speaking": 8000000
  },
  {
    "name_en": "Bulgarian",
    "name_de": "Bulgarisch",
    "country_name_en": "Bulgaria",
    "country_name_de": "Bulgarien",
    "amount_of_people_speaking": 8000000
  },
  {
    "name_en": "Somali",
    "name_de": "Somali",
    "country_name_en": "Somalia",
    "country_name_de": "Somalia",
    "amount_of_people_speaking": 16000000
  },
  {
    "name_en": "Kazakh",
    "name_de": "Kasachisch",
    "country_name_en": "Kazakhstan",
    "country_name_de": "Kasachstan",
    "amount_of_people_speaking": 13000000
  },
  {
    "name_en": "Hungarian",
    "name_de": "Ungarisch",
    "country_name_en": "Hungary",
    "country_name_de": "Ungarn",
    "amount_of_people_speaking": 13000000
  },
  {
    "name_en": "Kinyarwanda",
    "name_de": "Kinyarwanda",
    "country_name_en": "Rwanda",
    "country_name_de": "Ruanda",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Greek",
    "name_de": "Griechisch",
    "country_name_en": "Greece",
    "country_name_de": "Griechenland",
    "amount_of_people_speaking": 13000000
  },
  {
    "name_en": "Czech",
    "name_de": "Tschechisch",
    "country_name_en": "Czech Republic",
    "country_name_de": "Tschechische Republik",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Swedish",
    "name_de": "Schwedisch",
    "country_name_en": "Sweden",
    "country_name_de": "Schweden",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Hmong",
    "name_de": "Hmong",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 9000000
  },
  {
    "name_en": "Rundi",
    "name_de": "Rundi",
    "country_name_en": "Burundi",
    "country_name_de": "Burundi",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Portuguese (Angola)",
    "name_de": "Portugiesisch (Angola)",
    "country_name_en": "Angola",
    "country_name_de": "Angola",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Czech",
    "name_de": "Tschechisch",
    "country_name_en": "Czech Republic",
    "country_name_de": "Tschechische Republik",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Serbian",
    "name_de": "Serbisch",
    "country_name_en": "Serbia",
    "country_name_de": "Serbien",
    "amount_of_people_speaking": 9000000
  },
  {
    "name_en": "Zulu",
    "name_de": "Zulu",
    "country_name_en": "South Africa",
    "country_name_de": "Südafrika",
    "amount_of_people_speaking": 12000000
  },
            {
        "name_en": "Swahili",
        "name_de": "Suaheli",
        "country_name_en": "Tanzania",
        "country_name_de": "Tansania",
        "amount_of_people_speaking": 15000000
      },
      {
        "name_en": "Javanese",
        "name_de": "Javanisch",
        "country_name_en": "Indonesia",
        "country_name_de": "Indonesien",
        "amount_of_people_speaking": 82000000
      },
      {
        "name_en": "Sundanese",
        "name_de": "Sundanesisch",
        "country_name_en": "Indonesia",
        "country_name_de": "Indonesien",
        "amount_of_people_speaking": 39000000
      },
      {
        "name_en": "Amharic",
        "name_de": "Amharisch",
        "country_name_en": "Ethiopia",
        "country_name_de": "Äthiopien",
        "amount_of_people_speaking": 22000000
      },
      {
        "name_en": "Fula",
        "name_de": "Ful",
        "country_name_en": "Nigeria",
        "country_name_de": "Nigeria",
        "amount_of_people_speaking": 25000000
      },
      {
        "name_en": "Spanish (Mexico)",
        "name_de": "Spanisch (Mexiko)",
        "country_name_en": "Mexico",
        "country_name_de": "Mexiko",
        "amount_of_people_speaking": 125000000
      },
      {
        "name_en": "Herero",
        "name_de": "Herero",
        "country_name_en": "Namibia",
        "country_name_de": "Namibia",
        "amount_of_people_speaking": 250000
      },
      {
        "name_en": "Esperanto",
        "name_de": "Esperanto",
        "country_name_en": "International",
        "country_name_de": "International",
        "amount_of_people_speaking": 2000000
      },
      {
        "name_en": "Haitian Creole",
        "name_de": "Haitianisch-Kreolisch",
        "country_name_en": "Haiti",
        "country_name_de": "Haiti",
        "amount_of_people_speaking": 11000000
      },
      {
        "name_en": "Shona",
        "name_de": "Shona",
        "country_name_en": "Zimbabwe",
        "country_name_de": "Simbabwe",
        "amount_of_people_speaking": 15000000
      },
      {
        "name_en": "Uzbek",
        "name_de": "Usbekisch",
        "country_name_en": "Uzbekistan",
        "country_name_de": "Usbekistan",
        "amount_of_people_speaking": 27000000
      },
      {
        "name_en": "Kazakh",
        "name_de": "Kasachisch",
        "country_name_en": "Kazakhstan",
        "country_name_de": "Kasachstan",
        "amount_of_people_speaking": 13000000
      },
      {
        "name_en": "Hungarian",
        "name_de": "Ungarisch",
        "country_name_en": "Hungary",
        "country_name_de": "Ungarn",
        "amount_of_people_speaking": 13000000
      },
      {
        "name_en": "Greek",
        "name_de": "Griechisch",
        "country_name_en": "Greece",
        "country_name_de": "Griechenland",
        "amount_of_people_speaking": 13000000
      },
      {
        "name_en": "Czech",
        "name_de": "Tschechisch",
        "country_name_en": "Czech Republic",
        "country_name_de": "Tschechische Republik",
        "amount_of_people_speaking": 10000000
      },
      {
        "name_en": "Chichewa",
        "name_de": "Chichewa",
        "country_name_en": "Malawi",
        "country_name_de": "Malawi",
        "amount_of_people_speaking": 17000000
      },
      {
        "name_en": "Kinyarwanda",
        "name_de": "Kinyarwanda",
        "country_name_en": "Rwanda",
        "country_name_de": "Ruanda",
        "amount_of_people_speaking": 12000000
      },
      {
        "name_en": "Zulu",
        "name_de": "Zulu",
        "country_name_en": "South Africa",
        "country_name_de": "Südafrika",
        "amount_of_people_speaking": 12000000
      },
      {
        "name_en": "Kurdish",
        "name_de": "Kurdisch",
        "country_name_en": "Turkey",
        "country_name_de": "Türkei",
        "amount_of_people_speaking": 20000000
      },
      {
        "name_en": "Quechua",
        "name_de": "Quechua",
        "country_name_en": "Peru",
        "country_name_de": "Peru",
        "amount_of_people_speaking": 8000000
      },
      {
        "name_en": "Kirundi",
        "name_de": "Kirundi",
        "country_name_en": "Burundi",
        "country_name_de": "Burundi",
        "amount_of_people_speaking": 12000000
      },
      {
        "name_en": "Slovak",
        "name_de": "Slowakisch",
        "country_name_en": "Slovakia",
        "country_name_de": "Slowakei",
        "amount_of_people_speaking": 5000000
      },
      {
        "name_en": "Danish",
        "name_de": "Dänisch",
        "country_name_en": "Denmark",
        "country_name_de": "Dänemark",
        "amount_of_people_speaking": 5800000
      },
      {
        "name_en": "Finnish",
        "name_de": "Finnisch",
        "country_name_en": "Finland",
        "country_name_de": "Finnland",
        "amount_of_people_speaking": 5500000
      },
      {
        "name_en": "Norwegian",
        "name_de": "Norwegisch",
        "country_name_en": "Norway",
        "country_name_de": "Norwegen",
        "amount_of_people_speaking": 5300000
      },
      {
        "name_en": "Lithuanian",
        "name_de": "Litauisch",
        "country_name_en": "Lithuania",
        "country_name_de": "Litauen",
        "amount_of_people_speaking": 3000000
      },
      {
        "name_en": "Latvian",
        "name_de": "Lettisch",
        "country_name_en": "Latvia",
        "country_name_de": "Lettland",
        "amount_of_people_speaking": 2000000
      },
      {
        "name_en": "Estonian",
        "name_de": "Estnisch",
        "country_name_en": "Estonia",
        "country_name_de": "Estland",
        "amount_of_people_speaking": 1100000
      },
      {
        "name_en": "Macedonian",
        "name_de": "Mazedonisch",
        "country_name_en": "North Macedonia",
        "country_name_de": "Nordmazedonien",
        "amount_of_people_speaking": 2000000
      },
      {
        "name_en": "Armenian",
        "name_de": "Armenisch",
        "country_name_en": "Armenia",
        "country_name_de": "Armenien",
        "amount_of_people_speaking": 6500000
      },
      {
        "name_en": "Albanian",
        "name_de": "Albanisch",
        "country_name_en": "Albania",
        "country_name_de": "Albanien",
        "amount_of_people_speaking": 7500000
      },
      {
        "name_en": "Georgian",
        "name_de": "Georgisch",
        "country_name_en": "Georgia",
        "country_name_de": "Georgien",
        "amount_of_people_speaking": 4000000
      },
      {
        "name_en": "Irish",
        "name_de": "Irisch",
        "country_name_en": "Ireland",
        "country_name_de": "Irland",
        "amount_of_people_speaking": 1400000
      },
      {
        "name_en": "Welsh",
        "name_de": "Walisisch",
        "country_name_en": "United Kingdom",
        "country_name_de": "Vereinigtes Königreich",
        "amount_of_people_speaking": 750000
      },
      {
        "name_en": "Basque",
        "name_de": "Baskisch",
        "country_name_en": "Spain",
        "country_name_de": "Spanien",
        "amount_of_people_speaking": 750000
      },
      {
        "name_en": "Catalan",
        "name_de": "Katalanisch",
        "country_name_en": "Spain",
        "country_name_de": "Spanien",
        "amount_of_people_speaking": 9500000
      },
      {
        "name_en": "Galician",
        "name_de": "Galicisch",
        "country_name_en": "Spain",
        "country_name_de": "Spanien",
        "amount_of_people_speaking": 2500000
      },
      {
        "name_en": "Luxembourgish",
        "name_de": "Luxemburgisch",
        "country_name_en": "Luxembourg",
        "country_name_de": "Luxemburg",
        "amount_of_people_speaking": 600000
      },
      {
        "name_en": "Icelandic",
        "name_de": "Isländisch",
        "country_name_en": "Iceland",
        "country_name_de": "Island",
        "amount_of_people_speaking": 350000
      },
      {
        "name_en": "Maltese",
        "name_de": "Maltesisch",
        "country_name_en": "Malta",
        "country_name_de": "Malta",
        "amount_of_people_speaking": 520000
      },
      {
        "name_en": "Tatar",
        "name_de": "Tatarisch",
        "country_name_en": "Russia",
        "country_name_de": "Russland",
        "amount_of_people_speaking": 5500000
      },
      {
        "name_en": "Uyghur",
        "name_de": "Uigurisch",
        "country_name_en": "China",
        "country_name_de": "China",
        "amount_of_people_speaking": 10000000
      },
      {
        "name_en": "Mongolian",
        "name_de": "Mongolisch",
        "country_name_en": "Mongolia",
        "country_name_de": "Mongolei",
        "amount_of_people_speaking": 5000000
      },
      {
        "name_en": "Tajik",
        "name_de": "Tadschikisch",
        "country_name_en": "Tajikistan",
        "country_name_de": "Tadschikistan",
        "amount_of_people_speaking": 8000000
      },
      {
        "name_en": "Turkmen",
        "name_de": "Turkmenisch",
        "country_name_en": "Turkmenistan",
        "country_name_de": "Turkmenistan",
        "amount_of_people_speaking": 7000000
      },
      {
        "name_en": "Khmer",
        "name_de": "Khmer",
        "country_name_en": "Cambodia",
        "country_name_de": "Kambodscha",
        "amount_of_people_speaking": 16000000
      },
      {
        "name_en": "Lao",
        "name_de": "Laotisch",
        "country_name_en": "Laos",
        "country_name_de": "Laos",
        "amount_of_people_speaking": 3000000
      },
      {
        "name_en": "Sinhala",
        "name_de": "Singhalesisch",
        "country_name_en": "Sri Lanka",
        "country_name_de": "Sri Lanka",
        "amount_of_people_speaking": 17000000
      },
      {
        "name_en": "Tibetan",
        "name_de": "Tibetisch",
        "country_name_en": "China",
        "country_name_de": "China",
        "amount_of_people_speaking": 6000000
      },
      {
        "name_en": "Dzongkha",
        "name_de": "Dzongkha",
        "country_name_en": "Bhutan",
        "country_name_de": "Bhutan",
        "amount_of_people_speaking": 600000
      }
    ]
    """
    )


def get_medieval_languages():
    return json.loads(
        """
    [
  {
    "name_en": "Mandarin Chinese",
    "name_de": "Mandarin-Chinesisch",
    "country_name_en": "Song Dynasty",
    "country_name_de": "Song-Dynastie",
    "amount_of_people_speaking": 60000000
  },
  {
    "name_en": "Arabic",
    "name_de": "Arabisch",
    "country_name_en": "Abbasid Caliphate",
    "country_name_de": "Abbasiden-Kalifat",
    "amount_of_people_speaking": 35000000
  },
  {
    "name_en": "Middle English",
    "name_de": "Mittelenglisch",
    "country_name_en": "Kingdom of England",
    "country_name_de": "Königreich England",
    "amount_of_people_speaking": 2500000
  },
  {
    "name_en": "Latin",
    "name_de": "Latein",
    "country_name_en": "Various European Regions",
    "country_name_de": "Verschiedene europäische Regionen",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Old French",
    "name_de": "Altfranzösisch",
    "country_name_en": "Kingdom of France",
    "country_name_de": "Königreich Frankreich",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Old High German",
    "name_de": "Althochdeutsch",
    "country_name_en": "Holy Roman Empire",
    "country_name_de": "Heiliges Römisches Reich",
    "amount_of_people_speaking": 8000000
  },
  {
    "name_en": "Byzantine Greek",
    "name_de": "Byzantinisches Griechisch",
    "country_name_en": "Byzantine Empire",
    "country_name_de": "Byzantinisches Reich",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Sanskrit",
    "name_de": "Sanskrit",
    "country_name_en": "Indian Subcontinent",
    "country_name_de": "Indischer Subkontinent",
    "amount_of_people_speaking": 15000000
  },
  {
    "name_en": "Old Norse",
    "name_de": "Altnordisch",
    "country_name_en": "Scandinavian Regions",
    "country_name_de": "Skandinavische Regionen",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Persian",
    "name_de": "Persisch",
    "country_name_en": "Sassanian Empire",
    "country_name_de": "Sassanidenreich",
    "amount_of_people_speaking": 8000000
  },
  {
    "name_en": "Japanese",
    "name_de": "Japanisch",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 8000000
  },
  {
    "name_en": "Korean",
    "name_de": "Koreanisch",
    "country_name_en": "Goryeo Dynasty",
    "country_name_de": "Goryeo-Dynastie",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "Chola Dynasty",
    "country_name_de": "Chola-Dynastie",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "Kakatiya Dynasty",
    "country_name_de": "Kakatiya-Dynastie",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Malay",
    "name_de": "Malaiisch",
    "country_name_en": "Srivijaya Empire",
    "country_name_de": "Sriwijaya-Reich",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Vietnamese",
    "name_de": "Vietnamesisch",
    "country_name_en": "Dai Viet",
    "country_name_de": "Đại Việt",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Khmer",
    "name_de": "Khmer",
    "country_name_en": "Khmer Empire",
    "country_name_de": "Khmer-Reich",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Bengali",
    "name_de": "Bengalisch",
    "country_name_en": "Pala Empire",
    "country_name_de": "Pala-Reich",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Marathi",
    "name_de": "Marathi",
    "country_name_en": "Yadava Dynasty",
    "country_name_de": "Yadava-Dynastie",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Gujarati",
    "name_de": "Gujarati",
    "country_name_en": "Solanki Dynasty",
    "country_name_de": "Solanki-Dynastie",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Kannada",
    "name_de": "Kannada",
    "country_name_en": "Hoysala Empire",
    "country_name_de": "Hoysala-Reich",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Burmese",
    "name_de": "Birmanisch",
    "country_name_en": "Pagan Kingdom",
    "country_name_de": "Pagan-Königreich",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Hebrew",
    "name_de": "Hebräisch",
    "country_name_en": "Kingdom of Judah",
    "country_name_de": "Königreich Juda",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Coptic",
    "name_de": "Koptisch",
    "country_name_en": "Fatimid Caliphate",
    "country_name_de": "Fatimiden-Kalifat",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Swahili",
    "name_de": "Swahili",
    "country_name_en": "Swahili Coast",
    "country_name_de": "Swahili-Küste",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Amharic",
    "name_de": "Amharisch",
    "country_name_en": "Ethiopian Empire",
    "country_name_de": "Äthiopisches Reich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Hausa",
    "name_de": "Hausa",
    "country_name_en": "Hausa Kingdoms",
    "country_name_de": "Hausa-Königreiche",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Yoruba",
    "name_de": "Yoruba",
    "country_name_en": "Oyo Empire",
    "country_name_de": "Oyo-Reich",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Zulu",
    "name_de": "Zulu",
    "country_name_en": "Zulu Kingdom",
    "country_name_de": "Zulu-Königreich",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Mandinka",
    "name_de": "Mandinka",
    "country_name_en": "Mali Empire",
    "country_name_de": "Mali-Reich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Berber",
    "name_de": "Berberisch",
    "country_name_en": "Almohad Caliphate",
    "country_name_de": "Almohaden-Kalifat",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Mongolian",
    "name_de": "Mongolisch",
    "country_name_en": "Mongol Empire",
    "country_name_de": "Mongolisches Reich",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Turkish",
    "name_de": "Türkisch",
    "country_name_en": "Seljuk Empire",
    "country_name_de": "Seldschukenreich",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Armenian",
    "name_de": "Armenisch",
    "country_name_en": "Kingdom of Cilicia",
    "country_name_de": "Königreich Kilikien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Georgian",
    "name_de": "Georgisch",
    "country_name_en": "Kingdom of Georgia",
    "country_name_de": "Königreich Georgien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Kurdish",
    "name_de": "Kurdisch",
    "country_name_en": "Ayyubid Dynasty",
    "country_name_de": "Ayyubiden-Dynastie",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Slavic Languages",
    "name_de": "Slawische Sprachen",
    "country_name_en": "Kievan Rus'",
    "country_name_de": "Kiewer Rus",
    "amount_of_people_speaking": 7000000
  },
  {
    "name_en": "Polish",
    "name_de": "Polnisch",
    "country_name_en": "Kingdom of Poland",
    "country_name_de": "Königreich Polen",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Czech",
    "name_de": "Tschechisch",
    "country_name_en": "Kingdom of Bohemia",
    "country_name_de": "Königreich Böhmen",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Hungarian",
    "name_de": "Ungarisch",
    "country_name_en": "Kingdom of Hungary",
    "country_name_de": "Königreich Ungarn",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Bulgarian",
    "name_de": "Bulgarisch",
    "country_name_en": "Second Bulgarian Empire",
    "country_name_de": "Zweites Bulgarisches Reich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Serbian",
    "name_de": "Serbisch",
    "country_name_en": "Serbian Empire",
    "country_name_de": "Serbisches Reich",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Romanian",
    "name_de": "Rumänisch",
    "country_name_en": "Principality of Wallachia",
    "country_name_de": "Fürstentum Walachei",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Finnish",
    "name_de": "Finnisch",
    "country_name_en": "Kingdom of Sweden",
    "country_name_de": "Königreich Schweden",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Estonian",
    "name_de": "Estnisch",
    "country_name_en": "Teutonic Order State",
    "country_name_de": "Deutschordensstaat",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Lithuanian",
    "name_de": "Litauisch",
    "country_name_en": "Grand Duchy of Lithuania",
    "country_name_de": "Großfürstentum Litauen",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Basque",
    "name_de": "Baskisch",
    "country_name_en": "Kingdom of Navarre",
    "country_name_de": "Königreich Navarra",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Catalan",
    "name_de": "Katalanisch",
    "country_name_en": "Crown of Aragon",
    "country_name_de": "Krone von Aragon",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Castilian",
    "name_de": "Kastilisch",
    "country_name_en": "Kingdom of Castile",
    "country_name_de": "Königreich Kastilien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Portuguese",
    "name_de": "Portugiesisch",
    "country_name_en": "Kingdom of Portugal",
    "country_name_de": "Königreich Portugal",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Welsh",
    "name_de": "Walisisch",
    "country_name_en": "Wales",
    "country_name_de": "Wales",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Irish Gaelic",
    "name_de": "Irisches Gälisch",
    "country_name_en": "Ireland",
    "country_name_de": "Irland",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Scots Gaelic",
    "name_de": "Schottisches Gälisch",
    "country_name_en": "Scotland",
    "country_name_de": "Schottland",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Norwegian",
    "name_de": "Norwegisch",
    "country_name_en": "Kingdom of Norway",
    "country_name_de": "Königreich Norwegen",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Danish",
    "name_de": "Dänisch",
    "country_name_en": "Kingdom of Denmark",
    "country_name_de": "Königreich Dänemark",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Swedish",
    "name_de": "Schwedisch",
    "country_name_en": "Kingdom of Sweden",
    "country_name_de": "Königreich Schweden",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Icelandic",
    "name_de": "Isländisch",
    "country_name_en": "Iceland",
    "country_name_de": "Island",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Quechua",
    "name_de": "Quechua",
    "country_name_en": "Inca Empire",
    "country_name_de": "Inka-Reich",
    "amount_of_people_speaking": 6000000
  },
  {
    "name_en": "Nahuatl",
    "name_de": "Nahuatl",
    "country_name_en": "Aztec Empire",
    "country_name_de": "Aztekenreich",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Mayan Languages",
    "name_de": "Maya-Sprachen",
    "country_name_en": "Maya Civilization",
    "country_name_de": "Maya-Zivilisation",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Algonquian Languages",
    "name_de": "Algonkin-Sprachen",
    "country_name_en": "Various Tribes",
    "country_name_de": "Verschiedene Stämme",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Inuit Languages",
    "name_de": "Inuit-Sprachen",
    "country_name_en": "Arctic Regions",
    "country_name_de": "Arktische Regionen",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Maori",
    "name_de": "Maori",
    "country_name_en": "New Zealand",
    "country_name_de": "Neuseeland",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Tibetan",
    "name_de": "Tibetisch",
    "country_name_en": "Tibetan Empire",
    "country_name_de": "Tibetisches Reich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Sogdian",
    "name_de": "Sogdisch",
    "country_name_en": "Sogdia",
    "country_name_de": "Sogdien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Uyghur",
    "name_de": "Uigurisch",
    "country_name_en": "Uyghur Khaganate",
    "country_name_de": "Uiguren-Kaganat",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Luo",
    "name_de": "Luo",
    "country_name_en": "Eastern Africa",
    "country_name_de": "Ostafrika",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Fulani",
    "name_de": "Fulfulde",
    "country_name_en": "West Africa",
    "country_name_de": "Westafrika",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Kanuri",
    "name_de": "Kanuri",
    "country_name_en": "Kanem Empire",
    "country_name_de": "Kanem-Reich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Nubian",
    "name_de": "Nubisch",
    "country_name_en": "Kingdom of Makuria",
    "country_name_de": "Königreich von Makuria",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Sicilian",
    "name_de": "Sizilianisch",
    "country_name_en": "Kingdom of Sicily",
    "country_name_de": "Königreich Sizilien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Ainu",
    "name_de": "Ainu",
    "country_name_en": "Northern Japan",
    "country_name_de": "Nordjapan",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Ojibwe",
    "name_de": "Ojibwe",
    "country_name_en": "Great Lakes Region",
    "country_name_de": "Region der Großen Seen",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Inuktitut",
    "name_de": "Inuktitut",
    "country_name_en": "Arctic Regions",
    "country_name_de": "Arktische Regionen",
    "amount_of_people_speaking": 100000
  }
  ]"""
    )


def get_classic_languages():
    return json.loads(
        """
    [
  {
    "name_en": "Latin",
    "name_de": "Latein",
    "country_name_en": "Roman Republic",
    "country_name_de": "Römische Republik",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Ancient Greek",
    "name_de": "Altgriechisch",
    "country_name_en": "Hellenistic Greece",
    "country_name_de": "Hellenistisches Griechenland",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Classical Chinese",
    "name_de": "Klassisches Chinesisch",
    "country_name_en": "Qin Dynasty",
    "country_name_de": "Qin-Dynastie",
    "amount_of_people_speaking": 20000000
  },
  {
    "name_en": "Sanskrit",
    "name_de": "Sanskrit",
    "country_name_en": "Maurya Empire",
    "country_name_de": "Maurya-Reich",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Old Persian",
    "name_de": "Altpersisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Aramaic",
    "name_de": "Aramäisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 2500000
  },
  {
    "name_en": "Egyptian (Demotic)",
    "name_de": "Ägyptisch (Demotisch)",
    "country_name_en": "Ptolemaic Egypt",
    "country_name_de": "Ptolemäisches Ägypten",
    "amount_of_people_speaking": 4000000
  },
  {
    "name_en": "Hebrew",
    "name_de": "Hebräisch",
    "country_name_en": "Hasmonean Kingdom",
    "country_name_de": "Hasmonäisches Königreich",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Gaulish",
    "name_de": "Gallisch",
    "country_name_en": "Gaul",
    "country_name_de": "Gallien",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Celtic (Various Dialects)",
    "name_de": "Keltisch (Verschiedene Dialekte)",
    "country_name_en": "Various Celtic Tribes",
    "country_name_de": "Verschiedene keltische Stämme",
    "amount_of_people_speaking": 7000000
  },
  {
    "name_en": "Punic",
    "name_de": "Punisch",
    "country_name_en": "Carthaginian Empire",
    "country_name_de": "Karthagisches Reich",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Phoenician",
    "name_de": "Phönizisch",
    "country_name_en": "Phoenician City-States",
    "country_name_de": "Phönizische Stadtstaaten",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Illyrian",
    "name_de": "Illyrisch",
    "country_name_en": "Kingdom of Illyria",
    "country_name_de": "Königreich Illyrien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Thracian",
    "name_de": "Thrakisch",
    "country_name_en": "Thrace",
    "country_name_de": "Thrakien",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Lydian",
    "name_de": "Lydisch",
    "country_name_en": "Lydia",
    "country_name_de": "Lydien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Scythian",
    "name_de": "Skythisch",
    "country_name_en": "Scythia",
    "country_name_de": "Skythien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Nubian",
    "name_de": "Nubisch",
    "country_name_en": "Kingdom of Kush",
    "country_name_de": "Königreich von Kusch",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Etruscan",
    "name_de": "Etruskisch",
    "country_name_en": "Etruria",
    "country_name_de": "Etrurien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Berber",
    "name_de": "Berberisch",
    "country_name_en": "Numidia",
    "country_name_de": "Numidien",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Germanic (Proto-Germanic)",
    "name_de": "Germanisch (Ur-Germanisch)",
    "country_name_en": "Germanic Tribes",
    "country_name_de": "Germanische Stämme",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Sogdian",
    "name_de": "Sogdisch",
    "country_name_en": "Sogdia",
    "country_name_de": "Sogdien",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Parthian",
    "name_de": "Parthisch",
    "country_name_en": "Parthian Empire",
    "country_name_de": "Parthisches Reich",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Anatolian (Various Languages)",
    "name_de": "Anatolisch (Verschiedene Sprachen)",
    "country_name_en": "Anatolia",
    "country_name_de": "Anatolien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Old Macedonian",
    "name_de": "Altmakedonisch",
    "country_name_en": "Macedonia",
    "country_name_de": "Makedonien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Armenian",
    "name_de": "Armenisch",
    "country_name_en": "Kingdom of Armenia",
    "country_name_de": "Königreich Armenien",
    "amount_of_people_speaking": 900000
  },
  {
    "name_en": "Goidelic (Primitive Irish)",
    "name_de": "Goidelisch (Primitives Irisch)",
    "country_name_en": "Ireland",
    "country_name_de": "Irland",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Brittonic",
    "name_de": "Brittonisch",
    "country_name_en": "Britannia",
    "country_name_de": "Britannien",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Old Norse (Proto-Norse)",
    "name_de": "Altnordisch (Urnordisch)",
    "country_name_en": "Scandinavian Tribes",
    "country_name_de": "Skandinavische Stämme",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Epirote",
    "name_de": "Epirotisch",
    "country_name_en": "Epirus",
    "country_name_de": "Epirus",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Ligurian",
    "name_de": "Ligurisch",
    "country_name_en": "Liguria",
    "country_name_de": "Ligurien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Dacian",
    "name_de": "Dakisch",
    "country_name_en": "Dacia",
    "country_name_de": "Dakien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Hittite",
    "name_de": "Hethitisch",
    "country_name_en": "Neo-Hittite States",
    "country_name_de": "Neo-hethitische Staaten",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Gothic (Early)",
    "name_de": "Gotisch (Früh)",
    "country_name_en": "Gothic Tribes",
    "country_name_de": "Gotische Stämme",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Old Malayalam (Proto-Dravidian)",
    "name_de": "Alt-Malayalam (Ur-Dravidisch)",
    "country_name_en": "South India",
    "country_name_de": "Südindien",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "Tamilakam",
    "country_name_de": "Tamilakam",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Kannada",
    "name_de": "Kannada",
    "country_name_en": "Karnata",
    "country_name_de": "Karnata",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "Andhra",
    "country_name_de": "Andhra",
    "amount_of_people_speaking": 900000
  },
  {
    "name_en": "Mayan Languages",
    "name_de": "Maya-Sprachen",
    "country_name_en": "Maya City-States",
    "country_name_de": "Maya-Stadtstaaten",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Zapotec",
    "name_de": "Zapotekisch",
    "country_name_en": "Zapotec Civilization",
    "country_name_de": "Zapotekische Zivilisation",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Quechua (Proto-Quechua)",
    "name_de": "Quechua (Ur-Quechua)",
    "country_name_en": "Andean Region",
    "country_name_de": "Andenregion",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Nahuatl (Proto-Nahuan)",
    "name_de": "Nahuatl (Ur-Nahuan)",
    "country_name_en": "Central Mexico",
    "country_name_de": "Zentralmexiko",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Japanese (Old Japanese)",
    "name_de": "Japanisch (Altjapanisch)",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Korean (Old Korean)",
    "name_de": "Koreanisch (Altkoreanisch)",
    "country_name_en": "Gojoseon",
    "country_name_de": "Gojoseon",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Vietnamese (Proto-Vietic)",
    "name_de": "Vietnamesisch (Ur-Vietic)",
    "country_name_en": "Âu Lạc",
    "country_name_de": "Âu Lạc",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Mongolic (Proto-Mongolic)",
    "name_de": "Mongolisch (Ur-Mongolisch)",
    "country_name_en": "Mongolian Steppes",
    "country_name_de": "Mongolische Steppen",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Turkic (Proto-Turkic)",
    "name_de": "Turkisch (Ur-Turkisch)",
    "country_name_en": "Central Asia",
    "country_name_de": "Zentralasien",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Basque",
    "name_de": "Baskisch",
    "country_name_en": "Vasconia",
    "country_name_de": "Vasconia",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Umbrian",
    "name_de": "Umbrisch",
    "country_name_en": "Umbria",
    "country_name_de": "Umbrien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Oscan",
    "name_de": "Oskisch",
    "country_name_en": "Samnium",
    "country_name_de": "Samnium",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Venetic",
    "name_de": "Venetisch",
    "country_name_en": "Venetia",
    "country_name_de": "Venetien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Phrygian",
    "name_de": "Phrygisch",
    "country_name_en": "Phrygia",
    "country_name_de": "Phrygien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Luwian",
    "name_de": "Luwisch",
    "country_name_en": "Anatolia",
    "country_name_de": "Anatolien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Elamite",
    "name_de": "Elamisch",
    "country_name_en": "Elam",
    "country_name_de": "Elam",
    "amount_of_people_speaking": 150000
  },
  {
    "name_en": "Numidian",
    "name_de": "Numidisch",
    "country_name_en": "Numidia",
    "country_name_de": "Numidien",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Edomite",
    "name_de": "Edomitisch",
    "country_name_en": "Edom",
    "country_name_de": "Edom",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Moabite",
    "name_de": "Moabitisch",
    "country_name_en": "Moab",
    "country_name_de": "Moab",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Ammonite",
    "name_de": "Ammonitisch",
    "country_name_en": "Ammon",
    "country_name_de": "Ammon",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Anasazi (Proto-Puebloan)",
    "name_de": "Anasazi (Ur-Pueblo)",
    "country_name_en": "Southwestern North America",
    "country_name_de": "Südwestliches Nordamerika",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Inuit (Proto-Inuit)",
    "name_de": "Inuit (Ur-Inuit)",
    "country_name_en": "Arctic Regions",
    "country_name_de": "Arktische Regionen",
    "amount_of_people_speaking": 40000
  },
  {
    "name_en": "Maori (Proto-Polynesian)",
    "name_de": "Maori (Ur-Polynesisch)",
    "country_name_en": "Polynesia",
    "country_name_de": "Polynesien",
    "amount_of_people_speaking": 60000
  },
  {
    "name_en": "Bantu Languages",
    "name_de": "Bantu-Sprachen",
    "country_name_en": "Sub-Saharan Africa",
    "country_name_de": "Subsahara-Afrika",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Yoruba",
    "name_de": "Yoruba",
    "country_name_en": "West Africa",
    "country_name_de": "Westafrika",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Igbo",
    "name_de": "Igbo",
    "country_name_en": "West Africa",
    "country_name_de": "Westafrika",
    "amount_of_people_speaking": 400000
  },
  {
    "name_en": "Zulu",
    "name_de": "Zulu",
    "country_name_en": "Southern Africa",
    "country_name_de": "Südliches Afrika",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Swahili (Proto-Sabaki)",
    "name_de": "Swahili (Ur-Sabaki)",
    "country_name_en": "East Africa",
    "country_name_de": "Ostafrika",
    "amount_of_people_speaking": 600000
  },
  {
    "name_en": "Avestan",
    "name_de": "Avestisch",
    "country_name_en": "Bactria",
    "country_name_de": "Baktrien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Old Armenian",
    "name_de": "Altarmenisch",
    "country_name_en": "Armenia",
    "country_name_de": "Armenien",
    "amount_of_people_speaking": 700000
  },
  {
    "name_en": "Kurdish (Proto-Kurdish)",
    "name_de": "Kurdisch (Ur-Kurdisch)",
    "country_name_en": "Median Empire",
    "country_name_de": "Mederreich",
    "amount_of_people_speaking": 500000
  },
  {
    "name_en": "Syriac",
    "name_de": "Syrisch",
    "country_name_en": "Seleucid Empire",
    "country_name_de": "Seleukidisches Reich",
    "amount_of_people_speaking": 300000
  },
  {
    "name_en": "Akkadian",
    "name_de": "Akkadisch",
    "country_name_en": "Mesopotamia",
    "country_name_de": "Mesopotamien",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Sumerian",
    "name_de": "Sumerisch",
    "country_name_en": "Mesopotamia",
    "country_name_de": "Mesopotamien",
    "amount_of_people_speaking": 150000
  },
  {
    "name_en": "Hunnic",
    "name_de": "Hunisch",
    "country_name_en": "Hunnic Tribes",
    "country_name_de": "Hunnenstämme",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Lusitanian",
    "name_de": "Lusitanisch",
    "country_name_en": "Lusitania",
    "country_name_de": "Lusitanien",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Elymian",
    "name_de": "Elymisch",
    "country_name_en": "Sicily",
    "country_name_de": "Sizilien",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Messapian",
    "name_de": "Messapisch",
    "country_name_en": "Apulia",
    "country_name_de": "Apulien",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Picene",
    "name_de": "Picenisch",
    "country_name_en": "Picenum",
    "country_name_de": "Picenum",
    "amount_of_people_speaking": 60000
  },
  {
    "name_en": "Lepontic",
    "name_de": "Lepontisch",
    "country_name_en": "Alpine Region",
    "country_name_de": "Alpenregion",
    "amount_of_people_speaking": 70000
  },
  {
    "name_en": "Raetic",
    "name_de": "Rätisch",
    "country_name_en": "Rhaetia",
    "country_name_de": "Rätien",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Venetic (Adriatic Venetic)",
    "name_de": "Venetisch (Adriatisch Venetisch)",
    "country_name_en": "Venetia",
    "country_name_de": "Venetien",
    "amount_of_people_speaking": 80000
  },
  {
    "name_en": "Hurrian",
    "name_de": "Hurrier",
    "country_name_en": "Hurrian States",
    "country_name_de": "Hurritische Staaten",
    "amount_of_people_speaking": 50000
  },
  {
    "name_en": "Minoan",
    "name_de": "Minoisch",
    "country_name_en": "Crete",
    "country_name_de": "Kreta",
    "amount_of_people_speaking": 40000
  },
  {
    "name_en": "Pelasgian",
    "name_de": "Pelasgisch",
    "country_name_en": "Greece",
    "country_name_de": "Griechenland",
    "amount_of_people_speaking": 30000
  },
  {
    "name_en": "Sabean",
    "name_de": "Sabaeisch",
    "country_name_en": "Kingdom of Saba",
    "country_name_de": "Königreich von Saba",
    "amount_of_people_speaking": 100000
  },
  {
    "name_en": "Ge'ez",
    "name_de": "Geʿez",
    "country_name_en": "Kingdom of Aksum",
    "country_name_de": "Königreich von Aksum",
    "amount_of_people_speaking": 150000
  }
]
    """
    )


def get_victorian_languages():
    return json.loads(
        """
        [
  {
    "name_en": "Mandarin Chinese",
    "name_de": "Mandarin-Chinesisch",
    "country_name_en": "China",
    "country_name_de": "China",
    "amount_of_people_speaking": 400000000
  },
  {
    "name_en": "Hindi",
    "name_de": "Hindi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 150000000
  },
  {
    "name_en": "English",
    "name_de": "Englisch",
    "country_name_en": "United Kingdom",
    "country_name_de": "Vereinigtes Königreich",
    "amount_of_people_speaking": 130000000
  },
  {
    "name_en": "Spanish",
    "name_de": "Spanisch",
    "country_name_en": "Spain",
    "country_name_de": "Spanien",
    "amount_of_people_speaking": 100000000
  },
  {
    "name_en": "Russian",
    "name_de": "Russisch",
    "country_name_en": "Russia",
    "country_name_de": "Russland",
    "amount_of_people_speaking": 80000000
  },
  {
    "name_en": "Bengali",
    "name_de": "Bengalisch",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 75000000
  },
  {
    "name_en": "Portuguese",
    "name_de": "Portugiesisch",
    "country_name_en": "Portugal",
    "country_name_de": "Portugal",
    "amount_of_people_speaking": 60000000
  },
  {
    "name_en": "German",
    "name_de": "Deutsch",
    "country_name_en": "Germany",
    "country_name_de": "Deutschland",
    "amount_of_people_speaking": 50000000
  },
  {
    "name_en": "Japanese",
    "name_de": "Japanisch",
    "country_name_en": "Japan",
    "country_name_de": "Japan",
    "amount_of_people_speaking": 40000000
  },
  {
    "name_en": "French",
    "name_de": "Französisch",
    "country_name_en": "France",
    "country_name_de": "Frankreich",
    "amount_of_people_speaking": 35000000
  },
  {
    "name_en": "Italian",
    "name_de": "Italienisch",
    "country_name_en": "Italy",
    "country_name_de": "Italien",
    "amount_of_people_speaking": 30000000
  },
  {
    "name_en": "Turkish",
    "name_de": "Türkisch",
    "country_name_en": "Ottoman Empire",
    "country_name_de": "Osmanisches Reich",
    "amount_of_people_speaking": 25000000
  },
  {
    "name_en": "Vietnamese",
    "name_de": "Vietnamesisch",
    "country_name_en": "Vietnam",
    "country_name_de": "Vietnam",
    "amount_of_people_speaking": 20000000
  },
  {
    "name_en": "Telugu",
    "name_de": "Telugu",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 18000000
  },
  {
    "name_en": "Korean",
    "name_de": "Koreanisch",
    "country_name_en": "Korea",
    "country_name_de": "Korea",
    "amount_of_people_speaking": 15000000
  },
  {
    "name_en": "Tamil",
    "name_de": "Tamil",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 13000000
  },
  {
    "name_en": "Marathi",
    "name_de": "Marathi",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 12000000
  },
  {
    "name_en": "Urdu",
    "name_de": "Urdu",
    "country_name_en": "India",
    "country_name_de": "Indien",
    "amount_of_people_speaking": 11000000
  },
  {
    "name_en": "Persian",
    "name_de": "Persisch",
    "country_name_en": "Persia",
    "country_name_de": "Persien",
    "amount_of_people_speaking": 10000000
  },
  {
    "name_en": "Javanese",
    "name_de": "Javanisch",
    "country_name_en": "Java (Dutch East Indies)",
    "country_name_de": "Java (Niederländisch-Indien)",
    "amount_of_people_speaking": 9500000
  }
]
        """
    )
