# Generated by Django 5.1.5 on 2025-01-29 21:18

import json

from django.db import migrations


def forward(apps, schema_editor):
    Extension = apps.get_model("rules", "Extension")
    Language = apps.get_model("worlds", "Language")

    tirakan = Extension.objects.get(identifier="tirakan")
    for language in get_tirakan_languages():
        l = Language.objects.create(
            name_de=language["name_de"],
            name_en=language["name_en"],
            country_name_de=language["country_name_de"],
            country_name_en=language["country_name_en"],
            amount_of_people_speaking=language["amount_of_people_speaking"],
        )
        l.extensions.add(tirakan)


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0024_auto_20250129_2112"),
    ]

    operations = [migrations.RunPython(forward)]


def get_tirakan_languages():
    return json.loads(
        """
        [
  {
    "name_en": "Asgal",
    "name_de": "Asgal",
    "country_name_en": "Asgoran",
    "country_name_de": "Asgoran",
    "amount_of_people_speaking": 25000000
  },
  {
    "name_en": "Flit",
    "name_de": "Flüglerisch",
    "country_name_en": "Flit",
    "country_name_de": "Flügler",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Gasdarian",
    "name_de": "Gasdarisch",
    "country_name_en": "Gasdaria",
    "country_name_de": "Gasdaria",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "JiRa",
    "name_de": "JiRa",
    "country_name_en": "Al Bah JiRa",
    "country_name_de": "Al Bah JiRa",
    "amount_of_people_speaking": 2200000
  },
  {
    "name_en": "Yava",
    "name_de": "Yava",
    "country_name_en": "Yavon",
    "country_name_de": "Yavon",
    "amount_of_people_speaking": 1200000
  },
  {
    "name_en": "Toranar",
    "name_de": "Toranar",
    "country_name_en": "Toran",
    "country_name_de": "Toran",
    "amount_of_people_speaking": 3200000
  },
  {
    "name_en": "Gas'Danir Slang (Asgal)",
    "name_de": "Gas'Danir Slang (Asgal)",
    "country_name_en": "Gas'Danir",
    "country_name_de": "Gas'Danir",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Yadosiaise",
    "name_de": "Yadosiaise",
    "country_name_en": "Yadosia",
    "country_name_de": "Yadosien",
    "amount_of_people_speaking": 6000000
  },
  {
    "name_en": "Tukladan",
    "name_de": "Tukladan",
    "country_name_en": "Nur'Tuk",
    "country_name_de": "Nur'Tuk",
    "amount_of_people_speaking": 200000
  },
  {
    "name_en": "Merid",
    "name_de": "Meridisch",
    "country_name_en": "Meridian",
    "country_name_de": "Meridian",
    "amount_of_people_speaking": 4500000
  },
  {
    "name_en": "Quitmacha",
    "name_de": "Quitmacha",
    "country_name_en": "Quitaron",
    "country_name_de": "Quitaron",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Hadar",
    "name_de": "Hadar",
    "country_name_en": "Hadewald",
    "country_name_de": "Hadewald",
    "amount_of_people_speaking": 2800000
  },
  {
    "name_en": "Barbarien Dialects",
    "name_de": "Barbariendialekte",
    "country_name_en": "Barbarien",
    "country_name_de": "Barbaren",
    "amount_of_people_speaking": 250000
  },
  {
    "name_en": "Doldag",
    "name_de": "Doldag",
    "country_name_en": "Doldagor (Gargoyles)",
    "country_name_de": "Doldagor (Gargoyles)",
    "amount_of_people_speaking": 1200000
  },
  {
    "name_en": "Ancatir",
    "name_de": "Ancatir",
    "country_name_en": "Ancatir",
    "country_name_de": "Ancatir",
    "amount_of_people_speaking": 800000
  },
  {
    "name_en": "Silkandar",
    "name_de": "Silkandar",
    "country_name_en": "Silkanda",
    "country_name_de": "Silkanda",
    "amount_of_people_speaking": 1200000
  },
  {
    "name_en": "Anscharon",
    "name_de": "Anscharon",
    "country_name_en": "Anscharon",
    "country_name_de": "Anscharon",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Atiarel",
    "name_de": "Atiarel",
    "country_name_en": "Atiarel",
    "country_name_de": "Atiarel",
    "amount_of_people_speaking": 1200000
  },
  {
    "name_en": "Draken",
    "name_de": "Draken",
    "country_name_en": "Dragons",
    "country_name_de": "Drachen",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Lizzard",
    "name_de": "Echsisssch",
    "country_name_en": "Lizard folk",
    "country_name_de": "Echsen",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Fraxut",
    "name_de": "Fraxut",
    "country_name_en": "Fraxut",
    "country_name_de": "Fraxut",
    "amount_of_people_speaking": 1500000
  },
  {
    "name_en": "Xordal",
    "name_de": "Xordal",
    "country_name_en": "Xordai",
    "country_name_de": "Xordai",
    "amount_of_people_speaking": 1000000
  },
  {
    "name_en": "Morgal",
    "name_de": "Morgal",
    "country_name_en": "Morgalas",
    "country_name_de": "Morgalas",
    "amount_of_people_speaking": 2000000
  },
  {
    "name_en": "Minoan",
    "name_de": "Minoisch",
    "country_name_en": "Minoton (Minotaurs)",
    "country_name_de": "Minoton (Minotauren)",
    "amount_of_people_speaking": 5000000
  },
  {
    "name_en": "Katora",
    "name_de": "Katora",
    "country_name_en": "Katora",
    "country_name_de": "Katora",
    "amount_of_people_speaking": 850000
  },
  {
    "name_en": "Chroto'lar",
    "name_de": "Chroto'lar",
    "country_name_en": "Chroto'Chim",
    "country_name_de": "Chroto'Chim",
    "amount_of_people_speaking": 1200000
  },
  {
    "name_en": "Asch-Ta-Ki",
    "name_de": "Asch-Ta-Ki",
    "country_name_en": "Goblins",
    "country_name_de": "Goblins",
    "amount_of_people_speaking": 3000000
  },
  {
    "name_en": "Gnomish",
    "name_de": "Gnomisch",
    "country_name_en": "Gnomes",
    "country_name_de": "Gnomes",
    "amount_of_people_speaking": 2000000
  }
  ]
        """
    )
