# Generated by Django 5.1.5 on 2025-01-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0025_auto_20250129_2118"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "language group",
                "verbose_name_plural": "language groups",
            },
        ),
        migrations.AddField(
            model_name="language",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="worlds.languagegroup",
                verbose_name="group",
            ),
        ),
    ]
