# Generated by Django 5.1.5 on 2025-01-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_auto_20240717_2137"),
        ("characters", "0005_characterattribute_modifier"),
        ("worlds", "0026_languagegroup_language_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homebrew_%(app_label)s_%(class)s_set",
                to="campaigns.campaign",
                verbose_name="homebrew campaign",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="homebrew_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homebrew_%(app_label)s_%(class)s_set",
                to="characters.character",
                verbose_name="homebrew character",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="is_homebrew",
            field=models.BooleanField(default=False, verbose_name="is homebrew"),
        ),
        migrations.AddField(
            model_name="language",
            name="keep_as_homebrew",
            field=models.BooleanField(
                default=False,
                help_text="This was not accepted as general spell and is kept as homebrew.",
                verbose_name="keep as homebrew",
            ),
        ),
    ]
