# Generated by Django 5.1.7 on 2025-03-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0028_auto_20250322_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ("-amount_of_people_speaking",),
                "verbose_name": "language",
                "verbose_name_plural": "languages",
            },
        ),
    ]
