# Generated by Django 5.1.7 on 2025-04-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0029_alter_language_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="show_in_worlds_overview",
            field=models.BooleanField(
                default=False, verbose_name="show in worlds overview"
            ),
        ),
    ]
