# Generated by Django 5.2.1 on 2025-05-22 05:44

import json

from django.db import migrations
from django.template.defaultfilters import slugify


def forward(apps, schema_editor):
    WikiPage = apps.get_model("worlds", "WikiPage")
    EntityCategory = apps.get_model("pantheon", "EntityCategory")
    Entity = apps.get_model("pantheon", "Entity")
    World = apps.get_model("worlds", "World")

    parent = WikiPage.objects.get(slug="gottgleiche-wesen")
    world = World.objects.get(slug="nexus-origins")

    categories = {}
    entity_categories = {}
    for category in get_category_json():
        categories[category["category_key"]] = WikiPage.objects.create(
            parent=parent,
            name_de=category["name_de"],
            name_en=category["name_en"],
            text_de=category["description_de"],
            text_en=category["description_en"],
            slug=slugify(category["name_de"]),
            world=world,
        )
        entity_categories[category["category_key"]] = EntityCategory.objects.create(
            name_de=category["name_de"],
            name_en=category["name_en"],
            description_de=category["description_de"],
            description_en=category["description_en"],
        )

    for entity in get_json():
        wiki_page_obj = WikiPage.objects.create(
            parent=categories[entity["category"]],
            name_de=entity["name_de"],
            name_en=entity["name_en"],
            text_de=entity["description_de"],
            text_en=entity["description_en"],
            slug=slugify(entity["name_de"]),
            world=world,
        )
        Entity.objects.create(
            wiki_page=wiki_page_obj,
            category=entity_categories[entity["category"]],
            name_de=entity["name_de"],
            name_en=entity["name_en"],
            description_de=entity["description_de"],
            description_en=entity["description_en"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0030_world_show_in_worlds_overview"),
    ]

    operations = [migrations.RunPython(forward)]


def get_category_json():
    return json.loads(
        """
    [
    {
        "name_de": "Äußere Götter",
        "name_en": "Outer Gods",
        "category_key": "Outer God",
        "description_de": "Die Äußeren Götter sind mächtige, kosmische Wesen, die jenseits der normalen Raum-Zeit existieren. Sie sind die ultimativen Herrscher des Universums und verkörpern die grundlegenden Kräfte des Chaos, der Zerstörung und der Schöpfung. Diese Wesen sind so mächtig und unbegreiflich, dass ihr bloßer Anblick oder das Wissen um ihre Existenz Wahnsinn auslösen kann. Sie werden oft als unpersönliche und unbegreifliche Kräfte beschrieben, die die Realität nach ihrem Willen formen können.",
        "description_en": "The Outer Gods are powerful, cosmic beings that exist beyond normal space-time. They are the ultimate rulers of the universe and embody the fundamental forces of chaos, destruction, and creation. These beings are so powerful and incomprehensible that their mere sight or the knowledge of their existence can drive one to madness. They are often described as impersonal and incomprehensible forces that can shape reality according to their will."
    },
    {
        "name_de": "Große Alte",
        "name_en": "Great Old Ones",
        "category_key": "Great Old One",
        "description_de": "Die Großen Alten sind uralte und mächtige Wesen, die in den Tiefen der Erde oder in anderen Dimensionen schlummern. Sie sind bekannt für ihre immense Macht und ihren Einfluss auf die menschliche Welt, wenn auch meist auf zerstörerische Weise. Diese Wesen sind oft mit bestimmten Elementen oder Aspekten der Natur verbunden, wie dem Meer, den Träumen oder den Stürmen. Sie werden als unpersönliche und unbegreifliche Kräfte beschrieben, die die Realität nach ihrem Willen formen können.",
        "description_en": "The Great Old Ones are ancient and powerful beings that slumber in the depths of the Earth or in other dimensions. They are known for their immense power and influence on the human world, albeit often in destructive ways. These beings are often associated with specific elements or aspects of nature, such as the sea, dreams, or storms. They are described as impersonal and incomprehensible forces that can shape reality according to their will."
    }
]

    """
    )


def get_json():
    return json.loads(
        """
[
    {
        "name_de": "Cthulhu",
        "name_en": "Cthulhu",
        "description_de": "Cthulhu ist eine uralte kosmische Entität, die als eine der mächtigsten und bekanntesten Gottheiten gilt. Er wird oft als ein riesiges, tentakelgesichtiges Wesen beschrieben, das in der versunkenen Stadt R'lyeh schlummert. Cthulhu verkörpert das Chaos und die Unergründlichkeit des Universums, das den menschlichen Verstand übersteigt. Es heißt, Cthulhu sei ein Symbol für die Unbedeutsamkeit der Menschheit im Angesicht des unermesslichen Kosmos. Seine bloße Existenz und das Wissen um ihn können bei Menschen Wahnsinn auslösen. Er wird oft als eine Art Gottheit verehrt, die in Träumen und Visionen erscheint und die Grenzen der Realität verwischt. Cthulhu ist Teil eines Pantheons außerirdischer Wesen, die als die 'Großen Alten' bekannt sind. Diese Wesen existieren außerhalb der normalen Raum-Zeit und haben die Macht, die Realität nach ihrem Willen zu formen. Cthulhu ist einer der wenigen Großen Alten, die direkt mit der menschlichen Welt interagieren, wenn auch meist auf zerstörerische Weise.",
        "description_en": "Cthulhu is an ancient cosmic entity regarded as one of the most powerful and well-known deities. He is often depicted as a massive, tentacle-faced being slumbering in the sunken city of R'lyeh. Cthulhu embodies the chaos and unfathomability of the universe, which surpasses human comprehension. It is said that Cthulhu is a symbol of the insignificance of humanity in the face of the vast cosmos. His mere existence and the knowledge of him can drive humans to madness. He is often worshipped as a kind of deity who appears in dreams and visions, blurring the boundaries of reality. Cthulhu is part of a pantheon of alien beings known as the 'Great Old Ones.' These beings exist outside normal space-time and have the power to shape reality according to their will. Cthulhu is one of the few Great Old Ones who directly interact with the human world, albeit usually in a destructive manner.",
        "category": "Great Old One",
        "prompt": "A massive, tentacle-faced cosmic entity slumbering in the sunken city of R'lyeh, embodying chaos and the unfathomable universe."
    },
    {
        "name_de": "Nyarlathotep",
        "name_en": "Nyarlathotep",
        "description_de": "Nyarlathotep ist eine der komplexesten und vielseitigsten Gottheiten. Er wird oft als der 'Bote der Äußeren Götter' beschrieben und nimmt viele verschiedene Formen an, um die Menschheit zu täuschen und zu manipulieren. Im Gegensatz zu anderen Gottheiten interagiert Nyarlathotep direkt und häufig mit den Menschen, oft mit böswilligen Absichten. Nyarlathotep verkörpert Täuschung, Wahnsinn und Zerstörung. Er erscheint in verschiedenen Gestalten, von einem ägyptischen Pharao bis hin zu einem dunklen, schattenhaften Wesen. Seine Anwesenheit bringt oft Chaos und Verderben, und er genießt es, die Schwächen und Ängste der Menschen auszunutzen. In vielen Geschichten dient Nyarlathotep als Antagonist, der die Pläne der Äußeren Götter ausführt. Er ist bekannt für seine grausamen Spiele mit den Menschen, die oft in Tragödie und Wahnsinn enden. Nyarlathotep ist eine der wenigen Gottheiten, die aktiv die menschliche Welt beeinflussen und verändern.",
        "description_en": "Nyarlathotep is one of the most complex and versatile deities. He is often described as the 'Messenger of the Outer Gods' and takes on many different forms to deceive and manipulate humanity. Unlike other deities, Nyarlathotep interacts directly and frequently with humans, often with malicious intent. Nyarlathotep embodies deception, madness, and destruction. He appears in various forms, from an Egyptian pharaoh to a dark, shadowy being. His presence often brings chaos and ruin, and he enjoys exploiting the weaknesses and fears of humans. In many stories, Nyarlathotep serves as an antagonist who carries out the plans of the Outer Gods. He is known for his cruel games with humans, which often end in tragedy and madness. Nyarlathotep is one of the few deities who actively influence and alter the human world.",
        "category": "Outer God",
        "prompt": "A deceptive and shadowy messenger of the Outer Gods, appearing in various forms to manipulate and bring chaos to humanity."
    },
    {
        "name_de": "Azathoth",
        "name_en": "Azathoth",
        "description_de": "Azathoth ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'Blinde Idiotengott' beschrieben, der im Zentrum des Universums thront. Azathoth ist eine verkörperte Form des Chaos und der Zerstörung, die das gesamte Universum beeinflusst. Azathoth wird als ein riesiges, amorphes Wesen beschrieben, das von einer Horde von Flöten begleitet wird, deren Musik die Realität selbst verzerrt. Er ist so mächtig, dass sein bloßer Anblick Wahnsinn auslösen kann. Azathoth ist der Herrscher über die Äußeren Götter und die ultimative Quelle aller Existenz. Azathoth ist die ultimative Macht, die das Schicksal des Universums bestimmt. Er ist ein Symbol für die Unergründlichkeit und die Unberechenbarkeit des Kosmos. Azathoth wird oft als eine unpersönliche und unbegreifliche Kraft dargestellt, die jenseits des menschlichen Verständnisses liegt.",
        "description_en": "Azathoth is one of the most powerful and mysterious Outer Gods. He is often described as the 'Blind Idiot God' who sits at the center of the universe. Azathoth is an embodied form of chaos and destruction that influences the entire universe. Azathoth is described as a massive, amorphous being accompanied by a horde of flutes whose music distorts reality itself. He is so powerful that his mere sight can drive one to madness. Azathoth is the ruler of the Outer Gods and the ultimate source of all existence. Azathoth is the ultimate power that determines the fate of the universe. He is a symbol of the unfathomability and unpredictability of the cosmos. Azathoth is often depicted as an impersonal and incomprehensible force beyond human understanding.",
        "category": "Outer God",
        "prompt": "A massive, amorphous being at the center of the universe, accompanied by a horde of flutes distorting reality."
    },
    {
        "name_de": "Yog-Sothoth",
        "name_en": "Yog-Sothoth",
        "description_de": "Yog-Sothoth ist einer der mächtigsten Äußeren Götter. Er wird oft als der 'All-in-One' und der 'Einer-in-Allen' beschrieben, der die gesamte Raum-Zeit durchdringt. Yog-Sothoth ist eine verkörperte Form des Wissens und der Erkenntnis, die alle Geheimnisse des Universums kennt. Yog-Sothoth wird als ein riesiges, kugelförmiges Wesen beschrieben, das aus unzähligen Augen und Mündern besteht. Er ist der Hüter der Tore zu anderen Dimensionen und hat die Macht, die Realität nach seinem Willen zu formen. Yog-Sothoth ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Yog-Sothoth ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Universums und die Grenzen des menschlichen Wissens. Yog-Sothoth wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Yog-Sothoth is one of the most powerful Outer Gods. He is often described as the 'All-in-One' and the 'One-in-All,' who permeates all of space-time. Yog-Sothoth is an embodied form of knowledge and understanding, knowing all the secrets of the universe. Yog-Sothoth is described as a massive, spherical being composed of countless eyes and mouths. He is the keeper of the gates to other dimensions and has the power to shape reality according to his will. Yog-Sothoth is an impersonal and incomprehensible force beyond human understanding. Yog-Sothoth is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of the universe and the limits of human knowledge. Yog-Sothoth is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, spherical being composed of countless eyes and mouths, permeating all of space-time."
    },
    {
        "name_de": "Shub-Niggurath",
        "name_en": "Shub-Niggurath",
        "description_de": "Shub-Niggurath ist eine der ältesten und fruchtbarsten Gottheiten. Sie wird oft als die 'Schwarze Ziege der Wälder mit den tausend Jungen' beschrieben. Shub-Niggurath ist eine verkörperte Form der Fruchtbarkeit und des Wachstums, die mit der Natur und den wilden Orten der Welt verbunden ist. Shub-Niggurath wird als ein riesiges, tentakelartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Sie ist die Mutter vieler anderer Gottheiten und Wesen. Shub-Niggurath ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Shub-Niggurath ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Sie ist ein Symbol für die Unergründlichkeit der Natur und die Grenzen des menschlichen Wissens. Shub-Niggurath wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Shub-Niggurath is one of the oldest and most fertile deities. She is often described as the 'Black Goat of the Woods with a Thousand Young.' Shub-Niggurath is an embodied form of fertility and growth, associated with nature and the wild places of the world. Shub-Niggurath is described as a massive, tentacle-like being accompanied by a horde of creatures. She is the mother of many other deities and beings. Shub-Niggurath is an impersonal and incomprehensible force beyond human understanding. Shub-Niggurath is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. She is a symbol of the unfathomability of nature and the limits of human knowledge. Shub-Niggurath is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, tentacle-like being accompanied by a horde of creatures, embodying fertility and the wild places of the world."
    },
    {
        "name_de": "Dagon",
        "name_en": "Dagon",
        "description_de": "Dagon ist eine der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Herr der Tiefen' beschrieben, der in den dunklen und unheimlichen Tiefen des Ozeans lebt. Dagon ist eine verkörperte Form des Meeres und der Geheimnisse, die es birgt. Dagon wird als ein riesiges, fischartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Tiefen des Ozeans und hat die Macht, die Gezeiten und die Strömungen zu kontrollieren. Dagon ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Dagon ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Ozeans und die Grenzen des menschlichen Wissens. Dagon wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Dagon is one of the oldest and most powerful deities. He is often described as the 'Lord of the Depths,' who dwells in the dark and eerie depths of the ocean. Dagon is an embodied form of the sea and the mysteries it holds. Dagon is described as a massive, fish-like being accompanied by a horde of creatures. He is the ruler of the ocean depths and has the power to control the tides and currents. Dagon is an impersonal and incomprehensible force beyond human understanding. Dagon is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of the ocean and the limits of human knowledge. Dagon is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, fish-like being dwelling in the dark depths of the ocean, ruling over the tides and currents."
    },
    {
        "name_de": "Hastur",
        "name_en": "Hastur",
        "description_de": "Hastur ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'König in Gelb' beschrieben, der in der fernen Stadt Carcosa thront. Hastur ist eine verkörperte Form des Wahnsinns und der Zerstörung, die die menschliche Psyche beeinflusst. Hastur wird als ein riesiges, tentakelartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Träume und Visionen der Menschen und hat die Macht, die Realität nach seinem Willen zu formen. Hastur ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Hastur ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Wahnsinns und die Grenzen des menschlichen Wissens. Hastur wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Hastur is one of the most powerful and mysterious Outer Gods. He is often described as the 'King in Yellow,' who sits on the throne in the distant city of Carcosa. Hastur is an embodied form of madness and destruction that influences the human psyche. Hastur is described as a massive, tentacle-like being accompanied by a horde of creatures. He is the ruler of the dreams and visions of humans and has the power to shape reality according to his will. Hastur is an impersonal and incomprehensible force beyond human understanding. Hastur is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of madness and the limits of human knowledge. Hastur is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, tentacle-like being ruling over dreams and visions, embodying madness and destruction."
    },
    {
        "name_de": "Yig",
        "name_en": "Yig",
        "description_de": "Yig ist einer der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Vater der Schlangen' beschrieben, der in den dunklen und unheimlichen Tiefen der Erde lebt. Yig ist eine verkörperte Form der Schlangen und der Geheimnisse, die sie bewachen. Yig wird als ein riesiges, schlangenartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Schlangen und hat die Macht, die Natur und die Tiere zu kontrollieren. Yig ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Yig ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit der Natur und die Grenzen des menschlichen Wissens. Yig wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Yig is one of the oldest and most powerful deities. He is often described as the 'Father of Serpents,' who dwells in the dark and eerie depths of the Earth. Yig is an embodied form of snakes and the mysteries they guard. Yig is described as a massive, serpent-like being accompanied by a horde of creatures. He is the ruler of the snakes and has the power to control nature and animals. Yig is an impersonal and incomprehensible force beyond human understanding. Yig is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of nature and the limits of human knowledge. Yig is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, serpent-like being dwelling in the dark depths of the Earth, ruling over snakes and nature."
    },
    {
        "name_de": "Tsathoggua",
        "name_en": "Tsathoggua",
        "description_de": "Tsathoggua ist einer der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Schlafende Gott' beschrieben, der in den dunklen und unheimlichen Tiefen der Erde schlummert. Tsathoggua ist eine verkörperte Form des Schlafes und der Träume, die die menschliche Psyche beeinflusst. Tsathoggua wird als ein riesiges, froschartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Träume und Visionen der Menschen und hat die Macht, die Realität nach seinem Willen zu formen. Tsathoggua ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Tsathoggua ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Schlafes und die Grenzen des menschlichen Wissens. Tsathoggua wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Tsathoggua is one of the oldest and most powerful deities. He is often described as the 'Sleeping God,' who slumbers in the dark and eerie depths of the Earth. Tsathoggua is an embodied form of sleep and dreams that influences the human psyche. Tsathoggua is described as a massive, frog-like being accompanied by a horde of creatures. He is the ruler of the dreams and visions of humans and has the power to shape reality according to his will. Tsathoggua is an impersonal and incomprehensible force beyond human understanding. Tsathoggua is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of sleep and the limits of human knowledge. Tsathoggua is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, frog-like being dwelling in the dark depths of the Earth, ruling over dreams and visions."
    },
    {
        "name_de": "Ubbo-Sathla",
        "name_en": "Ubbo-Sathla",
        "description_de": "Ubbo-Sathla ist einer der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Ursprung des Lebens' beschrieben, der in den dunklen und unheimlichen Tiefen der Erde lebt. Ubbo-Sathla ist eine verkörperte Form des Lebens und der Evolution, die die menschliche Existenz beeinflusst. Ubbo-Sathla wird als ein riesiges, amöbenartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über das Leben und die Evolution und hat die Macht, die Natur und die Tiere zu kontrollieren. Ubbo-Sathla ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Ubbo-Sathla ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Lebens und die Grenzen des menschlichen Wissens. Ubbo-Sathla wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Ubbo-Sathla is one of the oldest and most powerful deities. He is often described as the 'Source of Life,' who dwells in the dark and eerie depths of the Earth. Ubbo-Sathla is an embodied form of life and evolution that influences human existence. Ubbo-Sathla is described as a massive, amoeba-like being accompanied by a horde of creatures. He is the ruler of life and evolution and has the power to control nature and animals. Ubbo-Sathla is an impersonal and incomprehensible force beyond human understanding. Ubbo-Sathla is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of life and the limits of human knowledge. Ubbo-Sathla is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, amoeba-like being dwelling in the dark depths of the Earth, ruling over life and evolution."
    },
    {
        "name_de": "Nyogtha",
        "name_en": "Nyogtha",
        "description_de": "Nyogtha ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'Dunkle Wanderer' beschrieben, der durch die unendlichen Weiten des Kosmos wandert. Nyogtha ist eine verkörperte Form des Chaos und der Zerstörung, die das gesamte Universum beeinflusst. Nyogtha wird als ein riesiges, schattenhaftes Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Dunkelheit und die Leere des Kosmos und hat die Macht, die Realität nach seinem Willen zu formen. Nyogtha ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Nyogtha ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Kosmos und die Grenzen des menschlichen Wissens. Nyogtha wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Nyogtha is one of the most powerful and mysterious Outer Gods. He is often described as the 'Dark Wanderer,' who roams through the infinite expanse of the cosmos. Nyogtha is an embodied form of chaos and destruction that influences the entire universe. Nyogtha is described as a massive, shadowy being accompanied by a horde of creatures. He is the ruler of the darkness and the void of the cosmos and has the power to shape reality according to his will. Nyogtha is an impersonal and incomprehensible force beyond human understanding. Nyogtha is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of the cosmos and the limits of human knowledge. Nyogtha is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, shadowy being wandering through the infinite expanse of the cosmos, embodying chaos and destruction."
    },
    {
        "name_de": "Yibb-Tstll",
        "name_en": "Yibb-Tstll",
        "description_de": "Yibb-Tstll ist einer der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Hüter der Geheimnisse' beschrieben, der in den dunklen und unheimlichen Tiefen des Kosmos lebt. Yibb-Tstll ist eine verkörperte Form des Wissens und der Geheimnisse, die das Universum birgt. Yibb-Tstll wird als ein riesiges, kristallines Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Hüter der Geheimnisse des Kosmos und hat die Macht, die Realität nach seinem Willen zu formen. Yibb-Tstll ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Yibb-Tstll ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Wissens und die Grenzen des menschlichen Wissens. Yibb-Tstll wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Yibb-Tstll is one of the oldest and most powerful deities. He is often described as the 'Keeper of Secrets,' who dwells in the dark and eerie depths of the cosmos. Yibb-Tstll is an embodied form of knowledge and the secrets that the universe holds. Yibb-Tstll is described as a massive, crystalline being accompanied by a horde of creatures. He is the keeper of the secrets of the cosmos and has the power to shape reality according to his will. Yibb-Tstll is an impersonal and incomprehensible force beyond human understanding. Yibb-Tstll is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of knowledge and the limits of human understanding. Yibb-Tstll is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, crystalline being dwelling in the dark depths of the cosmos, guarding the secrets of the universe."
    },
    {
        "name_de": "Zhar",
        "name_en": "Zhar",
        "description_de": "Zhar ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'Herr der Träume' beschrieben, der in den unendlichen Weiten des Kosmos wandert. Zhar ist eine verkörperte Form der Träume und Visionen, die die menschliche Psyche beeinflusst. Zhar wird als ein riesiges, nebelhaftes Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Träume und Visionen der Menschen und hat die Macht, die Realität nach seinem Willen zu formen. Zhar ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Zhar ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit der Träume und die Grenzen des menschlichen Wissens. Zhar wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Zhar is one of the most powerful and mysterious Outer Gods. He is often described as the 'Lord of Dreams,' who roams through the infinite expanse of the cosmos. Zhar is an embodied form of dreams and visions that influences the human psyche. Zhar is described as a massive, misty being accompanied by a horde of creatures. He is the ruler of the dreams and visions of humans and has the power to shape reality according to his will. Zhar is an impersonal and incomprehensible force beyond human understanding. Zhar is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of dreams and the limits of human knowledge. Zhar is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, misty being wandering through the infinite expanse of the cosmos, ruling over dreams and visions."
    },
    {
        "name_de": "Lloigor",
        "name_en": "Lloigor",
        "description_de": "Lloigor ist einer der ältesten und mächtigsten Gottheiten. Er wird oft als der 'Herr der Stürme' beschrieben, der in den dunklen und unheimlichen Tiefen des Kosmos lebt. Lloigor ist eine verkörperte Form der Stürme und der Naturgewalten, die die menschliche Existenz beeinflusst. Lloigor wird als ein riesiges, wirbelsturmartiges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Stürme und die Naturgewalten und hat die Macht, die Natur und die Elemente zu kontrollieren. Lloigor ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Lloigor ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit der Naturgewalten und die Grenzen des menschlichen Wissens. Lloigor wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Lloigor is one of the oldest and most powerful deities. He is often described as the 'Lord of Storms,' who dwells in the dark and eerie depths of the cosmos. Lloigor is an embodied form of storms and the forces of nature that influence human existence. Lloigor is described as a massive, hurricane-like being accompanied by a horde of creatures. He is the ruler of the storms and the forces of nature and has the power to control nature and the elements. Lloigor is an impersonal and incomprehensible force beyond human understanding. Lloigor is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of the forces of nature and the limits of human knowledge. Lloigor is often depicted as a source of inspiration and madness.",
        "category": "Great Old One",
        "prompt": "A massive, hurricane-like being dwelling in the dark depths of the cosmos, ruling over storms and the forces of nature."
    },
    {
        "name_de": "Ithaqua",
        "name_en": "Ithaqua",
        "description_de": "Ithaqua ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'Wanderer der Winde' beschrieben, der durch die unendlichen Weiten des Kosmos wandert. Ithaqua ist eine verkörperte Form der Winde und der Stürme, die die menschliche Psyche beeinflusst. Ithaqua wird als ein riesiges, geisterhaftes Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über die Winde und die Stürme und hat die Macht, die Realität nach seinem Willen zu formen. Ithaqua ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Ithaqua ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit der Winde und die Grenzen des menschlichen Wissens. Ithaqua wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Ithaqua is one of the most powerful and mysterious Outer Gods. He is often described as the 'Wind Walker,' who roams through the infinite expanse of the cosmos. Ithaqua is an embodied form of the winds and storms that influence the human psyche. Ithaqua is described as a massive, ghostly being accompanied by a horde of creatures. He is the ruler of the winds and storms and has the power to shape reality according to his will. Ithaqua is an impersonal and incomprehensible force beyond human understanding. Ithaqua is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of the winds and the limits of human knowledge. Ithaqua is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, ghostly being wandering through the infinite expanse of the cosmos, ruling over the winds and storms."
    },
    {
        "name_de": "Cthugha",
        "name_en": "Cthugha",
        "description_de": "Cthugha ist einer der mächtigsten und geheimnisvollsten Äußeren Götter. Er wird oft als der 'Herr des Feuers' beschrieben, der in den unendlichen Weiten des Kosmos wandert. Cthugha ist eine verkörperte Form des Feuers und der Zerstörung, die die menschliche Psyche beeinflusst. Cthugha wird als ein riesiges, feuriges Wesen beschrieben, das von einer Horde von Kreaturen begleitet wird. Er ist der Herrscher über das Feuer und die Zerstörung und hat die Macht, die Realität nach seinem Willen zu formen. Cthugha ist eine unpersönliche und unbegreifliche Kraft, die jenseits des menschlichen Verständnisses liegt. Cthugha ist eine der wenigen Gottheiten, die direkt mit den Menschen interagieren, wenn auch meist auf rätselhafte und unheimliche Weise. Er ist ein Symbol für die Unergründlichkeit des Feuers und die Grenzen des menschlichen Wissens. Cthugha wird oft als eine Quelle der Inspiration und des Wahnsinns dargestellt.",
        "description_en": "Cthugha is one of the most powerful and mysterious Outer Gods. He is often described as the 'Lord of Fire,' who roams through the infinite expanse of the cosmos. Cthugha is an embodied form of fire and destruction that influences the human psyche. Cthugha is described as a massive, fiery being accompanied by a horde of creatures. He is the ruler of fire and destruction and has the power to shape reality according to his will. Cthugha is an impersonal and incomprehensible force beyond human understanding. Cthugha is one of the few deities who directly interact with humans, albeit often in mysterious and eerie ways. He is a symbol of the unfathomability of fire and the limits of human knowledge. Cthugha is often depicted as a source of inspiration and madness.",
        "category": "Outer God",
        "prompt": "A massive, fiery being wandering through the infinite expanse of the cosmos, ruling over fire and destruction."
    }
]

    """
    )
