# Generated by Django 5.2.1 on 2025-05-22 10:46

from django.db import migrations


def forward(apps, schema_editor):
    EntityCategory = apps.get_model("pantheon", "EntityCategory")

    for category in EntityCategory.objects.filter(
        name_en__in=["Outer Gods", "Great Old Ones"]
    ):
        for entity in category.entity_set.all():
            entity.description_de = entity.wiki_page.text_de
            entity.description_en = entity.wiki_page.text_en
            entity.image.save(
                entity.wiki_page.image.name, entity.wiki_page.image, save=True
            )
            entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0031_auto_20250522_0544"),
    ]

    operations = [migrations.RunPython(forward)]
