# Generated by Django 5.2.4 on 2025-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0032_auto_20250522_1046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipage",
            name="actions_heading_de",
        ),
        migrations.RemoveField(
            model_name="wikipage",
            name="actions_heading_en",
        ),
        migrations.RemoveField(
            model_name="wikipage",
            name="exclude_from_foe_search",
        ),
        migrations.RemoveField(
            model_name="world",
            name="foe_overview_wiki_page",
        ),
    ]
