# Generated by Django 5.2.6 on 2025-09-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0033_remove_wikipage_actions_heading_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="dns_domain_name",
            field=models.CharField(
                blank=True,
                help_text="This world is set as default if the given dns domain name is requested",
                max_length=120,
                null=True,
                verbose_name="dns domain name",
            ),
        ),
        migrations.AddField(
            model_name="world",
            name="session_cookie_domain",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="session cookie domain",
            ),
        ),
    ]
