# Generated by Django 5.2.6 on 2025-09-29 01:21

from django.db import migrations


def forward(apps, schema_editor):
    WorldSiteConfiguration = apps.get_model("worlds", "WorldSiteConfiguration")

    for w in WorldSiteConfiguration.objects.all():
        w.world.dns_domain_name = w.dns_domain_name
        w.world.session_cookie_domain = w.session_cookie_domain
        w.world.save()


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0034_world_dns_domain_name_world_session_cookie_domain"),
    ]

    operations = [migrations.RunPython(forward)]
