# Generated by Django 5.2.6 on 2025-09-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0035_move_domains_to_world"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorldSiteConfiguration",
        ),
    ]
