# Generated by Django 5.2.9 on 2025-12-23 14:32

import phasesix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0037_language_created_at_language_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipage",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="wikipageimage",
            name="image",
            field=models.ImageField(
                max_length=256,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=phasesix.models.image_upload_path,
                verbose_name="image",
            ),
        ),
    ]
