# Generated by Django 6.0.7 on 2026-07-14

from django.db import migrations, models


PHASESIX_BACKGROUND = "img/pdf_backgrounds/phasesix-background.png"
TIRAKAN_BACKGROUND = "img/pdf_backgrounds/tirakan-background.png"
NEXUS_BACKGROUND = "img/pdf_backgrounds/nexus-background.png"


def assign_pdf_backgrounds(apps, schema_editor):
    World = apps.get_model("worlds", "World")

    World.objects.filter(scss_file="theme/tirakan.scss").update(
        pdf_background=TIRAKAN_BACKGROUND
    )
    World.objects.filter(scss_file="theme/nexus.scss").update(
        pdf_background=NEXUS_BACKGROUND
    )


class Migration(migrations.Migration):
    dependencies = [
        ("worlds", "0039_wikipage_image_focal_x_wikipage_image_focal_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="pdf_background",
            field=models.CharField(
                choices=[
                    (PHASESIX_BACKGROUND, "PhaseSix"),
                    (TIRAKAN_BACKGROUND, "Tirakan"),
                    (NEXUS_BACKGROUND, "Nexus"),
                ],
                default=PHASESIX_BACKGROUND,
                max_length=80,
                verbose_name="PDF background",
            ),
        ),
        migrations.RunPython(assign_pdf_backgrounds, migrations.RunPython.noop),
    ]
