# Generated by Django 4.1.9 on 2023-06-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0001_initial"),
        ("campaigns", "0002_initial"),
        ("armory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponmodificationattributechange",
            name="status_effect",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.statuseffect",
                verbose_name="status effect",
            ),
        ),
        migrations.AddField(
            model_name="weaponmodificationattributechange",
            name="weapon_modification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.weaponmodification",
            ),
        ),
        migrations.AddField(
            model_name="weaponmodification",
            name="available_for_weapon_types",
            field=models.ManyToManyField(to="armory.weapontype"),
        ),
        migrations.AddField(
            model_name="weaponmodification",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AddField(
            model_name="weaponmodification",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.weaponmodificationtype",
            ),
        ),
        migrations.AddField(
            model_name="weaponattackmode",
            name="attack_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.attackmode",
                verbose_name="Attack Mode",
            ),
        ),
        migrations.AddField(
            model_name="weaponattackmode",
            name="weapon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.weapon",
                verbose_name="Weapon",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AddField(
            model_name="weapon",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.weapontype",
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="riotgear",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.riotgeartype",
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.attribute",
                verbose_name="attribute for usage",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="extensions",
            field=models.ManyToManyField(to="rules.extension"),
        ),
        migrations.AddField(
            model_name="item",
            name="homebrew_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="knowledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.knowledge",
                verbose_name="knowledge for usage",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.skill",
                verbose_name="skill for usage",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.itemtype",
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="currencymapunit",
            name="currency_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.currencymap"
            ),
        ),
    ]
