# Generated by Django 5.0.3 on 2024-03-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0007_auto_20240315_2201"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weapon",
            name="encumbrance",
        ),
        migrations.AlterField(
            model_name="weaponmodificationattributechange",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("capacity", "Capacity"),
                    ("recoil_compensation", "Recoil compensation"),
                    ("actions_to_ready", "Actions to ready"),
                    ("crit_minimum_roll", "Crit minimum roll"),
                    ("damage_potential", "Damage potential"),
                    ("piercing", "Piercing"),
                    ("concealment", "Concealment"),
                    ("reload_actions", "Reload actions"),
                    ("range_meter", "Range (meter)"),
                ],
                max_length=40,
                verbose_name="attribute",
            ),
        ),
    ]
