# Generated by Django 5.1 on 2024-08-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0007_alter_currencymapunit_fa_icon_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="riotgeartype",
            name="is_shield",
            field=models.BooleanField(default=False, verbose_name="is shield"),
        ),
    ]
