# Generated by Django 5.0.3 on 2024-03-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0008_remove_weapon_encumbrance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponModificationKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0, verbose_name="value")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.keyword"
                    ),
                ),
                (
                    "weapon_modification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.weaponmodification",
                    ),
                ),
            ],
        ),
    ]
