# Generated by Django 5.1.1 on 2024-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0009_keyword_remove_weapon_encumbrance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="identifier",
            field=models.CharField(
                default="", max_length=20, unique=True, verbose_name="identifier"
            ),
            preserve_default=False,
        ),
    ]
