# Generated by Django 5.0.3 on 2024-03-16 14:34

from django.db import migrations


def forward(apps, schema_editor):
    WeaponModification = apps.get_model("armory", "WeaponModification")
    WeaponKeyword = apps.get_model("armory", "WeaponKeyword")
    Keyword = apps.get_model("armory", "Keyword")


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0009_weaponmodificationkeyword"),
    ]

    operations = [migrations.RunPython(forward)]
