# Generated by Django 5.1.1 on 2024-10-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0008_riotgeartype_is_shield"),
        ("armory", "0010_auto_20240316_1434"),
    ]

    operations = []
