# Generated by Django 5.1.1 on 2024-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0013_auto_20241003_1449"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weapon",
            name="actions_to_ready",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="concealment",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="crit_minimum_roll",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="damage_potential",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="piercing",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="range_meter",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="recoil_compensation",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="reload_actions",
        ),
        migrations.AddField(
            model_name="weapon",
            name="attack_modes",
            field=models.ManyToManyField(
                to="armory.attackmode", verbose_name="attack modes"
            ),
        ),
        migrations.DeleteModel(
            name="WeaponModificationAttributeChange",
        ),
    ]
