# Generated by Django 5.1.1 on 2024-10-03 17:18

from django.db import migrations


def forwards_func(apps, schema_editor):
    Weapon = apps.get_model("armory", "Weapon")
    for w in Weapon.objects.all():
        for wa in w.weaponattackmode_set.all():
            w.attack_modes.add(wa.attack_mode)


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0014_remove_weapon_actions_to_ready_and_more"),
    ]

    operations = [migrations.RunPython(forwards_func)]
