# Generated by Django 5.1.2 on 2024-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0020_remove_protectiontype_fa_icon_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protectiontype",
            name="rules",
        ),
        migrations.AlterField(
            model_name="protectiontype",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("text-white", "White"),
                    ("text-success", "Success"),
                    ("text-primary", "Primary"),
                    ("text-secondary", "Secondary"),
                    ("text-warning", "Warning"),
                    ("text-danger", "Danger"),
                ],
                default="text-primary",
                max_length=30,
            ),
        ),
    ]
