# Generated by Django 5.1.2 on 2024-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0023_auto_20241102_1753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectiontype",
            name="icon_class",
            field=models.CharField(
                choices=[
                    ("gi-delapouite-cross-shield", "Cross Shield"),
                    ("gi-delapouite-dice-shield", "Dice Shield"),
                    ("gi-delapouite-dragon-shield", "Dragon Shield"),
                    ("gi-delapouite-griffin-shield", "Griffin Shield"),
                    ("gi-delapouite-healing-shield", "Healing Shield"),
                    ("gi-delapouite-heart-shield", "Heart Shield"),
                    ("gi-delapouite-ribbon-shield", "Ribbon Shield"),
                    ("gi-delapouite-roman-shield", "Roman Shield"),
                    ("gi-delapouite-spiked-shield", "Spiked Shield"),
                    ("gi-delapouite-templar-shield", "Templar Shield"),
                    ("gi-delapouite-temporary-shield", "Temporary Shield"),
                    ("gi-delapouite-tribal-shield", "Tribal Shield"),
                    ("gi-delapouite-trident-shield", "Trident Shield"),
                    ("gi-delapouite-vibrating-shield", "Vibrating Shield"),
                    ("gi-delapouite-viking-shield", "Viking Shield"),
                ],
                default="fas fa-shield-alt",
                max_length=50,
                verbose_name="FA Icon Class",
            ),
        ),
    ]
