# Generated by Django 3.2.7 on 2021-10-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0061_statuseffect_is_active'),
        ('armory', '0034_remove_riotgear_protection_explosive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='status_effect',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.statuseffect', verbose_name='status effect'),
        ),
    ]
