# Generated by Django 3.2.7 on 2021-11-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0035_alter_weaponmodificationattributechange_status_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyMapUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('color_class', models.CharField(choices=[('White', 'text-white'), ('Success', 'text-success'), ('Primary', 'text-primary'), ('Secondary', 'text-secondary'), ('Warning', 'text-warning'), ('Danger', 'text-danger')], default='text-warning', max_length=30)),
                ('fa_icon_class', models.CharField(default='fas fa-coins', max_length=30, verbose_name='FA Icon Class')),
                ('currency_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.currencymap')),
            ],
        ),
    ]
