# Generated by Django 3.2.7 on 2021-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0036_currencymap_currencymapunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymapunit',
            name='color_class',
            field=models.CharField(choices=[('text-white', 'White'), ('text-success', 'Success'), ('text-primary', 'Primary'), ('text-secondary', 'Secondary'), ('text-warning', 'Warning'), ('text-danger', 'Danger')], default='text-warning', max_length=30),
        ),
        migrations.AlterField(
            model_name='currencymapunit',
            name='fa_icon_class',
            field=models.CharField(choices=[('fas fa-coins', 'Coins'), ('fas fa-euro-sign', 'Euro'), ('fas fa-dollar-sign', 'Dollar'), ('fas fa-rupee-sign', 'Rupee'), ('fas fa-pound-sign', 'Pound'), ('fas fa-lira-sign', 'Lira'), ('fas fa-shekel-sign', 'Shekel'), ('fas fa-yen-sign', 'Yen'), ('fas fa-won-sign', 'Won')], default='fas fa-coins', max_length=30, verbose_name='FA Icon Class'),
        ),
    ]
