# Generated by Django 3.2.9 on 2021-11-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0037_auto_20211110_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencymapunit',
            options={'get_latest_by': ('id',)},
        ),
    ]
