# Generated by Django 3.2.9 on 2021-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0038_alter_currencymapunit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dice_roll_string',
            field=models.CharField(blank=True, help_text='Shows a roll button at the item if not empty.', max_length=10, null=True, verbose_name='dice role string'),
        ),
    ]
