# Generated by Django 3.2.9 on 2022-01-13 21:40

from django.db import migrations


def wm_attribute_change(apps, schema_editor):
    WMAC = apps.get_model('armory', 'WeaponModificationAttributeChange')
    for w in WMAC.objects.all():
        if w.attribute == 'penetration':
            w.attribute = 'piercing'
            w.save()


class Migration(migrations.Migration):
    dependencies = [
        ('armory', '0039_item_dice_roll_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='penetration',
            new_name='piercing',
        ),
        migrations.RunPython(wm_attribute_change)
    ]
