# Generated by Django 3.2.9 on 2022-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0040_auto_20220113_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='piercing',
            field=models.IntegerField(default=0, verbose_name='piercing'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('wounds', 'Bonus wounds'), ('bonus_dice', 'Bonus dice'), ('piercing', 'Piercing'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
