# Generated by Django 3.2.12 on 2022-03-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0078_auto_20220107_2205'),
        ('armory', '0041_auto_20220120_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.skill', verbose_name='skill for usage'),
        ),
    ]
