# Generated by Django 3.2.12 on 2022-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0042_item_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponmodification',
            name='rules_de',
            field=models.TextField(blank=True, help_text='Rules for this weapon modification. May be blank if only attribute changes apply.', null=True, verbose_name='rules'),
        ),
        migrations.AddField(
            model_name='weaponmodification',
            name='rules_en',
            field=models.TextField(blank=True, help_text='Rules for this weapon modification. May be blank if only attribute changes apply.', null=True, verbose_name='rules'),
        ),
    ]
