# Generated by Django 3.2.12 on 2022-04-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_auto_20220410_1919'),
        ('armory', '0043_auto_20220331_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.knowledge', verbose_name='knowledge for usage'),
        ),
    ]
