# Generated by Django 3.2.12 on 2022-04-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_auto_20220410_1919'),
        ('armory', '0044_item_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.attribute', verbose_name='attribute for usage'),
        ),
    ]
