# Generated by Django 3.2.12 on 2022-04-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_epoch'),
        ('armory', '0045_item_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='homebrew_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
    ]
