# Generated by Django 3.2.12 on 2022-04-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_epoch'),
        ('armory', '0046_item_homebrew_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='riotgear',
            name='homebrew_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='riotgear',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='is homebrew'),
        ),
    ]
