# Generated by Django 3.2.12 on 2022-04-24 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_epoch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armory', '0048_riotgear_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='homebrew_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='is homebrew'),
        ),
    ]
