# Generated by Django 3.2.12 on 2022-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0049_auto_20220424_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='keep_as_homebrew',
            field=models.BooleanField(default=False, help_text='This was not accepted as general item and is kept as homebrew.', verbose_name='keep as homebrew'),
        ),
    ]
