# Generated by Django 3.2.12 on 2022-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0050_item_keep_as_homebrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='keep_as_homebrew',
            field=models.BooleanField(default=False, help_text='This was not accepted as general weapon and is kept as homebrew.', verbose_name='keep as homebrew'),
        ),
    ]
