# Generated by Django 3.2.15 on 2022-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0052_riotgear_keep_as_homebrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='charges',
            field=models.IntegerField(blank=True, null=True, verbose_name='charges'),
        ),
    ]
