# Generated by Django 3.2.15 on 2022-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0053_item_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='is container'),
        ),
    ]
