# Generated by Django 4.1.3 on 2022-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0054_item_is_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymapunit',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Is this the common unit people pay with?', verbose_name='is common'),
        ),
    ]
