# Generated by Django 4.1.3 on 2022-12-11 12:50

from django.db import migrations


def forwards(apps, schema_editor):
    CurrencyMapUnit = apps.get_model('armory', 'CurrencyMapUnit')
    for common in ["Gulden", 'Euro', "Dollar", "Mark"]:
        CurrencyMapUnit.objects.filter(name=common).update(is_common=True)


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0055_currencymapunit_is_common'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
