# Generated by Django 4.1.3 on 2022-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0056_auto_20221211_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencymapunit',
            options={'get_latest_by': ('id',), 'ordering': ('-ordering',)},
        ),
        migrations.AddField(
            model_name='currencymapunit',
            name='ordering',
            field=models.IntegerField(default=10, verbose_name='ordering'),
        ),
    ]
