# Generated by Django 4.1.3 on 2022-12-12 22:33

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    WeaponModificationAttributeChange = apps.get_model('armory', 'WeaponModificationAttributeChange')
    for wma in WeaponModificationAttributeChange.objects.all():
        if wma.attribute == 'bonus_dice':
            wma.attribute = 'damage_potential'
            wma.save()


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0057_alter_currencymapunit_options_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.RenameField(
            model_name='weapon',
            old_name='bonus_dice',
            new_name='damage_potential',
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('wounds', 'Bonus wounds'), ('damage_potential', 'Damage potential'), ('piercing', 'Piercing'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
