# Generated by Django 4.1.3 on 2022-12-12 23:01

from django.db import migrations


def forwards(apps, schema_editor):
    AttackMode = apps.get_model('armory', 'AttackMode')
    automatic = AttackMode.objects.get(id=4)
    automatic.delete()
    AttackMode.objects.filter(id__in=[3, 1]).update(dice_bonus=0)

    WeaponAttackMode = apps.get_model('armory', 'WeaponAttackMode')
    WeaponAttackMode.objects.all().update(dice_bonus_override=None)


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0058_remove_weapon_bonus_dice_weapon_damage_potential_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
