# Generated by Django 4.1.3 on 2022-12-12 23:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0059_auto_20221212_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='wounds',
        ),
        migrations.AddField(
            model_name='weapon',
            name='crit_minimum_roll',
            field=models.IntegerField(default=11, verbose_name='crit minimum roll'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='encumbrance',
            field=models.IntegerField(default=1, verbose_name='encumbrance'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='time_to_ready',
            field=models.IntegerField(default=1, verbose_name='time to ready'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_potential',
            field=models.IntegerField(default=0, verbose_name='damage potential'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('time_to_ready', 'Time to ready'), ('crit_minimum_roll', 'Crit minimum roll'), ('encumbrance', 'Encumbrance'), ('damage_potential', 'Damage potential'), ('piercing', 'Piercing'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
