# Generated by Django 4.1.3 on 2022-12-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0060_remove_weapon_wounds_weapon_crit_minimum_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='time_to_ready',
        ),
        migrations.AddField(
            model_name='weapon',
            name='actions_to_ready',
            field=models.IntegerField(default=1, verbose_name='actions to ready'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('actions_to_ready', 'Actions to ready'), ('crit_minimum_roll', 'Crit minimum roll'), ('encumbrance', 'Encumbrance'), ('damage_potential', 'Damage potential'), ('piercing', 'Piercing'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
