# Generated by Django 4.1.3 on 2022-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0061_remove_weapon_time_to_ready_weapon_actions_to_ready_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotGearType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=256, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='riotgear',
            name='evasion',
        ),
        migrations.AddField(
            model_name='riotgear',
            name='encumbrance',
            field=models.IntegerField(default=1, verbose_name='encumbrance'),
        ),
    ]
