# Generated by Django 4.1.3 on 2022-12-14 22:15

from django.db import migrations


def forwards(apps, schema_editor):
    RiotGearType = apps.get_model('armory', 'RiotGearType')
    RiotGearType.objects.create(
        name_de="Leichte Rüstung",
        name_en="Light armour"
    )
    RiotGearType.objects.create(
        name_de="Mittlere Rüstung",
        name_en="Medium armour"
    )
    RiotGearType.objects.create(
        name_de="Schwere Rüstung",
        name_en="Heavy armour"
    )
    RiotGearType.objects.create(
        name_de="Schild",
        name_en="Shield"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('armory', '0062_riotgeartype_remove_riotgear_evasion_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
