# Generated by Django 4.1.3 on 2022-12-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0063_auto_20221214_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='riotgear',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armory.riotgeartype', verbose_name='type'),
            preserve_default=False,
        ),
    ]
