# Generated by Django 4.1.3 on 2022-12-14 22:57

from django.db import migrations


def forward(apps, schema_editor):
    RiotGear = apps.get_model('armory', 'RiotGear')
    RiotGearType = apps.get_model('armory', 'RiotGearType')

    RiotGearType.objects.create(
        name_de="Kleidung",
        name_en="Clothing"
    )
    for rg in RiotGear.objects.all():
        if rg.protection_ballistic < 1:
            rg.type = RiotGearType.objects.get(name_en='Clothing')
            rg.encumbrance = 0
        elif rg.protection_ballistic < 2:
            rg.type = RiotGearType.objects.get(name_en='Light armour')
            rg.encumbrance = 1
        elif rg.protection_ballistic < 3:
            rg.type = RiotGearType.objects.get(name_en='Medium armour')
            rg.encumbrance = 2
        else:
            rg.type = RiotGearType.objects.get(name_en='Heavy armour')
            rg.encumbrance = 4

        if 'schild' in rg.name_de.lower():
            rg.type = RiotGearType.objects.get(name_en='Shield')
            rg.encumbrance = 2
        rg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0064_riotgear_type'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
