# Generated by Django 4.1.3 on 2022-12-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0065_auto_20221214_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='encumbrance',
            field=models.IntegerField(default=0, verbose_name='encumbrance'),
        ),
    ]
