# Generated by Django 4.1.3 on 2022-12-15 00:32

from django.db import migrations


def forward(apps, schema_editor):
    Weapon = apps.get_model('armory', 'Weapon')
    WeaponType = apps.get_model('armory', 'WeaponType')

    for weapon in Weapon.objects.all():
        if weapon.type.id in [1, 3, 8, 10]:
            weapon.encumbrance = 0
        elif weapon.type.id in [2, 4, 5, 11]:
            weapon.encumbrance = 1
        else:
            weapon.encumbrance = 2
        weapon.save()


class Migration(migrations.Migration):
    dependencies = [
        ('armory', '0066_alter_weapon_encumbrance'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
