# Generated by Django 4.1.6 on 2023-02-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0067_auto_20221215_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riotgeartype',
            options={'ordering': ('-ordering',)},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={'ordering': ('-ordering',), 'verbose_name': 'weapon type', 'verbose_name_plural': 'weapon types'},
        ),
        migrations.AddField(
            model_name='riotgeartype',
            name='ordering',
            field=models.IntegerField(default=10, verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='ordering',
            field=models.IntegerField(default=10, verbose_name='ordering'),
        ),
    ]
