# Generated by Django 4.1.6 on 2023-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0068_alter_riotgeartype_options_alter_weapontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ('-ordering',), 'verbose_name': 'item type', 'verbose_name_plural': 'item types'},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='ordering',
            field=models.IntegerField(default=10, verbose_name='ordering'),
        ),
    ]
