# Generated by Django 4.1.7 on 2023-03-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0069_alter_itemtype_options_itemtype_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='recoil_compensation',
            field=models.IntegerField(default=0, verbose_name='recoil compensation'),
        ),
    ]
