# Generated by Django 4.1.7 on 2023-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0070_weapon_recoil_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_throwing_weapon',
            field=models.BooleanField(default=False, verbose_name='is throwing weapon'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('recoil_compensation', 'Recoil compensation'), ('actions_to_ready', 'Actions to ready'), ('crit_minimum_roll', 'Crit minimum roll'), ('encumbrance', 'Encumbrance'), ('damage_potential', 'Damage potential'), ('piercing', 'Piercing'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
